In [1]:
import pandas as pd
import numpy as np

In [2]:
ppp_df = pd.read_csv("../data/ppp_pipe.csv")
ppp_df

,Unnamed: 0,Unnamed: 0.1,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,...,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add
0,0,0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,...,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC"
1,1,1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,...,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC"
2,2,2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,...,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA"
3,3,3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,...,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,4,4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,...,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968552,968552,968552,4395967002,897,PPP,"ROY E PAULSON, JR., P.C.",102 N. Kenwood,CASPER,WY,82601.0,...,Offices of Dentists,999 Other,6212 Offices of Dentists,6212,62,Health Care and Social Assistance,WYOMING DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"102 N. Kenwood, CASPER, WY"
968553,968553,968553,6985647108,897,PPP,"SWEETWATER COUNTY CHILD DEVELOPMENTAL CENTER, ...",1715 HITCHING POST DR,GREEN RIVER,WY,82935.0,...,Child Day Care Services,999 Other,6244 Child Day Care Services,6244,62,Health Care and Social Assistance,WYOMING DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"1715 HITCHING POST DR, GREEN RIVER, WY"
968554,968554,968554,7996438405,897,PPS,ELECTRICAL SYSTEMS OF WYOMING INC,1105 Adon Rd,Rozet,WY,82727.0,...,Electrical Contractors and Other Wiring Instal...,999 Other,2382 Building Equipment Contractors,2382,23,Construction,WYOMING DISTRICT OFFICE,"a $150,000-350,000",Fewer than 5,"1105 Adon Rd, Rozet, WY"
968555,968555,968555,9054647103,897,PPP,EDEN LIFE CARE,30 N. Gould Street Suite 4000,SHERIDAN,WY,82801.0,...,Home Health Care Services,999 Other,6216 Home Health Care Services,6216,62,Health Care and Social Assistance,WYOMING DISTRICT OFFICE,"a $150,000-350,000",5 to 9,"30 N. Gould Street Suite 4000, SHERIDAN, WY"
968556,968556,968556,9184687004,897,PPP,S & S JOHNSON ENTERPRISES INC,7342 Granite Loop Rd,TETON VILLAGE,WY,83025.0,...,Full-Service Restaurants,999 Other,7225 Restaurants and Other Eating Places,7225,72,Accommodation and Food Services,WYOMING DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"7342 Granite Loop Rd, TETON VILLAGE, WY"

In [8]:
ppp_df["NAICSCode"].dtype

dtype('int64')

<h4>Industry Sector Review

In [3]:
#pd.set_option('display.max_rows', None)
ppp_df_industry = ppp_df.groupby(["Industry", "IndustrySubsector"]).agg({ "LoanNumber": 'count'})
ppp_df_industry #312

                                                                                    LoanNumber
Industry                        IndustrySubsector
Accommodation and Food Services 7211 Traveler Accommodation                              20906
                                7212 RV (Recreational Vehicle) Parks and Recrea...        1158
                                7213 Rooming and Boarding Houses, Dormitories, ...         120
                                7223 Special Food Services                                4393
                                7224 Drinking Places (Alcoholic Beverages)                4002
...                                                                                        ...
Wholesale Trade                 4246 Chemical and Allied Products Merchant Whol...         955
                                4247 Petroleum and Petroleum Products Merchant ...        1490
                                4248 Beer, Wine, and Distilled Alcoholic Bevera...        1114
                                4249 Miscellaneous Nondurable Goods Merchant Wh...        3587
                                4251 Wholesale Electronic Markets and Agents an...        1281

[314 rows x 1 columns]

In [4]:
ppp_df_industry = ppp_df.groupby(["Industry", "IndustrySubsector", "Loan_Range", "BusinessType"]).agg({ "LoanNumber": 'count'})
ppp_df_industry  #9801

                                                                                                                                           LoanNumber
Industry                        IndustrySubsector                                  Loan_Range         BusinessType
Accommodation and Food Services 7211 Traveler Accommodation                        a $150,000-350,000 501(c)6 – Non Profit Membership               1
                                                                                                      Cooperative                                   4
                                                                                                      Corporation                                2601
                                                                                                      Employee Stock Ownership Plan(ESOP)           1
                                                                                                      Independent Contractors                       1
...                                                                                                                                               ...
Wholesale Trade                 4251 Wholesale Electronic Markets and Agents an... d $2-5 million     Corporation                                   5
                                                                                                      Limited Liability Company(LLC)                1
                                                                                                      Subchapter S Corporation                      5
                                                                                   e $5-10 million    Employee Stock Ownership Plan(ESOP)           1
                                                                                                      Limited Liability Company(LLC)                2

[9887 rows x 1 columns]

In [5]:
#pd.set_option('display.max_rows', None)
ppp_df["IndustrySubsector"].nunique()

314

In [6]:
ppp_df.loc[ppp_df["4DigitNAICS"] == "6115", "IndustrySubsector"] = "6115 Technical and Trade Schools"
edu_ppp = ppp_df.loc[ppp_df["Industry"] == "Educational Services"]
edu_ppp.groupby(["Industry", "IndustrySubsector"]).agg({"LoanNumber": "count"})

                                                                         LoanNumber
Industry             IndustrySubsector
Educational Services 6111 Elementary and Secondary Schools                    10032
                     6112 Junior Colleges                                       101
                     6113 Colleges, Universities, and Professional S...        1370
                     6114 Business Schools and Computer and Manageme...         873
                     6115 Technical and Trade Schools                          1013
                     6115 Technical and Trade Schools                           113
                     6116 Other Schools and Instruction                        3742
                     6117 Educational Support Services                         2781

In [7]:
#ppp_df.loc[ppp_df["4DigitNAICS"] == "6115", "IndustrySubsector"] = "6115 Technical and Trade Schools"
manppp = ppp_df.loc[ppp_df["Industry"] == "Utilities"]
manppp["IndustrySubsector"].sort_values().unique().tolist()

['2211 Electric Power Generation, Transmission and Distribution',
 '2212 Natural Gas Distribution ',
 '2213 Water, Sewage and Other Systems ']

<b>Industries - 26

In [8]:
indss_df_na =  ppp_df.groupby(["IndustrySubsector",  "4DigitNAICS"], as_index=False).agg({ "LoanNumber": 'count'}) #327
indss_df_na.head()

                                   IndustrySubsector  4DigitNAICS  LoanNumber
0                     1111 Oilseed and Grain Farming         1111         783
1                   1112 Vegetable and Melon Farming         1112         900
2                    1113 Fruit and Tree Nut Farming         1113        1630
3  1114 Greenhouse, Nursery, and Floriculture Pro...         1114        1230
4                            1119 Other Crop Farming         1119        1329

<b>Industry, Subsector - 328, accounts for Subsector = 0

In [9]:
#pd.set_option('display.max_rows', None)
indss_df = ppp_df.groupby(["Industry", "NA", "4DigitNAICS"]).agg({ "LoanNumber": 'count'}) #327
indss_df

                                                LoanNumber
Industry                        NA 4DigitNAICS
Accommodation and Food Services 72 7211              20906
                                   7212               1158
                                   7213                120
                                   7223               4393
                                   7224               4002
...                                                    ...
Wholesale Trade                 42 4246                955
                                   4247               1490
                                   4248               1114
                                   4249               3587
                                   4251               1281

[313 rows x 1 columns]

In [10]:
indss_df =  ppp_df.groupby(["Industry", "NA", "IndustrySubsector", "4DigitNAICS"]).agg({ "LoanNumber": 'count'}) #327
print(indss_df.shape[0])
indss_df

314

                                                                                                   LoanNumber
Industry                        NA IndustrySubsector                                  4DigitNAICS
Accommodation and Food Services 72 7211 Traveler Accommodation                        7211              20906
                                   7212 RV (Recreational Vehicle) Parks and Recrea... 7212               1158
                                   7213 Rooming and Boarding Houses, Dormitories, ... 7213                120
                                   7223 Special Food Services                         7223               4393
                                   7224 Drinking Places (Alcoholic Beverages)         7224               4002
...                                                                                                       ...
Wholesale Trade                 42 4246 Chemical and Allied Products Merchant Whol... 4246                955
                                   4247 Petroleum and Petroleum Products Merchant ... 4247               1490
                                   4248 Beer, Wine, and Distilled Alcoholic Bevera... 4248               1114
                                   4249 Miscellaneous Nondurable Goods Merchant Wh... 4249               3587
                                   4251 Wholesale Electronic Markets and Agents an... 4251               1281

[314 rows x 1 columns]

In [11]:
ppp_df['BusinessType'].value_counts()

Corporation                            415963
Limited Liability Company(LLC)         261542
Subchapter S Corporation               177322
Non-Profit Organization                 54932
Partnership                             18086
Limited Liability Partnership           12737
Sole Proprietorship                     12429
Professional Association                 6780
Cooperative                              2449
501(c)3 – Non Profit                     1790
Non-Profit Childcare Center               909
501(c)6 – Non Profit Membership           765
Not Available                             728
Employee Stock Ownership Plan(ESOP)       636
Self-Employed Individuals                 497
Trust                                     408
Housing Co-op                             152
Joint Venture                             129
Independent Contractors                   116
Single Member LLC                          76
Tribal Concerns                            63
Tenant in Common                           31
501(c) – Non Profit except 3,4,6,          10
Rollover as Business Start-Ups (ROB         3
501(c)19 – Non Profit Veterans              2
Qualified Joint-Venture (spouses)           2
Name: BusinessType, dtype: int64

<h4>Hashing Code Values

In [12]:
pd.set_option('display.max_columns', None)
ppp_df_hash = ppp_df
ppp_df_hash = ppp_df_hash.drop(["Unnamed: 0", "Unnamed: 0.1"], axis=1)
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC"
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC"
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA"
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI"

Industry Conditions

In [16]:
ppp_df_hash["NA"]=ppp_df_hash["NA"].apply(str)
ppp_df_hash["4DigitNAICS"]=ppp_df_hash["4DigitNAICS"].apply(str)

In [17]:
ppp_df_hash["INDcode"] = 'IND' + ppp_df_hash["NA"]
ppp_df_hash["SScode"] = 'SS' + ppp_df_hash["4DigitNAICS"].str[-2:]
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42

Loan Conditions

In [18]:
loan_conditions = [
(ppp_df_hash.Loan_Range == "a $150,000-350,000" ),
(ppp_df_hash.Loan_Range == "b $350,000-1 million" ),
(ppp_df_hash.Loan_Range == "c $1-2 million" ),
(ppp_df_hash.Loan_Range == "d $2-5 million" ),
(ppp_df_hash.Loan_Range == "e $5-10 million" ),
]
loan_values = ["LR1","LR2","LR3","LR4","LR5"]
ppp_df_hash['LRcode'] = np.select(loan_conditions, loan_values)
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2

Job Range Conditions

In [19]:
jobrange_conditions = [
    (ppp_df_hash.job_Range == 'Fewer than 5'),
    (ppp_df_hash.job_Range == '5 to 9'),
    (ppp_df_hash.job_Range == '10 to 19'),
    (ppp_df_hash.job_Range == '20 to 49'),
    (ppp_df_hash.job_Range == '50 to 99'),
    (ppp_df_hash.job_Range == '100 to 249'),
    (ppp_df_hash.job_Range == '250 to 499'),
    (ppp_df_hash.job_Range == '500 or more'),
]

jobrange_values = ['JR1', 'JR2', 'JR3', 'JR4', 'JR5',
       'JR6', 'JR7', 'JR8']

ppp_df_hash['JRcode'] = np.select(jobrange_conditions , jobrange_values)
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4

In [20]:
ppp_df_hash['JRcode'].value_counts()

JR4    417145
JR3    242131
JR5    161529
JR6     84789
JR2     31387
JR7     22073
JR1      5145
JR8      4358
Name: JRcode, dtype: int64

Business Type Conditions

In [21]:
businesstype_conditions = [
    (ppp_df_hash.BusinessType == "Corporation"),
    (ppp_df_hash.BusinessType == "Limited Liability Company(LLC)"),
    (ppp_df_hash.BusinessType == "Subchapter S Corporation"),
    (ppp_df_hash.BusinessType == "Non-Profit Organization"),
    (ppp_df_hash.BusinessType == "Partnership"),
    (ppp_df_hash.BusinessType == "Limited Liability Partnership"),
    (ppp_df_hash.BusinessType == "Sole Proprietorship"),
    (ppp_df_hash.BusinessType == "Professional Association"),
    (ppp_df_hash.BusinessType == "Cooperative"),
    (ppp_df_hash.BusinessType == "501(c)3 – Non Profit"),
    (ppp_df_hash.BusinessType == "Non-Profit Childcare Center"),
    (ppp_df_hash.BusinessType == "501(c)6 – Non Profit Membership"),
    (ppp_df_hash.BusinessType == "Not Available"),
    (ppp_df_hash.BusinessType == "Employee Stock Ownership Plan(ESOP)"),
    (ppp_df_hash.BusinessType == "Self-Employed Individuals"),
    (ppp_df_hash.BusinessType == "Trust"),
    (ppp_df_hash.BusinessType == "Housing Co-op"),
    (ppp_df_hash.BusinessType == "Joint Venture"),
    (ppp_df_hash.BusinessType == "Independent Contractors"),
    (ppp_df_hash.BusinessType == "Single Member LLC"),
    (ppp_df_hash.BusinessType == "Tribal Concerns"),
    (ppp_df_hash.BusinessType == "Tenant in Common"),
    (ppp_df_hash.BusinessType == "501(c) – Non Profit except 3,4,6,"),
    (ppp_df_hash.BusinessType == "Rollover as Business Start-Ups (ROB"),
    (ppp_df_hash.BusinessType == "501(c)19 – Non Profit Veterans"),
    (ppp_df_hash.BusinessType == "Qualified Joint-Venture (spouses)"),
    
    
]

businesstype_values = ["BT01", "BT02", "BT03", "BT04", "BT05", 
                       "BT06", "BT07", "BT08", "BT09", "BT10", 
                       "BT11", "BT12", "BT13", "BT14", "BT15", 
                       "BT16", "BT17", "BT18", "BT19", "BT20", 
                       "BT21", "BT22", "BT23", "BT24", "BT25",
                       "BT26"]
ppp_df_hash['BTcode'] = np.select(businesstype_conditions, businesstype_values)
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13

In [22]:
ppp_df_hash['BTcode'].value_counts()

BT01    415963
BT02    261542
BT03    177322
BT04     54932
BT05     18086
BT06     12737
BT07     12429
BT08      6780
BT09      2449
BT10      1790
BT11       909
BT12       765
BT13       728
BT14       636
BT15       497
BT16       408
BT17       152
BT18       129
BT19       116
BT20        76
BT21        63
BT22        31
BT23        10
BT24         3
BT25         2
BT26         2
Name: BTcode, dtype: int64

Business Age Conditions

In [23]:
businessage_conditions = [
    (ppp_df_hash.BusinessAgeDescription == 'Existing or more than 2 years old'),
    (ppp_df_hash.BusinessAgeDescription == 'New Business or 2 years or less'),
    (ppp_df_hash.BusinessAgeDescription == 'Unanswered'),
    (ppp_df_hash.BusinessAgeDescription == 'Change of Ownership'),
    (ppp_df_hash.BusinessAgeDescription == 'Startup, Loan Funds will Open Business'),
]
businessage_values = ["BA1", "BA2", "BA3", "BA4", "BA5"]
ppp_df_hash['BAcode'] = np.select(businessage_conditions, businessage_values)
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3

In [24]:
ppp_df_hash['BAcode'].value_counts()

BA1    861935
BA2     54854
BA3     51056
BA4       422
BA5       290
Name: BAcode, dtype: int64

<b>Alt Process Codes

In [25]:
ppp_df_hash["PMcode"] = ppp_df_hash["ProcessingMethod"] # PPP/PPS
ppp_df_hash["NPcode"] = 'NP' + ppp_df_hash["NonProfit"] # Y/N
ppp_df_hash["LMIcode"] = 'LMI' +ppp_df_hash["LMIIndicator"] #Y/N
ppp_df_hash["HZcode"] = 'HZ' + ppp_df_hash["HubzoneIndicator"] #Y/N
ppp_df_hash["RUcode"] = ppp_df_hash["RuralUrbanIndicator"] #U/R
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1,PPP,NPN,LMIN,HZN,U
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1,PPP,NPN,LMIY,HZY,U
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2,PPP,NPY,LMIN,HZN,U
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2,PPP,NPN,LMIN,HZN,U
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3,PPP,NPN,LMIN,HZN,U

In [26]:
md_groups = ppp_df_hash.loc[ppp_df_hash["BorrowerState"] == "MD"]
md_groups.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode
425853,4142717108,373,PPP,"PT NETWORK, LLC",501 Fairmount Ave,Towson,MD,21286.0,7/15/21,Paid in Full,24,100,10000000.0,10000000.0,0.0,NaN,455644,Live Oak Banking Company,1741 Tiburon Dr,WILMINGTON,NC,28403-6244,U,N,Y,Existing or more than 2 years old,Towson,BALTIMORE,MD,21286-0500,MD-02,500.0,621340,White,Not Hispanic or Latino,NaN,10000000.0,NaN,NaN,NaN,NaN,NaN,Limited Liability Company(LLC),455644,Live Oak Banking Company,WILMINGTON,NC,Male Owned,Non-Veteran,N,10114520.55,1%,100000.0,20200412,20210611,"Offices of Physical, Occupational and Speech T...",999 Other,6213 Offices of Other Health Practitioners,6213,62,Health Care and Social Assistance,BALTIMORE DISTRICT OFFICE,e $5-10 million,500 or more,"501 Fairmount Ave, Towson, MD",IND62,SS13,LR5,JR8,BT02,BA1,PPP,NPN,LMIY,HZN,U
425854,4682157009,373,PPP,"GMS MINE REPAIR AND MAINTENANCE, INC.",PO Box 2446 32 Enterprise Drive,OAKLAND,MD,21550.0,7/17/21,Paid in Full,24,100,10000000.0,10000000.0,0.0,NaN,30767,First United Bank & Trust,19 S 2nd St,OAKLAND,MD,21550-1517,R,N,N,Existing or more than 2 years old,OAKLAND,GARRETT,MD,21550-0001,MD-06,500.0,212112,Unanswered,Unknown/NotStated,NaN,10000000.0,NaN,NaN,NaN,NaN,NaN,Corporation,30767,First United Bank & Trust,OAKLAND,MD,Unanswered,Veteran,N,10118611.11,1%,100000.0,20200404,20210615,Bituminous Coal Underground Mining,2121 Coal Mining,2121 Coal Mining,2121,21,"Mining, Quarrying, and Oil and Gas Extraction",BALTIMORE DISTRICT OFFICE,e $5-10 million,500 or more,"PO Box 2446 32 Enterprise Drive, OAKLAND, MD",IND21,SS21,LR5,JR8,BT01,BA1,PPP,NPN,LMIN,HZN,R
425855,8298497108,373,PPP,"GSE SYSTEMS, INC.",1332 Londontown Blvd 200,Sykesville,MD,21784.0,9/29/21,Paid in Full,24,100,10000000.0,10000000.0,0.0,NaN,434162,"Citizens Bank, National Association",1 Citizens Plaza,PROVIDENCE,RI,02903-1344,R,N,N,Existing or more than 2 years old,Sykesville,CARROLL,MD,21784-0001,MD-08,380.0,333318,Unanswered,Unknown/NotStated,NaN,10000000.0,NaN,NaN,NaN,NaN,NaN,Corporation,434162,"Citizens Bank, National Association",PROVIDENCE,RI,Unanswered,Unanswered,N,10126849.32,1%,100000.0,20200415,20210802,Other Commercial and Service Industry Machiner...,333 Machinery,3333 Commercial and Service Industry Machinery...,3333,33,Manufacturing,BALTIMORE DISTRICT OFFICE,e $5-10 million,250 to 499,"1332 Londontown Blvd 200, Sykesville, MD",IND33,SS33,LR5,JR7,BT01,BA1,PPP,NPN,LMIN,HZN,R
425856,8415647105,373,PPP,"MISSION BBQ MANAGEMENT, LLC",7750 Governor Ritchie Highway,Glen Burnie,MD,21061.0,7/8/21,Paid in Full,24,100,10000000.0,10000000.0,0.0,NaN,46391,Manufacturers and Traders Trust Company,"One M & T Plaza, 15th Fl",BUFFALO,NY,14203,U,N,N,Existing or more than 2 years old,Glen Burnie,ANNE ARUNDEL,MD,21061-0312,MD-03,500.0,722511,Unanswered,Unknown/NotStated,900000.0,7600000.0,0.0,890000.0,0.0,610000.0,0.0,Limited Liability Company(LLC),46391,Manufacturers and Traders Trust Company,BUFFALO,NY,Unanswered,Unanswered,N,10113698.63,1%,100000.0,20200415,20210611,Full-Service Restaurants,999 Other,7225 Restaurants and Other Eating Places,7225,72,Accommodation and Food Services,BALTIMORE DISTRICT OFFICE,e $5-10 million,500 or more,"7750 Governor Ritchie Highway, Glen Burnie, MD",IND72,SS25,LR5,JR8,BT02,BA1,PPP,NPN,LMIN,HZN,U
425857,9405257009,373,PPP,LEMEK LLC,8184 Lark Brown Road Suite 201,ELKRIDGE,MD,21075.0,NaN,Exemption 4,24,100,10000000.0,10000000.0,0.0,Panera Bread,30872,Sandy Spring Bank,17801 Georgia Ave,OLNEY,MD,20832-2233,U,N,N,Existing or more than 2 years old,ELKRIDGE,HOWARD,MD,21075-3401,MD-03,500.0,722513,Unanswered,Not Hispanic or Latino,NaN,10000000.0,NaN,NaN,NaN,NaN,NaN,Subchapter S Corporation,30872,Sandy Spring Bank,OLNEY,MD,Male Owned,Non-Veteran,N,NaN,1%,100000.0,20200409,NaT,Limited-Service Restaurants,999 Other,7225 Restaurants and Other Eating Places,7225,72,Accommodation and Food Services,BALTIMORE DISTRICT OFFICE,e $5-10 million,500 or more,"8184 Lark Brown Road Suite 201, ELKRIDGE, MD",IND72,SS25,LR5,JR8,BT03,BA1,PPP,NPN,LMIN,HZN,U

Creating HASHcodes

In [27]:
### Industry, Subsector
ppp_df_hash["INDSScode"] = ppp_df_hash["INDcode"]  + ppp_df_hash["SScode"]


# Loan Range, Business Type, Industry, Subsector
#ppp_df_hash["HASHcodebase1"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode']
#ppp_df_hash["HASHcodebase2"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['JRcode']
#ppp_df_hash["HASHcodebase3"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['BTcode']
#ppp_df_hash["HASHcodebase4"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['BAcode']
#ppp_df_hash["HASHcodebase5"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['PMcode']
# Loan Range, Business Type, Industry, Subsector
#ppp_df_hash["HASHcodebaseJR"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] 
# Loan Range, Business Type, Industry, Subsector
#ppp_df_hash["HASHcodebaseJRBT"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] 
# Loan Range, Business Type, JobRange, Industry, Subsector
#ppp_df_hash["HASHcodebaseJRBTBA"] =  ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode'] + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash['BAcode']


# Loan Range, Business Type, JobRange, Industry, Subsector, ProcessingMethod
ppp_df_hash["HASHcodePM"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] + ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash['BAcode'] + ppp_df_hash["PMcode"]
# Loan Range, Business Type, JobRange, Industry, Subsector, ProcessingMethod, Nonprofit, LMI, Hubzone, RuralUrban
#ppp_df_hash["HASHcodefull"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] + ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash["PMcode"] + ppp_df_hash["NPcode"] + ppp_df_hash["LMIcode"] + ppp_df_hash["HZcode"]  + ppp_df_hash["RUcode"]
#ppp_df_hash["HASHcodePMr"] = ppp_df_hash["PMcode"] + ppp_df_hash['LRcode'] + ppp_df_hash['BAcode'] + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash["INDcode"] + ppp_df_hash["SScode"]  
ppp_df_hash.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodePM
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1,PPP,NPN,LMIN,HZN,U,IND32SS55,IND32SS55LR2JR5BT01BA1PPP
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1,PPP,NPN,LMIY,HZY,U,IND56SS17,IND56SS17LR2JR5BT07BA1PPP
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2,PPP,NPY,LMIN,HZN,U,IND0SS0,IND0SS0LR2JR5BT04BA2PPP
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2,PPP,NPN,LMIN,HZN,U,IND23SS61,IND23SS61LR2JR4BT01BA2PPP
4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3,PPP,NPN,LMIN,HZN,U,IND48SS42,IND48SS42LR2JR4BT13BA3PPP

In [28]:
#md_groups = md_groups.groupby(["INDcode", "Industry", "INDSScode", "IndustrySubsector"]).agg({"LoanNumber":"count"})
#md_groups.shape[0] #290


#groups = ppp_df_hash.groupby(["INDcode", "Industry", "INDSScode", "IndustrySubsector"]).agg({"LoanNumber":"count"})
#groups.shape[0] #

In [29]:
print(ppp_df_hash["INDSScode"].nunique()) #328

'''
print(ppp_df_hash["HASHcodebase1"].nunique()) #1580 LR
print(ppp_df_hash["HASHcodebase2"].nunique()) #2431  JR
print(ppp_df_hash["HASHcodebase3"].nunique()) #3499 BT
print(ppp_df_hash["HASHcodebase4"].nunique()) #1227 BA
print(ppp_df_hash["HASHcodebase5"].nunique()) #639 PM

print(ppp_df_hash["HASHcodebaseJR"].nunique()) #6924
print(ppp_df_hash["HASHcodebaseJRBT"].nunique()) #26945
print(ppp_df_hash["HASHcodebaseJRBTBA"].nunique()) #43458
'''
print(ppp_df_hash["HASHcodePM"].nunique()) #55127


#print(ppp_df_hash["HASHcode"].nunique()) # 26945
#print(ppp_df_hash["HASHcodePM"].nunique()) # 55127
#print(ppp_df_hash["HASHcodefull"].nunique()) #108534 combinations

313
54996

In [30]:
ppp_df["ServicingLenderLocationID"].nunique() #4810
ppp_df["ServicingLenderName"].nunique() #4295

4295

Writing HASHcode File

In [31]:
ppp_df_hash.to_csv("../data/ppp_hash.csv")

In [32]:
ppp_df_hash["BTcode"].value_counts()

BT01    415963
BT02    261542
BT03    177322
BT04     54932
BT05     18086
BT06     12737
BT07     12429
BT08      6780
BT09      2449
BT10      1790
BT11       909
BT12       765
BT13       728
BT14       636
BT15       497
BT16       408
BT17       152
BT18       129
BT19       116
BT20        76
BT21        63
BT22        31
BT23        10
BT24         3
BT25         2
BT26         2
Name: BTcode, dtype: int64

In [33]:
print(ppp_df_hash.isnull().sum())

LoanNumber          0
SBAOfficeCode       0
ProcessingMethod    0
BorrowerName        4
BorrowerAddress     6
                   ..
LMIcode             0
HZcode              0
RUcode              0
INDSScode           0
HASHcodePM          0
Length: 78, dtype: int64

In [34]:
## option FIPS hashing, State, County, BlockGroup additions - separate

In [35]:
ppp_df_hash = pd.read_csv("../data/ppp_hash.csv")
ppp_df_hash.head()

,Unnamed: 0,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodePM
0,0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150.0,12/18/20,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,N,773553.37,3%,23080.7634,20200501,20201120,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1,PPP,NPN,LMIN,HZN,U,IND32SS55,IND32SS55LR2JR5BT01BA1PPP
1,1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420.0,9/28/21,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,N,746336.24,3%,22107.8337,20200501,20210812,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1,PPP,NPN,LMIY,HZY,U,IND56SS17,IND56SS17LR2JR5BT07BA1PPP
2,2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112.0,3/17/21,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,0,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,3%,20740.6500,20200501,20210210,NaN,NaN,Not Available,0,0,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2,PPP,NPY,LMIN,HZN,U,IND0SS0,IND0SS0LR2JR5BT04BA2PPP
3,3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407.0,10/16/21,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-08,21.0,236115,Unanswered,Unknown/NotStated,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,N,395264.11,3%,14996.1300,20200501,20210910,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2,PPP,NPN,LMIN,HZN,U,IND23SS61,IND23SS61LR2JR4BT01BA2PPP
4,4,9662437702,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,NaN,8/17/21,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,Not Available,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,N,370819.35,3%,11023.1100,20200501,20210408,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3,PPP,NPN,LMIN,HZN,U,IND48SS42,IND48SS42LR2JR4BT13BA3PPP

<b>Sorting Hash Arrays (used to combine feature groups)

In [36]:
ppp_df_hash.loc[ppp_df_hash["LoanNumber"] == 3894287707]

,Unnamed: 0,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,Estimated_LenderPercent,Estimated_LenderProfit,DateApprovedTS,ForgivenessDateTS,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodePM
116929,116929,3894287707,912,PPP,PHD UROLOGY,1240 S. ELISEO DRIVE SUITE 200,GREENBRAE,CA,94904.0,NaN,Exemption 4,24,100,241386.0,241386.0,0.0,NaN,12096,"Wells Fargo Bank, National Association",101 N Philips Ave,SIOUX FALLS,SD,57104-6738,U,N,Y,Existing or more than 2 years old,GREENBRAE,MARIN,CA,94904-1000,CA-02,3.0,0,Unanswered,Unknown/NotStated,NaN,241386.0,NaN,NaN,NaN,NaN,NaN,Corporation,12096,"Wells Fargo Bank, National Association",SIOUX FALLS,SD,Unanswered,Unanswered,N,NaN,5%,12069.3,20200501,NaT,NaN,NaN,Not Available,0,0,Not Available,SAN FRANCISCO DISTRICT OFFICE,"a $150,000-350,000",Fewer than 5,"1240 S. ELISEO DRIVE SUITE 200, GREENBRAE, CA",IND0,SS0,LR1,JR1,BT01,BA1,PPP,NPN,LMIY,HZN,U,IND0SS0,IND0SS0LR1JR1BT01BA1PPP

cols= ["LoanNumber", "INDSScode", "INDcode", "SScode", "LRcode","JRcode", "BTcode", "BAcode", "PMcode", "HASHcodebaseJRBT", "HASHcodePM"]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["PMcode", "LRcode", "BAcode", "JRcode",  "BTcode", "INDcode", "SScode"], ascending=[True, True, True, True, True, True, True], ignore_index=True)
ppp_df_hashSort.head(40)

In [38]:
cols= ["LoanNumber", "INDSScode", "INDcode", "SScode", "LRcode","JRcode", "BTcode", "BAcode", "PMcode", "HASHcodePM", "Industry", "IndustrySubsector" ]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["INDcode", "SScode", "LRcode", "JRcode", "BAcode", "BTcode","PMcode"], ascending=[True, True, True, True, True, True, True], ignore_index=True)
ppp_df_hashSort.head(40)

,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodePM,Industry,IndustrySubsector
0,3894287707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
1,3910757707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
2,4559867701,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
3,4533907702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
4,9925367708,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
5,4158237710,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
6,3321447710,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
7,2366557707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
8,3191927702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
9,3461597700,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
10,7521657706,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
11,4203327702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
12,4133777701,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
13,4119857705,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
14,4320877702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
15,4272147700,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
16,1526937709,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
17,3497247702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
18,4328877707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
19,4124397703,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
20,1861887704,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
21,3514637704,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
22,3248217703,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
23,3336527702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
24,4321407703,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
25,3535997706,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
26,3723007710,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
27,1100577700,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
28,4893777704,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
29,1496967705,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
30,4381387701,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
31,4194237707,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
32,1600597702,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
33,1719447700,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
34,9823957707,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
35,7348777702,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
36,9500297705,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
37,3185537108,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
38,4189217707,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
39,3013257710,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available

In [39]:
ppp_df_hashSort["INDSScode"].nunique()

313

In [40]:
ppp_df_hashSort["HASHcodePM"].nunique()

54996

In [41]:
print(ppp_df_hashSort["INDSScode"].nunique()) #313 
ppp_df_hashSort["INDSScode"].unique().tolist() 
print(ppp_df_hashSort.loc[ppp_df_hashSort["INDSScode"] =="IND11SS22"].count())

313
LoanNumber           303
INDSScode            303
INDcode              303
SScode               303
LRcode               303
JRcode               303
BTcode               303
BAcode               303
PMcode               303
HASHcodePM           303
Industry             303
IndustrySubsector    303
dtype: int64

In [42]:
print(ppp_df_hashSort.loc[ppp_df_hashSort["JRcode"] =="JR1"].count())

LoanNumber           5145
INDSScode            5145
INDcode              5145
SScode               5145
LRcode               5145
JRcode               5145
BTcode               5145
BAcode               5145
PMcode               5145
HASHcodePM           5145
Industry             5145
IndustrySubsector    5145
dtype: int64

Output for Sorted HASHcodes

cols= ["HASHcodebase", "LoanNumber"]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["HASHcodebase"], ascending=[True])
print(ppp_df_hashSort["HASHcodebase"].nunique())
ppp_df_hashSort.head(20)

In [43]:
ppp_df_hashSort.to_csv("../data/ppp_hashSort.csv")
read_hsh = pd.read_csv('../data/ppp_hashSort.csv')
read_hsh.head()

,Unnamed: 0,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodePM,Industry,IndustrySubsector
0,0,3894287707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
1,1,3910757707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
2,2,4559867701,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
3,3,4533907702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
4,4,9925367708,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available

In [44]:
read_hsh.dtypes

Unnamed: 0            int64
LoanNumber            int64
INDSScode            object
INDcode              object
SScode               object
LRcode               object
JRcode               object
BTcode               object
BAcode               object
PMcode               object
HASHcodePM           object
Industry             object
IndustrySubsector    object
dtype: object

cols= ["HASHcodePM", "LoanNumber"]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["HASHcodePM"], ascending=[True])
print(ppp_df_hashSort["HASHcodePM"].nunique())
ppp_df_hashSort.head(20)

In [43]:
#would need to combine loan factors and sort array
#. using haashcode sequence create layergroup for each unique combination
# if layer contains feature = INDcode add to industry group[1-21]
# if layer contains feature = SScode add to subsector group
# if layer contains feature = LRcode [1-5] add to LoanRange group[1-5]
# if layer contains feature = JRcode [1-9] add to JobsRange group[1-9]
# if layer contains feature = BTcode [1-26] add to BusinessType group[1-26]
# if layer contains feature = PMcode [1-2] add to ProcessingMethod group[1-2]