In [1]:
import pandas as pd 
import numpy as np

<b>PIPE

<b>MAIN PIPE file addition

In [2]:
ppp_pipe = pd.read_csv("../data/ppp_pipe.csv", index_col=0)
ppp_pipe.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDateTS,LoanStatus,Term,...,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,20201218.0,Paid in Full,24,...,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,Paint and Coating Manufacturing,"2410 Highway 15 South, Sumter, SC"
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,20210928.0,Paid in Full,24,...,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,Landscaping Services,"7684 Southrail Road, North Charleston, SC"
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,20210317.0,Paid in Full,24,...,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA"
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,20211016.0,Paid in Full,24,...,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,New Single-Family Housing Construction (except...,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,20210817.0,Paid in Full,24,...,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,Used Household and Office Goods Moving,"20101 Cornillie Dr, Roseville, MI"

In [3]:
#pd.set_option('display.max_rows', 250)
pd.reset_option('display.max_rows', silent=True) #disables display option
ppp_pipe_grp= ppp_pipe.groupby(["LoanStatusDateTS"]).agg({ "LoanNumber": 'count'})
ppp_pipe_grp

                  LoanNumber
LoanStatusDateTS
20200427.0                 1
20200429.0                 1
20200430.0                 2
20200515.0                 2
20200530.0                 1
...                      ...
20211116.0              3153
20211117.0              5379
20211118.0              6090
20211119.0              5832
20211120.0              6877

[423 rows x 1 columns]

Column Check

In [4]:
ppp_pipe.columns
print(len(ppp_pipe.columns))

43

In [5]:
#keep track of columns removed
dele = ['NA', '4DigitNAICS', 'NAICSCode', 'Industry', 'IndustrySubsector', 'TRIIndustrySector', 'Loan_Range', 'job_Range']
#Industry and Industry Subsector taken from HASH file (NAICS)
cols =['LoanNumber', 'DateApprovedTS', 'SBAOfficeCode', 'SBAOfficeLabel','ProcessingMethod', 'BorrowerName', 
       'BorrowerState', 'LoanStatusDateTS', 'LoanStatus', 'Term', 'CurrentApprovalAmount', 'UndisbursedAmount', 
       'FranchiseName','ServicingLenderLocationID', 'ServicingLenderName', 'ServicingLenderState','ServicingLenderFullAddress',
       'CD', 'JobsReported', 'OriginatingLenderLocationID', 'OriginatingLender', 'OriginatingLenderCity', 'OriginatingLenderState',
       'BusinessType', 'BusinessAgeDescription', 'NonProfit', 'ForgivenessAmount', 'ForgivenessDateTS', 'Estimated_LenderPercent', 'Estimated_LenderProfit', 
       'LongName', 'full_add']

ppp_pipe = ppp_pipe[cols]
ppp_pipe.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDateTS,LoanStatus,Term,...,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,LongName,full_add
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,20201218.0,Paid in Full,24,...,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120.0,3%,23080.76,Paint and Coating Manufacturing,"2410 Highway 15 South, Sumter, SC"
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,20210928.0,Paid in Full,24,...,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812.0,3%,22107.83,Landscaping Services,"7684 Southrail Road, North Charleston, SC"
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,20210317.0,Paid in Full,24,...,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210.0,3%,20740.65,Not Available,"1850 BOYER AVE E, SEATTLE, WA"
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,20211016.0,Paid in Full,24,...,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910.0,3%,14996.13,New Single-Family Housing Construction (except...,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,20210817.0,Paid in Full,24,...,OH,Not Available,Unanswered,N,370819.35,20210408.0,3%,11023.11,Used Household and Office Goods Moving,"20101 Cornillie Dr, Roseville, MI"

<b>HASH file addition

In [6]:
ppp_hash = pd.read_csv("../data/ppp_hashSort.csv") 
ppp_hash  = ppp_hash.loc[:, ~ppp_hash.columns.str.contains('^Unnamed')] 
ppp_hash

,LoanNumber,HASHcodePM,Industry,IndustrySubsector
0,3894287707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
1,3910757707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
2,4559867701,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
3,4533907702,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
4,9925367708,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
...,...,...,...,...
968552,3488997103,IND99SS99LR5JR6BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968553,5482257701,IND99SS99LR5JR7BT04BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968554,6699567107,IND99SS99LR5JR8BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968555,5359597703,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968556,5843777700,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments

<b>GEO, FIPS file addition

In [7]:
ppp_geo_fips=pd.read_csv("../data/state_data/geo/ppp_geo_fips.csv")
ppp_geo_fips=ppp_geo_fips.drop(["Unnamed: 0"], axis=1)
ppp_geo_fips

,LoanNumber,BorrowerState,full_add,Lat,Long,FIPS_z
0,5502308207,AK,"5015 BUSINESS PARK BLVD, ANCHORAGE, AK",61.174949,-149.888309,2.020002e+13
1,6110847106,AK,"7000 Uula St, BARROW, AK",71.297290,-156.728897,2.185000e+13
2,4539098204,AK,"4700 Old International Airport Rd, Anchorage, AK",61.173232,-149.972718,2.020002e+13
3,5120868804,AK,"540 W Intl Airport Rd, Anchorage, AK",61.173164,-149.893283,2.020003e+13
4,6650277102,AK,"4300 BARTLETT STREET, HOMER, AK",59.652704,-151.549793,2.122001e+13
...,...,...,...,...,...,...
968552,4395967002,WY,"102 N. Kenwood, CASPER, WY",42.850300,-106.304365,5.602500e+14
968553,6985647108,WY,"1715 HITCHING POST DR, GREEN RIVER, WY",41.499071,-109.464675,5.603797e+14
968554,7996438405,WY,"1105 Adon Rd, Rozet, WY",44.435381,-105.226008,5.600500e+14
968555,9054647103,WY,"30 N. Gould Street Suite 4000, SHERIDAN, WY",44.797763,-106.954952,5.603300e+14
968556,9184687004,WY,"7342 Granite Loop Rd, TETON VILLAGE, WY",43.587714,-110.822222,5.603997e+14

In [8]:
cols= ["LoanNumber", "Lat", "Long", "FIPS_z"]
ppp_geo_fips = ppp_geo_fips[cols]
ppp_geo_fips

        LoanNumber        Lat        Long        FIPS_z
0       5502308207  61.174949 -149.888309  2.020002e+13
1       6110847106  71.297290 -156.728897  2.185000e+13
2       4539098204  61.173232 -149.972718  2.020002e+13
3       5120868804  61.173164 -149.893283  2.020003e+13
4       6650277102  59.652704 -151.549793  2.122001e+13
...            ...        ...         ...           ...
968552  4395967002  42.850300 -106.304365  5.602500e+14
968553  6985647108  41.499071 -109.464675  5.603797e+14
968554  7996438405  44.435381 -105.226008  5.600500e+14
968555  9054647103  44.797763 -106.954952  5.603300e+14
968556  9184687004  43.587714 -110.822222  5.603997e+14

[968557 rows x 4 columns]

<b>Merged DataFrame

HASH > MAIN

In [9]:
#merge 
ppp_hash_pipe = ppp_hash.merge(ppp_pipe, on="LoanNumber", how="left")
ppp_hash_pipe

,LoanNumber,HASHcodePM,Industry,IndustrySubsector,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,...,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,LongName,full_add
0,3894287707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,912,SAN FRANCISCO DISTRICT OFFICE,PPP,PHD UROLOGY,CA,...,SD,Corporation,Existing or more than 2 years old,N,NaN,NaN,5%,12069.30,Not Available,"1240 S. ELISEO DRIVE SUITE 200, GREENBRAE, CA"
1,3910757707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,914,LOS ANGELES DISTRICT OFFICE,PPP,DIGITAL GRAPHIC SERVICE CENTER INC,CA,...,SD,Corporation,Existing or more than 2 years old,N,159125.94,20210611.0,5%,8790.00,Not Available,"35440 THOMAS ROAD, SANTA CLARITA, CA"
2,4559867701,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,954,SAN DIEGO DISTRICT OFFICE,PPP,ANDREW M BLUMENFELD MD APC,CA,...,SD,Corporation,Existing or more than 2 years old,N,NaN,NaN,5%,8383.35,Not Available,"336 OCEAN VIEW AVE, DEL MAR, CA"
3,4533907702,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,REVENUE MANAGEMENT CONSULTANTS,CA,...,SD,Corporation,Existing or more than 2 years old,N,161589.29,20210820.0,5%,7976.75,Not Available,"2040 SOUTH SANTA CRUZ STREET SUITE 240, ANAHEI..."
4,9925367708,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,"TVP GLOBAL SERVICES, INC.",CA,...,CA,Corporation,Existing or more than 2 years old,N,154087.67,20210521.0,5%,7625.00,Not Available,"1 YELLOWWOOD WAY, IRVINE, CA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968552,3488997103,IND99SS99LR5JR6BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200411,610,DALLAS / FT WORTH DISTRICT OFFICE,PPP,"ASTROCHEF, LLC",TX,...,CA,Limited Liability Company(LLC),Existing or more than 2 years old,N,NaN,NaN,1%,55527.49,Not Available,"1635 Innovation Dr, ROCKWALL, TX"
968553,5482257701,IND99SS99LR5JR7BT04BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,UW PHYSICIANS NETWORK,WA,...,NC,Non-Profit Organization,New Business or 2 years or less,Y,5366395.05,20210920.0,1%,52934.47,Not Available,"1100 NE 45th St Ste 500, Seattle, WA"
968554,6699567107,IND99SS99LR5JR8BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200414,455,SOUTH FLORIDA DISTRICT OFFICE,PPP,"PHASE THREE STAR, LLC DBA HARDEE'S",FL,...,MS,Limited Liability Company(LLC),Existing or more than 2 years old,N,6362785.00,20210623.0,1%,62920.00,Not Available,"4029 HENDERSON BLVD, TAMPA, FL"
968555,5359597703,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200501,455,SOUTH FLORIDA DISTRICT OFFICE,PPP,KNA SOLUTIONS LLC,FL,...,NC,Limited Liability Company(LLC),New Business or 2 years or less,N,NaN,NaN,1%,84989.77,Not Available,"11031 WATERCREST CIR W, PARKLAND, FL"
968556,5843777700,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200501,944,NEVADA DISTRICT OFFICE,PPP,SILVER STATE BELL LLC,NV,...,NC,Limited Liability Company(LLC),New Business or 2 years or less,N,6600200.69,20210618.0,1%,65268.85,Not Available,"3225A S Rainbow Blvd Ste 102, Las Vegas, NV"

HASH PIPE > RESULT (FIPS, GEO)

In [10]:
ppp_hpgf = ppp_hash_pipe.merge(ppp_geo_fips, on="LoanNumber", how="left")
ppp_hpgf

,LoanNumber,HASHcodePM,Industry,IndustrySubsector,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,...,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,LongName,full_add,Lat,Long,FIPS_z
0,3894287707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,912,SAN FRANCISCO DISTRICT OFFICE,PPP,PHD UROLOGY,CA,...,N,NaN,NaN,5%,12069.30,Not Available,"1240 S. ELISEO DRIVE SUITE 200, GREENBRAE, CA",37.944510,-122.535984,6.041119e+13
1,3910757707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,914,LOS ANGELES DISTRICT OFFICE,PPP,DIGITAL GRAPHIC SERVICE CENTER INC,CA,...,N,159125.94,20210611.0,5%,8790.00,Not Available,"35440 THOMAS ROAD, SANTA CLARITA, CA",34.521182,-118.259663,6.037911e+13
2,4559867701,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,954,SAN DIEGO DISTRICT OFFICE,PPP,ANDREW M BLUMENFELD MD APC,CA,...,N,NaN,NaN,5%,8383.35,Not Available,"336 OCEAN VIEW AVE, DEL MAR, CA",32.942704,-117.260217,6.073017e+13
3,4533907702,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,REVENUE MANAGEMENT CONSULTANTS,CA,...,N,161589.29,20210820.0,5%,7976.75,Not Available,"2040 SOUTH SANTA CRUZ STREET SUITE 240, ANAHEI...",33.797606,-117.894151,6.059086e+13
4,9925367708,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,"TVP GLOBAL SERVICES, INC.",CA,...,N,154087.67,20210521.0,5%,7625.00,Not Available,"1 YELLOWWOOD WAY, IRVINE, CA",33.658618,-117.822648,6.059063e+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968552,3488997103,IND99SS99LR5JR6BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200411,610,DALLAS / FT WORTH DISTRICT OFFICE,PPP,"ASTROCHEF, LLC",TX,...,N,NaN,NaN,1%,55527.49,Not Available,"1635 Innovation Dr, ROCKWALL, TX",32.912807,-96.425452,4.839704e+14
968553,5482257701,IND99SS99LR5JR7BT04BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,UW PHYSICIANS NETWORK,WA,...,Y,5366395.05,20210920.0,1%,52934.47,Not Available,"1100 NE 45th St Ste 500, Seattle, WA",47.661514,-122.316252,5.303301e+14
968554,6699567107,IND99SS99LR5JR8BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200414,455,SOUTH FLORIDA DISTRICT OFFICE,PPP,"PHASE THREE STAR, LLC DBA HARDEE'S",FL,...,N,6362785.00,20210623.0,1%,62920.00,Not Available,"4029 HENDERSON BLVD, TAMPA, FL",27.929549,-82.511182,1.205701e+14
968555,5359597703,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200501,455,SOUTH FLORIDA DISTRICT OFFICE,PPP,KNA SOLUTIONS LLC,FL,...,N,NaN,NaN,1%,84989.77,Not Available,"11031 WATERCREST CIR W, PARKLAND, FL",26.335189,-80.276842,1.201101e+14
968556,5843777700,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments,20200501,944,NEVADA DISTRICT OFFICE,PPP,SILVER STATE BELL LLC,NV,...,N,6600200.69,20210618.0,1%,65268.85,Not Available,"3225A S Rainbow Blvd Ste 102, Las Vegas, NV",36.130811,-115.243396,3.200300e+14

<b>Null Check

In [11]:
pd.set_option('display.max_rows', 70)
print(ppp_hpgf.isnull().sum())

LoanNumber                          0
HASHcodePM                          0
Industry                            0
IndustrySubsector                   0
DateApprovedTS                      0
SBAOfficeCode                       0
SBAOfficeLabel                      0
ProcessingMethod                    0
BorrowerName                        4
BorrowerState                       0
LoanStatusDateTS               281932
LoanStatus                          0
Term                                0
CurrentApprovalAmount               0
UndisbursedAmount                 219
FranchiseName                  933151
ServicingLenderLocationID           0
ServicingLenderName                 0
ServicingLenderState                0
ServicingLenderFullAddress          0
CD                                 46
JobsReported                        0
OriginatingLenderLocationID         0
OriginatingLender                   0
OriginatingLenderCity               0
OriginatingLenderState              0
BusinessType                        0
BusinessAgeDescription              0
NonProfit                           0
ForgivenessAmount              207884
ForgivenessDateTS              207884
Estimated_LenderPercent             0
Estimated_LenderProfit              0
LongName                            0
full_add                            6
Lat                               145
Long                              145
FIPS_z                            926
dtype: int64

In [12]:
pd.reset_option('display.max_rows', silent=True)

<b>Output for Labeled, Hashed, Geocoded, FIPS file

In [13]:
ppp_hpgf.to_csv("../data/pipe_hpgf.csv")

In [14]:
pd.set_option('display.max_rows', 60)
ppp_geonull = ppp_hpgf.loc[ppp_hpgf["Lat"].isnull()]
ppp_geonull["BorrowerState"].value_counts()

BorrowerState
IN    28
MI    14
FL    13
NC    11
AL     8
PA     8
TX     6
OR     6
AK     5
WA     4
NM     4
TN     3
NJ     3
CO     3
MA     3
WI     2
ID     2
PR     2
ME     2
NY     2
IL     2
AR     2
IA     1
MN     1
NE     1
MS     1
VI     1
OH     1
CT     1
HI     1
WV     1
GA     1
SC     1
CA     1
Name: count, dtype: int64

<B>Parsing by State Output for Labeled, Hashed, Geocoded, FIPS file

Removed State Hashed Files 07/19

In [15]:
#compute file for each state
ak_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "AK", :]
al_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "AL", :]
ar_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "AR", :]
as_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "AS", :] #American Samoa
az_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "AZ", :]

ca_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "CA", :]
co_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "CO", :]
ct_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "CT", :]
dc_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "DC", :] #D.C.
de_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "DE", :]

fl_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "FL", :]
ga_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "GA", :]
gu_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "GU", :] #Guam
hi_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "HI", :]
ia_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "IA", :]

id_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "ID", :]
il_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "IL", :]
in_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "IN", :]
ks_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "KS", :]
ky_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "KY", :]
la_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "LA", :]
ma_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MA", :]
md_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MD", :]
me_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "ME", :]
mi_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MI", :]
mn_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MN", :]
mo_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MO", :]
mp_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MP", :] #Saipan Member of Parliament
ms_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MS", :]
mt_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "MT", :]
nc_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NC", :]
nd_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "ND", :]
ne_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NE", :]
nh_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NH", :]
nj_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NJ", :]
nm_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NM", :]
nv_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NV", :]
ny_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "NY", :]
oh_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "OH", :]
ok_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "OK", :]
or_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "OR", :]
pa_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "PA", :]
pr_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "PR", :] #Puerto Rico
ri_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "RI", :]
sc_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "SC", :]
sd_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "SD", :]
tn_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "TN", :]
tx_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "TX", :]
ut_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "UT", :]
va_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "VA", :]
vi_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "VI", :] #Virgin Islands
vt_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "VT", :]
wa_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "WA", :]
wi_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "WI", :]
wv_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "WV", :]
wy_hpgf = ppp_hpgf.loc[ppp_hpgf["BorrowerState"] == "WY", :]

FIPS states

All States 2021

In [16]:
#PointPair each state file separately in aggregation notebook
ak_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ak.csv") 
al_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_al.csv")
ar_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ar.csv") 
as_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_as.csv")
az_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_az.csv")  
ca_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ca.csv")  
co_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_co.csv") 
ct_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ct.csv")  
dc_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_dc.csv")
de_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_de.csv") 
fl_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_fl.csv") 
ga_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ga.csv") 
gu_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_gu.csv")
hi_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_hi.csv") 
ia_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ia.csv")  
id_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_id.csv")  
il_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_il.csv")  
in_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_in.csv") 
ks_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ks.csv")  
ky_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ky.csv")  
la_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_la.csv")
ma_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ma.csv") 
md_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_md.csv")
me_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_me.csv")  
mi_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_mi.csv") 
mn_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_mn.csv") 
mo_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_mo.csv")  
mp_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_mp.csv") 
ms_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ms.csv")
mt_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_mt.csv")
nc_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_nc.csv") 
nd_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_nd.csv")  
ne_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ne.csv")
nh_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_nh.csv")  
nj_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_nj.csv")
nm_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_nm.csv") 
nv_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_nv.csv")  
ny_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ny.csv")  
oh_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_oh.csv")
ok_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ok.csv") 
or_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_or.csv")  
pa_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_pa.csv")
pr_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_pr.csv")  
ri_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ri.csv") 
sc_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_sc.csv") 
sd_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_sd.csv") 
tn_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_tn.csv")  
tx_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_tx.csv")  
ut_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_ut.csv")  
va_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_va.csv")  
vi_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_vi.csv")  
vt_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_vt.csv")
wa_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_wa.csv")  
wi_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_wi.csv")  
wv_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_wv.csv") 
wy_hpgf.to_csv("../data/state_data/hash_states/21/hpgf_wy.csv")

KeyboardInterrupt: