In [1]:
import pandas as pd
import numpy as np

In [2]:
ppp_df = pd.read_csv("../data/ppp_pipe.csv")
ppp_df

,Unnamed: 0,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,...,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add
0,0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,...,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC"
1,1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,...,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC"
2,2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,...,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA"
3,3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,...,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,...,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968552,968552,4395967002,20200403,897,WYOMING DISTRICT OFFICE,PPP,"ROY E PAULSON, JR., P.C.",WY,1/13/21,Paid in Full,...,62,6212,621210,Health Care and Social Assistance,6212 Offices of Dentists,999 Other,"a $150,000-350,000",10 to 19,6212 Offices of Dentists,"102 N. Kenwood, CASPER, WY"
968553,968553,6985647108,20200414,897,WYOMING DISTRICT OFFICE,PPP,"SWEETWATER COUNTY CHILD DEVELOPMENTAL CENTER, ...",WY,12/8/20,Paid in Full,...,62,6244,624410,Health Care and Social Assistance,6244 Child Day Care Services,999 Other,"a $150,000-350,000",20 to 49,6244 Child Day Care Services,"1715 HITCHING POST DR, GREEN RIVER, WY"
968554,968554,7996438405,20210212,897,WYOMING DISTRICT OFFICE,PPS,ELECTRICAL SYSTEMS OF WYOMING INC,WY,9/15/21,Paid in Full,...,23,2382,238210,Construction,2382 Building Equipment Contractors,999 Other,"a $150,000-350,000",Fewer than 5,2382 Building Equipment Contractors,"1105 Adon Rd, Rozet, WY"
968555,968555,9054647103,20200415,897,WYOMING DISTRICT OFFICE,PPP,EDEN LIFE CARE,WY,NaN,Exemption 4,...,62,6216,621610,Health Care and Social Assistance,6216 Home Health Care Services,999 Other,"a $150,000-350,000",5 to 9,6216 Home Health Care Services,"30 N. Gould Street Suite 4000, SHERIDAN, WY"
968556,968556,9184687004,20200409,897,WYOMING DISTRICT OFFICE,PPP,S & S JOHNSON ENTERPRISES INC,WY,10/22/21,Paid in Full,...,72,7225,722511,Accommodation and Food Services,7225 Restaurants and Other Eating Places,999 Other,"a $150,000-350,000",10 to 19,7225 Restaurants and Other Eating Places,"7342 Granite Loop Rd, TETON VILLAGE, WY"

In [3]:
ppp_df["NAICSCode"].dtype

dtype('int64')

<h3>Industry Sector Review

In [4]:
#pd.set_option('display.max_rows', None)
ppp_df_industry = ppp_df.groupby(["Industry", "IndustrySubsector"]).agg({ "LoanNumber": 'count'})
ppp_df_industry #312

                                                                                    LoanNumber
Industry                        IndustrySubsector
Accommodation and Food Services 7211 Traveler Accommodation                              20906
                                7212 RV (Recreational Vehicle) Parks and Recrea...        1158
                                7213 Rooming and Boarding Houses, Dormitories, ...         120
                                7223 Special Food Services                                4393
                                7224 Drinking Places (Alcoholic Beverages)                4002
...                                                                                        ...
Wholesale Trade                 4246 Chemical and Allied Products Merchant Whol...         955
                                4247 Petroleum and Petroleum Products Merchant ...        1490
                                4248 Beer, Wine, and Distilled Alcoholic Bevera...        1114
                                4249 Miscellaneous Nondurable Goods Merchant Wh...        3587
                                4251 Wholesale Electronic Markets and Agents an...        1281

[314 rows x 1 columns]

In [5]:
ppp_df_industry = ppp_df.groupby(["Industry", "IndustrySubsector", "Loan_Range", "BusinessType"]).agg({ "LoanNumber": 'count'})
ppp_df_industry  #9801

                                                                                                                                           LoanNumber
Industry                        IndustrySubsector                                  Loan_Range         BusinessType
Accommodation and Food Services 7211 Traveler Accommodation                        a $150,000-350,000 501(c)6 – Non Profit Membership               1
                                                                                                      Cooperative                                   4
                                                                                                      Corporation                                2601
                                                                                                      Employee Stock Ownership Plan(ESOP)           1
                                                                                                      Independent Contractors                       1
...                                                                                                                                               ...
Wholesale Trade                 4251 Wholesale Electronic Markets and Agents an... d $2-5 million     Corporation                                   5
                                                                                                      Limited Liability Company(LLC)                1
                                                                                                      Subchapter S Corporation                      5
                                                                                   e $5-10 million    Employee Stock Ownership Plan(ESOP)           1
                                                                                                      Limited Liability Company(LLC)                2

[9887 rows x 1 columns]

In [6]:
ppp_df["IndustrySubsector"].nunique()

314

In [7]:
ppp_df.loc[ppp_df["4DigitNAICS"] == "6115", "IndustrySubsector"] = "6115 Technical and Trade Schools"
edu_ppp = ppp_df.loc[ppp_df["Industry"] == "Educational Services"]
edu_ppp.groupby(["Industry", "IndustrySubsector"]).agg({"LoanNumber": "count"})

                                                                         LoanNumber
Industry             IndustrySubsector
Educational Services 6111 Elementary and Secondary Schools                    10032
                     6112 Junior Colleges                                       101
                     6113 Colleges, Universities, and Professional S...        1370
                     6114 Business Schools and Computer and Manageme...         873
                     6115 Technical and Trade Schools                          1013
                     6115 Technical and Trade Schools                           113
                     6116 Other Schools and Instruction                        3742
                     6117 Educational Support Services                         2781

In [8]:
#ppp_df.loc[ppp_df["4DigitNAICS"] == "6115", "IndustrySubsector"] = "6115 Technical and Trade Schools"
manppp = ppp_df.loc[ppp_df["Industry"] == "Utilities"]
manppp["IndustrySubsector"].sort_values().unique().tolist()

['2211 Electric Power Generation, Transmission and Distribution',
 '2212 Natural Gas Distribution ',
 '2213 Water, Sewage and Other Systems ']

<b>Industries - 26

In [9]:
indss_df_na =  ppp_df.groupby(["IndustrySubsector",  "4DigitNAICS"], as_index=False).agg({ "LoanNumber": 'count'}) #327
indss_df_na.head()

                                   IndustrySubsector  4DigitNAICS  LoanNumber
0                     1111 Oilseed and Grain Farming         1111         783
1                   1112 Vegetable and Melon Farming         1112         900
2                    1113 Fruit and Tree Nut Farming         1113        1630
3  1114 Greenhouse, Nursery, and Floriculture Pro...         1114        1230
4                            1119 Other Crop Farming         1119        1329

<b>Industry, Subsector - 328, accounts for Subsector = 0

In [10]:
#pd.set_option('display.max_rows', None)
indss_df = ppp_df.groupby(["Industry", "NA", "4DigitNAICS"]).agg({ "LoanNumber": 'count'}) #327
indss_df

                                                LoanNumber
Industry                        NA 4DigitNAICS
Accommodation and Food Services 72 7211              20906
                                   7212               1158
                                   7213                120
                                   7223               4393
                                   7224               4002
...                                                    ...
Wholesale Trade                 42 4246                955
                                   4247               1490
                                   4248               1114
                                   4249               3587
                                   4251               1281

[313 rows x 1 columns]

In [11]:
indss_df =  ppp_df.groupby(["Industry", "NA", "IndustrySubsector", "4DigitNAICS"]).agg({ "LoanNumber": 'count'}) #327
print(indss_df.shape[0])
indss_df

314

                                                                                                   LoanNumber
Industry                        NA IndustrySubsector                                  4DigitNAICS
Accommodation and Food Services 72 7211 Traveler Accommodation                        7211              20906
                                   7212 RV (Recreational Vehicle) Parks and Recrea... 7212               1158
                                   7213 Rooming and Boarding Houses, Dormitories, ... 7213                120
                                   7223 Special Food Services                         7223               4393
                                   7224 Drinking Places (Alcoholic Beverages)         7224               4002
...                                                                                                       ...
Wholesale Trade                 42 4246 Chemical and Allied Products Merchant Whol... 4246                955
                                   4247 Petroleum and Petroleum Products Merchant ... 4247               1490
                                   4248 Beer, Wine, and Distilled Alcoholic Bevera... 4248               1114
                                   4249 Miscellaneous Nondurable Goods Merchant Wh... 4249               3587
                                   4251 Wholesale Electronic Markets and Agents an... 4251               1281

[314 rows x 1 columns]

In [12]:
ppp_df['BusinessType'].value_counts()

Corporation                            415963
Limited Liability Company(LLC)         261542
Subchapter S Corporation               177322
Non-Profit Organization                 54932
Partnership                             18086
Limited Liability Partnership           12737
Sole Proprietorship                     12429
Professional Association                 6780
Cooperative                              2449
501(c)3 – Non Profit                     1790
Non-Profit Childcare Center               909
501(c)6 – Non Profit Membership           765
Not Available                             728
Employee Stock Ownership Plan(ESOP)       636
Self-Employed Individuals                 497
Trust                                     408
Housing Co-op                             152
Joint Venture                             129
Independent Contractors                   116
Single Member LLC                          76
Tribal Concerns                            63
Tenant in Common                           31
501(c) – Non Profit except 3,4,6,          10
Rollover as Business Start-Ups (ROB         3
501(c)19 – Non Profit Veterans              2
Qualified Joint-Venture (spouses)           2
Name: BusinessType, dtype: int64

<h3>Hashing Code Values

In [13]:
pd.set_option('display.max_columns', None)
ppp_df_hash = ppp_df
ppp_df_hash = ppp_df_hash.drop(["Unnamed: 0"], axis=1)
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC"
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC"
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA"
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI"

Industry Conditions

In [14]:
ppp_df_hash["NA"]=ppp_df_hash["NA"].apply(str)
ppp_df_hash["4DigitNAICS"]=ppp_df_hash["4DigitNAICS"].apply(str)

In [15]:
ppp_df_hash["INDcode"] = 'IND' + ppp_df_hash["NA"]
ppp_df_hash["SScode"] = 'SS' + ppp_df_hash["4DigitNAICS"].str[-2:]
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42

Loan Conditions

In [16]:
loan_conditions = [
(ppp_df_hash.Loan_Range == "a $150,000-350,000" ),
(ppp_df_hash.Loan_Range == "b $350,000-1 million" ),
(ppp_df_hash.Loan_Range == "c $1-2 million" ),
(ppp_df_hash.Loan_Range == "d $2-5 million" ),
(ppp_df_hash.Loan_Range == "e $5-10 million" ),
]
loan_values = ["LR1","LR2","LR3","LR4","LR5"]
ppp_df_hash['LRcode'] = np.select(loan_conditions, loan_values)
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2

Job Range Conditions

In [17]:
jobrange_conditions = [
    (ppp_df_hash.job_Range == 'Fewer than 5'),
    (ppp_df_hash.job_Range == '5 to 9'),
    (ppp_df_hash.job_Range == '10 to 19'),
    (ppp_df_hash.job_Range == '20 to 49'),
    (ppp_df_hash.job_Range == '50 to 99'),
    (ppp_df_hash.job_Range == '100 to 249'),
    (ppp_df_hash.job_Range == '250 to 499'),
    (ppp_df_hash.job_Range == '500 or more'),
]

jobrange_values = ['JR1', 'JR2', 'JR3', 'JR4', 'JR5',
       'JR6', 'JR7', 'JR8']

ppp_df_hash['JRcode'] = np.select(jobrange_conditions , jobrange_values)
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode,JRcode
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4

In [18]:
ppp_df_hash['JRcode'].value_counts()

JR4    417145
JR3    242131
JR5    161529
JR6     84789
JR2     31387
JR7     22073
JR1      5145
JR8      4358
Name: JRcode, dtype: int64

Business Type Conditions

In [19]:
businesstype_conditions = [
    (ppp_df_hash.BusinessType == "Corporation"),
    (ppp_df_hash.BusinessType == "Limited Liability Company(LLC)"),
    (ppp_df_hash.BusinessType == "Subchapter S Corporation"),
    (ppp_df_hash.BusinessType == "Non-Profit Organization"),
    (ppp_df_hash.BusinessType == "Partnership"),
    (ppp_df_hash.BusinessType == "Limited Liability Partnership"),
    (ppp_df_hash.BusinessType == "Sole Proprietorship"),
    (ppp_df_hash.BusinessType == "Professional Association"),
    (ppp_df_hash.BusinessType == "Cooperative"),
    (ppp_df_hash.BusinessType == "501(c)3 – Non Profit"),
    (ppp_df_hash.BusinessType == "Non-Profit Childcare Center"),
    (ppp_df_hash.BusinessType == "501(c)6 – Non Profit Membership"),
    (ppp_df_hash.BusinessType == "Not Available"),
    (ppp_df_hash.BusinessType == "Employee Stock Ownership Plan(ESOP)"),
    (ppp_df_hash.BusinessType == "Self-Employed Individuals"),
    (ppp_df_hash.BusinessType == "Trust"),
    (ppp_df_hash.BusinessType == "Housing Co-op"),
    (ppp_df_hash.BusinessType == "Joint Venture"),
    (ppp_df_hash.BusinessType == "Independent Contractors"),
    (ppp_df_hash.BusinessType == "Single Member LLC"),
    (ppp_df_hash.BusinessType == "Tribal Concerns"),
    (ppp_df_hash.BusinessType == "Tenant in Common"),
    (ppp_df_hash.BusinessType == "501(c) – Non Profit except 3,4,6,"),
    (ppp_df_hash.BusinessType == "Rollover as Business Start-Ups (ROB"),
    (ppp_df_hash.BusinessType == "501(c)19 – Non Profit Veterans"),
    (ppp_df_hash.BusinessType == "Qualified Joint-Venture (spouses)"),
    
    
]

businesstype_values = ["BT01", "BT02", "BT03", "BT04", "BT05", 
                       "BT06", "BT07", "BT08", "BT09", "BT10", 
                       "BT11", "BT12", "BT13", "BT14", "BT15", 
                       "BT16", "BT17", "BT18", "BT19", "BT20", 
                       "BT21", "BT22", "BT23", "BT24", "BT25",
                       "BT26"]
ppp_df_hash['BTcode'] = np.select(businesstype_conditions, businesstype_values)
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode,JRcode,BTcode
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13

In [20]:
ppp_df_hash['BTcode'].value_counts()

BT01    415963
BT02    261542
BT03    177322
BT04     54932
BT05     18086
BT06     12737
BT07     12429
BT08      6780
BT09      2449
BT10      1790
BT11       909
BT12       765
BT13       728
BT14       636
BT15       497
BT16       408
BT17       152
BT18       129
BT19       116
BT20        76
BT21        63
BT22        31
BT23        10
BT24         3
BT25         2
BT26         2
Name: BTcode, dtype: int64

Business Age Conditions

In [21]:
businessage_conditions = [
    (ppp_df_hash.BusinessAgeDescription == 'Existing or more than 2 years old'),
    (ppp_df_hash.BusinessAgeDescription == 'New Business or 2 years or less'),
    (ppp_df_hash.BusinessAgeDescription == 'Unanswered'),
    (ppp_df_hash.BusinessAgeDescription == 'Change of Ownership'),
    (ppp_df_hash.BusinessAgeDescription == 'Startup, Loan Funds will Open Business'),
]
businessage_values = ["BA1", "BA2", "BA3", "BA4", "BA5"]
ppp_df_hash['BAcode'] = np.select(businessage_conditions, businessage_values)
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3

In [22]:
ppp_df_hash['BAcode'].value_counts()

BA1    861935
BA2     54854
BA3     51056
BA4       422
BA5       290
Name: BAcode, dtype: int64

<b>Alt Process Codes

In [23]:
ppp_df_hash["PMcode"] = ppp_df_hash["ProcessingMethod"] # PPP/PPS
ppp_df_hash["NPcode"] = 'NP' + ppp_df_hash["NonProfit"] # Y/N
ppp_df_hash["LMIcode"] = 'LMI' +ppp_df_hash["LMIIndicator"] #Y/N
ppp_df_hash["HZcode"] = 'HZ' + ppp_df_hash["HubzoneIndicator"] #Y/N
ppp_df_hash["RUcode"] = ppp_df_hash["RuralUrbanIndicator"] #U/R
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1,PPP,NPN,LMIN,HZN,U
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1,PPP,NPN,LMIY,HZY,U
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2,PPP,NPY,LMIN,HZN,U
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2,PPP,NPN,LMIN,HZN,U
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3,PPP,NPN,LMIN,HZN,U

In [24]:
md_groups = ppp_df_hash.loc[ppp_df_hash["BorrowerState"] == "MD"]
md_groups.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode
425853,4142717108,20200412,373,BALTIMORE DISTRICT OFFICE,PPP,"PT NETWORK, LLC",MD,7/15/21,Paid in Full,24,10000000.0,0.0,NaN,455644,Live Oak Banking Company,U,N,Y,MD-02,500.0,455644,Live Oak Banking Company,WILMINGTON,NC,Limited Liability Company(LLC),Existing or more than 2 years old,N,10114520.55,20210611,1%,100000.0,62,6213,621340,Health Care and Social Assistance,6213 Offices of Other Health Practitioners,999 Other,e $5-10 million,500 or more,6213 Offices of Other Health Practitioners,"501 Fairmount Ave, Towson, MD",IND62,SS13,LR5,JR8,BT02,BA1,PPP,NPN,LMIY,HZN,U
425854,4682157009,20200404,373,BALTIMORE DISTRICT OFFICE,PPP,"GMS MINE REPAIR AND MAINTENANCE, INC.",MD,7/17/21,Paid in Full,24,10000000.0,0.0,NaN,30767,First United Bank & Trust,R,N,N,MD-06,500.0,30767,First United Bank & Trust,OAKLAND,MD,Corporation,Existing or more than 2 years old,N,10118611.11,20210615,1%,100000.0,21,2121,212112,"Mining, Quarrying, and Oil and Gas Extraction",2121 Coal Mining,2121 Coal Mining,e $5-10 million,500 or more,2121 Coal Mining,"PO Box 2446 32 Enterprise Drive, OAKLAND, MD",IND21,SS21,LR5,JR8,BT01,BA1,PPP,NPN,LMIN,HZN,R
425855,8298497108,20200415,373,BALTIMORE DISTRICT OFFICE,PPP,"GSE SYSTEMS, INC.",MD,9/29/21,Paid in Full,24,10000000.0,0.0,NaN,434162,"Citizens Bank, National Association",R,N,N,MD-08,380.0,434162,"Citizens Bank, National Association",PROVIDENCE,RI,Corporation,Existing or more than 2 years old,N,10126849.32,20210802,1%,100000.0,33,3333,333318,Manufacturing,3333 Commercial and Service Industry Machinery...,333 Machinery,e $5-10 million,250 to 499,3333 Commercial and Service Industry Machinery...,"1332 Londontown Blvd 200, Sykesville, MD",IND33,SS33,LR5,JR7,BT01,BA1,PPP,NPN,LMIN,HZN,R
425856,8415647105,20200415,373,BALTIMORE DISTRICT OFFICE,PPP,"MISSION BBQ MANAGEMENT, LLC",MD,7/8/21,Paid in Full,24,10000000.0,0.0,NaN,46391,Manufacturers and Traders Trust Company,U,N,N,MD-03,500.0,46391,Manufacturers and Traders Trust Company,BUFFALO,NY,Limited Liability Company(LLC),Existing or more than 2 years old,N,10113698.63,20210611,1%,100000.0,72,7225,722511,Accommodation and Food Services,7225 Restaurants and Other Eating Places,999 Other,e $5-10 million,500 or more,7225 Restaurants and Other Eating Places,"7750 Governor Ritchie Highway, Glen Burnie, MD",IND72,SS25,LR5,JR8,BT02,BA1,PPP,NPN,LMIN,HZN,U
425857,9405257009,20200409,373,BALTIMORE DISTRICT OFFICE,PPP,LEMEK LLC,MD,NaN,Exemption 4,24,10000000.0,0.0,Panera Bread,30872,Sandy Spring Bank,U,N,N,MD-03,500.0,30872,Sandy Spring Bank,OLNEY,MD,Subchapter S Corporation,Existing or more than 2 years old,N,NaN,NaT,1%,100000.0,72,7225,722513,Accommodation and Food Services,7225 Restaurants and Other Eating Places,999 Other,e $5-10 million,500 or more,7225 Restaurants and Other Eating Places,"8184 Lark Brown Road Suite 201, ELKRIDGE, MD",IND72,SS25,LR5,JR8,BT03,BA1,PPP,NPN,LMIN,HZN,U

<b>Null Check before Creating Hashcodes

In [33]:
print(ppp_df_hash.isnull().sum())

LoanNumber                          0
DateApprovedTS                      0
SBAOfficeCode                       0
SBAOfficeLabel                      0
ProcessingMethod                    0
BorrowerName                        4
BorrowerState                       0
LoanStatusDate                 281932
LoanStatus                          0
Term                                0
CurrentApprovalAmount               0
UndisbursedAmount                 219
FranchiseName                  933151
ServicingLenderLocationID           0
ServicingLenderName                 0
RuralUrbanIndicator                 0
HubzoneIndicator                    0
LMIIndicator                        0
CD                                 46
JobsReported                        1
OriginatingLenderLocationID         0
OriginatingLender                   0
OriginatingLenderCity               0
OriginatingLenderState              0
BusinessType                        0
BusinessAgeDescription              0
NonProfit                           0
ForgivenessAmount              207884
ForgivenessDateTS                   0
Estimated_LenderPercent             0
Estimated_LenderProfit              0
NA                                  0
4DigitNAICS                         0
NAICSCode                           0
Industry                            0
IndustrySubsector                   0
TRIIndustrySector               12182
Loan_Range                          0
job_Range                           0
LongName                            0
full_add                            6
INDcode                             0
SScode                              0
LRcode                              0
JRcode                              0
BTcode                              0
BAcode                              0
PMcode                              0
NPcode                              0
LMIcode                             0
HZcode                              0
RUcode                              0
INDSScode                           0
HASHcodePM                          0
dtype: int64

Creating HASHcodes

In [25]:
### Industry, Subsector
ppp_df_hash["INDSScode"] = ppp_df_hash["INDcode"]  + ppp_df_hash["SScode"]

# Loan Range, Business Type, JobRange, Industry, Subsector, ProcessingMethod
ppp_df_hash["HASHcodePM"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] + ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash['BAcode'] + ppp_df_hash["PMcode"]
# Loan Range, Business Type, JobRange, Industry, Subsector, ProcessingMethod, Nonprofit, LMI, Hubzone, RuralUrban
#ppp_df_hash["HASHcodefull"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] + ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash["PMcode"] + ppp_df_hash["NPcode"] + ppp_df_hash["LMIcode"] + ppp_df_hash["HZcode"]  + ppp_df_hash["RUcode"]
#ppp_df_hash["HASHcodePMr"] = ppp_df_hash["PMcode"] + ppp_df_hash['LRcode'] + ppp_df_hash['BAcode'] + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash["INDcode"] + ppp_df_hash["SScode"]  
ppp_df_hash.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,SBAOfficeLabel,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDate,LoanStatus,Term,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,CD,JobsReported,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,BusinessType,BusinessAgeDescription,NonProfit,ForgivenessAmount,ForgivenessDateTS,Estimated_LenderPercent,Estimated_LenderProfit,NA,4DigitNAICS,NAICSCode,Industry,IndustrySubsector,TRIIndustrySector,Loan_Range,job_Range,LongName,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodePM
0,9547507704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"SUMTER COATINGS, INC.",SC,12/18/20,Paid in Full,24,769358.78,0.0,NaN,19248,Synovus Bank,U,N,N,SC-05,62.0,19248,Synovus Bank,COLUMBUS,GA,Corporation,Existing or more than 2 years old,N,773553.37,20201120,3%,23080.76,32,3255,325510,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",325 Chemicals,"b $350,000-1 million",50 to 99,"3255 Paint, Coating, and Adhesive Manufacturing","2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1,PPP,NPN,LMIN,HZN,U,IND32SS55,IND32SS55LR2JR5BT01BA1PPP
1,9777677704,20200501,464,SOUTH CAROLINA DISTRICT OFFICE,PPP,"PLEASANT PLACES, INC.",SC,9/28/21,Paid in Full,24,736927.79,0.0,NaN,19248,Synovus Bank,U,Y,Y,SC-06,73.0,19248,Synovus Bank,COLUMBUS,GA,Sole Proprietorship,Existing or more than 2 years old,N,746336.24,20210812,3%,22107.83,56,5617,561730,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,999 Other,"b $350,000-1 million",50 to 99,5617 Services to Buildings and Dwellings,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1,PPP,NPN,LMIY,HZY,U,IND56SS17,IND56SS17LR2JR5BT07BA1PPP
2,5791407702,20200501,1013,SEATTLE DISTRICT OFFICE,PPP,BOYER CHILDREN'S CLINIC,WA,3/17/21,Paid in Full,24,691355.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,WA-07,75.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Non-Profit Organization,New Business or 2 years or less,Y,696677.49,20210210,3%,20740.65,0,0,0,Not Available,Not Available,NaN,"b $350,000-1 million",50 to 99,Not Available,"1850 BOYER AVE E, SEATTLE, WA",IND0,SS0,LR2,JR5,BT04,BA2,PPP,NPY,LMIN,HZN,U,IND0SS0,IND0SS0LR2JR5BT04BA2PPP
3,6223567700,20200501,920,SANTA ANA DISTRICT OFFICE,PPP,KIRTLEY CONSTRUCTION INC,CA,10/16/21,Paid in Full,24,499871.00,0.0,NaN,9551,"Bank of America, National Association",U,N,N,CA-08,21.0,9551,"Bank of America, National Association",CHARLOTTE,NC,Corporation,New Business or 2 years or less,N,395264.11,20210910,3%,14996.13,23,2361,236115,Construction,2361 Residential Building Construction,999 Other,"b $350,000-1 million",20 to 49,2361 Residential Building Construction,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2,PPP,NPN,LMIN,HZN,U,IND23SS61,IND23SS61LR2JR4BT01BA2PPP
4,9662437702,20200501,101,MASSACHUSETTS DISTRICT OFFICE,PPP,AERO BOX LLC,MI,8/17/21,Paid in Full,24,367437.00,0.0,NaN,57328,The Huntington National Bank,U,N,N,NaN,25.0,57328,The Huntington National Bank,COLUMBUS,OH,Not Available,Unanswered,N,370819.35,20210408,3%,11023.11,48,4842,484210,Transportation and Warehousing,4842 Specialized Freight Trucking,999 Other,"b $350,000-1 million",20 to 49,4842 Specialized Freight Trucking,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3,PPP,NPN,LMIN,HZN,U,IND48SS42,IND48SS42LR2JR4BT13BA3PPP

In [26]:
#md_groups = md_groups.groupby(["INDcode", "Industry", "INDSScode", "IndustrySubsector"]).agg({"LoanNumber":"count"})
#md_groups.shape[0] #290

#groups = ppp_df_hash.groupby(["INDcode", "Industry", "INDSScode", "IndustrySubsector"]).agg({"LoanNumber":"count"})
#groups.shape[0] #

In [27]:
print(ppp_df_hash["INDSScode"].nunique()) #328 - 313

'''
print(ppp_df_hash["HASHcodebase1"].nunique()) #1580 LR
print(ppp_df_hash["HASHcodebase2"].nunique()) #2431  JR
print(ppp_df_hash["HASHcodebase3"].nunique()) #3499 BT
print(ppp_df_hash["HASHcodebase4"].nunique()) #1227 BA
print(ppp_df_hash["HASHcodebase5"].nunique()) #639 PM

print(ppp_df_hash["HASHcodebaseJR"].nunique()) #6924
print(ppp_df_hash["HASHcodebaseJRBT"].nunique()) #26945
print(ppp_df_hash["HASHcodebaseJRBTBA"].nunique()) #43458
'''
print(ppp_df_hash["HASHcodePM"].nunique()) #55127 = 54996


#print(ppp_df_hash["HASHcode"].nunique()) # 26945
#print(ppp_df_hash["HASHcodePM"].nunique()) # 55127
#print(ppp_df_hash["HASHcodefull"].nunique()) #108534 combinations

313
54996

In [29]:
print(ppp_df_hash["ServicingLenderLocationID"].nunique())#4810
print(ppp_df_hash["ServicingLenderName"].nunique()) #4295

4810
4295

Writing HASHcode File

In [30]:
cols= ["LoanNumber", "INDSScode", "INDcode", "SScode", "LRcode","JRcode", "BTcode", "BAcode", "PMcode", "HASHcodePM", "Industry", "IndustrySubsector" ]
#cols = ["LoanNumber", "HASHcodePM", "Industry", "IndustrySubsector"]
ppp_df_hash_reduced = ppp_df_hash[cols]
ppp_df_hash_reduced

,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodePM,Industry,IndustrySubsector
0,9547507704,IND32SS55,IND32,SS55,LR2,JR5,BT01,BA1,PPP,IND32SS55LR2JR5BT01BA1PPP,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing"
1,9777677704,IND56SS17,IND56,SS17,LR2,JR5,BT07,BA1,PPP,IND56SS17LR2JR5BT07BA1PPP,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings
2,5791407702,IND0SS0,IND0,SS0,LR2,JR5,BT04,BA2,PPP,IND0SS0LR2JR5BT04BA2PPP,Not Available,Not Available
3,6223567700,IND23SS61,IND23,SS61,LR2,JR4,BT01,BA2,PPP,IND23SS61LR2JR4BT01BA2PPP,Construction,2361 Residential Building Construction
4,9662437702,IND48SS42,IND48,SS42,LR2,JR4,BT13,BA3,PPP,IND48SS42LR2JR4BT13BA3PPP,Transportation and Warehousing,4842 Specialized Freight Trucking
...,...,...,...,...,...,...,...,...,...,...,...,...
968552,4395967002,IND62SS12,IND62,SS12,LR1,JR3,BT01,BA1,PPP,IND62SS12LR1JR3BT01BA1PPP,Health Care and Social Assistance,6212 Offices of Dentists
968553,6985647108,IND62SS44,IND62,SS44,LR1,JR4,BT11,BA1,PPP,IND62SS44LR1JR4BT11BA1PPP,Health Care and Social Assistance,6244 Child Day Care Services
968554,7996438405,IND23SS82,IND23,SS82,LR1,JR1,BT03,BA1,PPS,IND23SS82LR1JR1BT03BA1PPS,Construction,2382 Building Equipment Contractors
968555,9054647103,IND62SS16,IND62,SS16,LR1,JR2,BT01,BA2,PPP,IND62SS16LR1JR2BT01BA2PPP,Health Care and Social Assistance,6216 Home Health Care Services
968556,9184687004,IND72SS25,IND72,SS25,LR1,JR3,BT03,BA1,PPP,IND72SS25LR1JR3BT03BA1PPP,Accommodation and Food Services,7225 Restaurants and Other Eating Places

In [31]:
ppp_df_hash_reduced.to_csv("../data/ppp_hash.csv")

In [32]:
ppp_df_hash_reduced["BTcode"].value_counts()

BT01    415963
BT02    261542
BT03    177322
BT04     54932
BT05     18086
BT06     12737
BT07     12429
BT08      6780
BT09      2449
BT10      1790
BT11       909
BT12       765
BT13       728
BT14       636
BT15       497
BT16       408
BT17       152
BT18       129
BT19       116
BT20        76
BT21        63
BT22        31
BT23        10
BT24         3
BT25         2
BT26         2
Name: BTcode, dtype: int64

In [34]:
ppp_df_hash = pd.read_csv("../data/ppp_hash.csv")
ppp_df_hash.head()

,Unnamed: 0,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodePM,Industry,IndustrySubsector
0,0,9547507704,IND32SS55,IND32,SS55,LR2,JR5,BT01,BA1,PPP,IND32SS55LR2JR5BT01BA1PPP,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing"
1,1,9777677704,IND56SS17,IND56,SS17,LR2,JR5,BT07,BA1,PPP,IND56SS17LR2JR5BT07BA1PPP,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings
2,2,5791407702,IND0SS0,IND0,SS0,LR2,JR5,BT04,BA2,PPP,IND0SS0LR2JR5BT04BA2PPP,Not Available,Not Available
3,3,6223567700,IND23SS61,IND23,SS61,LR2,JR4,BT01,BA2,PPP,IND23SS61LR2JR4BT01BA2PPP,Construction,2361 Residential Building Construction
4,4,9662437702,IND48SS42,IND48,SS42,LR2,JR4,BT13,BA3,PPP,IND48SS42LR2JR4BT13BA3PPP,Transportation and Warehousing,4842 Specialized Freight Trucking

<b>Sorting Hash Arrays (used to combine feature groups)

In [35]:
ppp_df_hash.loc[ppp_df_hash["LoanNumber"] == 3894287707]

,Unnamed: 0,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodePM,Industry,IndustrySubsector
116929,116929,3894287707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available

In [36]:
cols= ["LoanNumber", "INDSScode", "INDcode", "SScode", "LRcode","JRcode", "BTcode", "BAcode", "PMcode", "HASHcodePM", "Industry", "IndustrySubsector" ]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["INDcode", "SScode", "LRcode", "JRcode", "BAcode", "BTcode","PMcode"], ascending=[True, True, True, True, True, True, True], ignore_index=True)
ppp_df_hashSort.head(40)

,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodePM,Industry,IndustrySubsector
0,3894287707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
1,3910757707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
2,4559867701,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
3,4533907702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
4,9925367708,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
5,4158237710,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
6,3321447710,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
7,2366557707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
8,3191927702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
9,3461597700,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
10,7521657706,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
11,4203327702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
12,4133777701,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
13,4119857705,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
14,4320877702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
15,4272147700,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
16,1526937709,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
17,3497247702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
18,4328877707,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
19,4124397703,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
20,1861887704,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
21,3514637704,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
22,3248217703,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
23,3336527702,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
24,4321407703,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
25,3535997706,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
26,3723007710,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
27,1100577700,IND0SS0,IND0,SS0,LR1,JR1,BT01,BA1,PPP,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
28,4893777704,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
29,1496967705,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
30,4381387701,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
31,4194237707,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
32,1600597702,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
33,1719447700,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
34,9823957707,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
35,7348777702,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
36,9500297705,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
37,3185537108,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
38,4189217707,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available
39,3013257710,IND0SS0,IND0,SS0,LR1,JR1,BT02,BA1,PPP,IND0SS0LR1JR1BT02BA1PPP,Not Available,Not Available

In [37]:
print(ppp_df_hashSort["INDSScode"].nunique()) #313
print(ppp_df_hashSort["INDSScode"].unique().tolist())
print(ppp_df_hashSort["HASHcodePM"].nunique()) #54996

313

In [39]:
print(ppp_df_hashSort.loc[ppp_df_hashSort["INDSScode"] =="IND11SS22"].count())
print(ppp_df_hashSort.loc[ppp_df_hashSort["JRcode"] =="JR1"].count())

313
LoanNumber           303
INDSScode            303
INDcode              303
SScode               303
LRcode               303
JRcode               303
BTcode               303
BAcode               303
PMcode               303
HASHcodePM           303
Industry             303
IndustrySubsector    303
dtype: int64

Reduced Columns for Sorted HASHcodes

In [41]:
cols = ["LoanNumber", "HASHcodePM", "Industry", "IndustrySubsector"]
ppp_df_hashSort_reduced = ppp_df_hashSort[cols]
ppp_df_hashSort_reduced

,LoanNumber,HASHcodePM,Industry,IndustrySubsector
0,3894287707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
1,3910757707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
2,4559867701,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
3,4533907702,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
4,9925367708,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
...,...,...,...,...
968552,3488997103,IND99SS99LR5JR6BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968553,5482257701,IND99SS99LR5JR7BT04BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968554,6699567107,IND99SS99LR5JR8BT02BA1PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968555,5359597703,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments
968556,5843777700,IND99SS99LR5JR8BT02BA2PPP,Nonclassifiable Establishments,Nonclassifiable Establishments

Output for Sorted HASHcodes

In [42]:
ppp_df_hashSort_reduced.to_csv("../data/ppp_hashSort.csv")
read_hsh = pd.read_csv('../data/ppp_hashSort.csv')
read_hsh.head()

,Unnamed: 0,LoanNumber,HASHcodePM,Industry,IndustrySubsector
0,0,3894287707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
1,1,3910757707,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
2,2,4559867701,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
3,3,4533907702,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available
4,4,9925367708,IND0SS0LR1JR1BT01BA1PPP,Not Available,Not Available

In [41]:
read_hsh.dtypes

Unnamed: 0            int64
LoanNumber            int64
INDSScode            object
INDcode              object
SScode               object
LRcode               object
JRcode               object
BTcode               object
BAcode               object
PMcode               object
HASHcodePM           object
Industry             object
IndustrySubsector    object
dtype: object

In [ ]:
#cols= ["HASHcodePM", "LoanNumber"]
#ppp_df_23_hashSort = ppp_df_23_hash[cols]
#ppp_df_23_hashSort = ppp_df_23_hashSort.sort_values(["HASHcodePM"], ascending=[True])
#print(ppp_df_23_hashSort["HASHcodePM"].nunique())
#ppp_df_23_hashSort.head(20)

In [42]:
#would need to combine loan factors and sort array
#. using haashcode sequence create layergroup for each unique combination
# if layer contains feature = INDcode add to industry group[1-21]
# if layer contains feature = SScode add to subsector group
# if layer contains feature = LRcode [1-5] add to LoanRange group[1-5]
# if layer contains feature = JRcode [1-9] add to JobsRange group[1-9]
# if layer contains feature = BTcode [1-26] add to BusinessType group[1-26]
# if layer contains feature = PMcode [1-2] add to ProcessingMethod group[1-2]