In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from tqdm.notebook import tqdm

2023 RAW INPUT

In [2]:
csv_path = "../data/raw/>150K/public_150k_plus_230630.csv"
ppp_df_23 = pd.read_csv(csv_path)
ppp_df_23.head()

In [3]:
ppp_df_23.shape[0]

965552

In [4]:
ppp_df_23.columns

Index(['LoanNumber', 'DateApproved', 'SBAOfficeCode', 'ProcessingMethod',
       'BorrowerName', 'BorrowerAddress', 'BorrowerCity', 'BorrowerState',
       'BorrowerZip', 'LoanStatusDate', 'LoanStatus', 'Term',
       'SBAGuarantyPercentage', 'InitialApprovalAmount',
       'CurrentApprovalAmount', 'UndisbursedAmount', 'FranchiseName',
       'ServicingLenderLocationID', 'ServicingLenderName',
       'ServicingLenderAddress', 'ServicingLenderCity', 'ServicingLenderState',
       'ServicingLenderZip', 'RuralUrbanIndicator', 'HubzoneIndicator',
       'LMIIndicator', 'BusinessAgeDescription', 'ProjectCity',
       'ProjectCountyName', 'ProjectState', 'ProjectZip', 'CD', 'JobsReported',
       'NAICSCode', 'Race', 'Ethnicity', 'UTILITIES_PROCEED',
       'PAYROLL_PROCEED', 'MORTGAGE_INTEREST_PROCEED', 'RENT_PROCEED',
       'REFINANCE_EIDL_PROCEED', 'HEALTH_CARE_PROCEED',
       'DEBT_INTEREST_PROCEED', 'BusinessType', 'OriginatingLenderLocationID',
       'OriginatingLender', 'OriginatingLenderCity', 'OriginatingLenderState',
       'Gender', 'Veteran', 'NonProfit', 'ForgivenessAmount',
       'ForgivenessDate'],
      dtype='object')

<h4>Null Check

<b>Null DataFrame

In [5]:
pd.set_option('display.max_rows', 70)
print(ppp_df_23.isnull().sum())

LoanNumber                          0
DateApproved                        0
SBAOfficeCode                       0
ProcessingMethod                    0
BorrowerName                        4
BorrowerAddress                    14
BorrowerCity                       12
BorrowerState                      13
BorrowerZip                        13
LoanStatusDate                  16825
LoanStatus                          0
Term                                0
SBAGuarantyPercentage               0
InitialApprovalAmount               0
CurrentApprovalAmount               0
UndisbursedAmount                  46
FranchiseName                  930147
ServicingLenderLocationID           0
ServicingLenderName                 0
ServicingLenderAddress              0
ServicingLenderCity                 0
ServicingLenderState                0
ServicingLenderZip                  0
RuralUrbanIndicator                 0
HubzoneIndicator                    0
LMIIndicator                        0
BusinessAgeDescription              1
ProjectCity                        13
ProjectCountyName                  57
ProjectState                        9
ProjectZip                         14
CD                                 46
JobsReported                        1
NAICSCode                        6628
Race                                0
Ethnicity                           0
UTILITIES_PROCEED              627203
PAYROLL_PROCEED                  1827
MORTGAGE_INTEREST_PROCEED      920028
RENT_PROCEED                   866328
REFINANCE_EIDL_PROCEED         942704
HEALTH_CARE_PROCEED            908126
DEBT_INTEREST_PROCEED          933856
BusinessType                      720
OriginatingLenderLocationID         0
OriginatingLender                   0
OriginatingLenderCity               0
OriginatingLenderState              0
Gender                              0
Veteran                             0
NonProfit                      906202
ForgivenessAmount               26515
ForgivenessDate                 26515
dtype: int64

In [6]:
pd.set_option('display.max_rows', 70)
ppp_df_23.dtypes

LoanNumber                       int64
DateApproved                    object
SBAOfficeCode                    int64
ProcessingMethod                object
BorrowerName                    object
BorrowerAddress                 object
BorrowerCity                    object
BorrowerState                   object
BorrowerZip                     object
LoanStatusDate                  object
LoanStatus                      object
Term                             int64
SBAGuarantyPercentage            int64
InitialApprovalAmount          float64
CurrentApprovalAmount          float64
UndisbursedAmount              float64
FranchiseName                   object
ServicingLenderLocationID        int64
ServicingLenderName             object
ServicingLenderAddress          object
ServicingLenderCity             object
ServicingLenderState            object
ServicingLenderZip              object
RuralUrbanIndicator             object
HubzoneIndicator                object
LMIIndicator                    object
BusinessAgeDescription          object
ProjectCity                     object
ProjectCountyName               object
ProjectState                    object
ProjectZip                      object
CD                              object
JobsReported                   float64
NAICSCode                      float64
Race                            object
Ethnicity                       object
UTILITIES_PROCEED              float64
PAYROLL_PROCEED                float64
MORTGAGE_INTEREST_PROCEED      float64
RENT_PROCEED                   float64
REFINANCE_EIDL_PROCEED         float64
HEALTH_CARE_PROCEED            float64
DEBT_INTEREST_PROCEED          float64
BusinessType                    object
OriginatingLenderLocationID      int64
OriginatingLender               object
OriginatingLenderCity           object
OriginatingLenderState          object
Gender                          object
Veteran                         object
NonProfit                       object
ForgivenessAmount              float64
ForgivenessDate                 object
dtype: object

In [7]:
pd.reset_option('all', silent=True)

<b>Null DataFrame

In [8]:
pd.set_option('display.max_columns', None)
null_columns=ppp_df_23.columns[ppp_df_23.isnull().any()]
df_col_null = ppp_df_23[null_columns]
df_col_null

,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,UndisbursedAmount,FranchiseName,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,NonProfit,ForgivenessAmount,ForgivenessDate
0,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,12/18/2020,0.0,NaN,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510.0,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,NaN,773553.37,11/20/2020
1,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,09/28/2021,0.0,NaN,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730.0,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,NaN,746336.24,08/12/2021
2,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,03/17/2021,0.0,NaN,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,NaN,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,Y,696677.49,02/10/2021
3,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,10/16/2021,0.0,NaN,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-23,21.0,236115.0,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,NaN,395264.11,09/10/2021
4,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,0.0,NaN,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210.0,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370819.35,04/08/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965547,"ROY E PAULSON, JR., P.C.",102 N. Kenwood,CASPER,WY,82601-2724,01/13/2021,0.0,NaN,Existing or more than 2 years old,CASPER,NATRONA,WY,82601-2724,WY-,15.0,621210.0,NaN,150000.00,NaN,NaN,NaN,NaN,NaN,Corporation,NaN,151037.50,12/09/2020
965548,"SWEETWATER COUNTY CHILD DEVELOPMENTAL CENTER, ...",1715 HITCHING POST DR,GREEN RIVER,WY,82935-5783,12/08/2020,0.0,NaN,Existing or more than 2 years old,GREEN RIVER,SWEETWATER,WY,82935-5783,WY-,42.0,624410.0,5000.0,145000.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Childcare Center,Y,150789.04,11/03/2020
965549,ELECTRICAL SYSTEMS OF WYOMING INC,1105 Adon Rd,Rozet,WY,82727-8465,09/15/2021,0.0,NaN,Existing or more than 2 years old,Rozet,CAMPBELL,WY,82727-8465,WY-,5.0,238210.0,1.0,149997.00,NaN,NaN,NaN,NaN,NaN,Subchapter S Corporation,NaN,150743.84,08/17/2021
965550,EDEN LIFE CARE,30 N. Gould Street Suite 4000,SHERIDAN,WY,82801,03/08/2022,0.0,NaN,New Business or 2 years or less,SHERIDAN,SHERIDAN,WY,82801-0001,WY-,7.0,621610.0,NaN,150000.00,NaN,NaN,NaN,NaN,NaN,Corporation,NaN,152820.83,02/23/2022
965551,S & S JOHNSON ENTERPRISES INC,7342 Granite Loop Rd,TETON VILLAGE,WY,83025-0550,10/22/2021,0.0,NaN,Existing or more than 2 years old,TETON VILLAGE,TETON,WY,83025-0550,WY-,11.0,722511.0,NaN,150000.00,NaN,NaN,NaN,NaN,NaN,Subchapter S Corporation,NaN,152162.50,09/22/2021

In [9]:
pd.reset_option('all', silent=True)

<b>Null Address Update: Null State

In [10]:
null_state = ppp_df_23.loc[ppp_df_23["BorrowerState"].isnull()] #verify same mssing addresses in main
null_state

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
0,9547507704,05/01/2020,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,12/18/2020,...,Corporation,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020
1,9777677704,05/01/2020,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,09/28/2021,...,Sole Proprietorship,19248,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021
2,5791407702,05/01/2020,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,03/17/2021,...,Non-Profit Organization,9551,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021
3,6223567700,05/01/2020,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,10/16/2021,...,Corporation,9551,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021
5,9774337701,05/01/2020,101,PPP,HUDSON EXTRUSIONS INC.,NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,332137.41,05/10/2021
6,9794577700,05/01/2020,491,PPP,FRUIT COVE BAPTIST CHURCH OF JACKSONVILLE FL INC,501 State Road 13,Saint Johns,NaN,32259-2832,02/19/2021,...,Non-Profit Organization,19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,Y,291741.75,01/07/2021
7,9722187702,05/01/2020,101,PPP,MIAMITOWN AUTO PARTS AND RECYCLING INC,NaN,NaN,NaN,NaN,02/24/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,269416.44,01/25/2021
8,9725917702,05/01/2020,101,PPP,POPPYCOCKS INC,NaN,NaN,NaN,NaN,08/17/2021,...,Subchapter S Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,259982.88,06/24/2021
9,9666867710,05/01/2020,101,PPP,CHURCH SQUARE PHARMACY INC,NaN,NaN,NaN,NaN,04/21/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,252253.42,03/31/2021
10,9662697710,05/01/2020,101,PPP,"MILFAST INDUSTRIAL SUPPLY, INC",NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Female Owned,Non-Veteran,NaN,175643.41,04/06/2021
11,9724667708,05/01/2020,101,PPP,FERNANDINA BEACH HOTEL GROUP LLC,NaN,NaN,NaN,NaN,08/17/2021,...,Limited Liability Company(LLC),57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,172263.32,07/29/2021
12,9672967701,05/01/2020,101,PPP,OTTAWA PRODUCTS CO INC,NaN,NaN,NaN,NaN,11/17/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,156504.89,04/23/2021

In [11]:
ppp_df_23.loc[ppp_df_23["LoanNumber"] == 9547507704, 'BorrowerState'] = "SC"
ppp_df_23.loc[ppp_df_23["LoanNumber"] == 9777677704, 'BorrowerState'] = "SC"
ppp_df_23.loc[ppp_df_23["LoanNumber"] == 5791407702, 'BorrowerState'] = "WA"
ppp_df_23.loc[ppp_df_23["LoanNumber"] == 6223567700, 'BorrowerState'] = "CA"
ppp_df_23.loc[ppp_df_23["LoanNumber"] == 9794577700, 'BorrowerState'] = "FL"
'''9547507704, 9777677704, 5791407702, 6223567700, 9794577700 replaced'''

'9547507704, 9777677704, 5791407702, 6223567700, 9794577700 replaced'

In [12]:
null_state_check = ppp_df_23.loc[ppp_df_23["BorrowerState"].isnull()] 
null_state_check

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021
5,9774337701,05/01/2020,101,PPP,HUDSON EXTRUSIONS INC.,NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,332137.41,05/10/2021
7,9722187702,05/01/2020,101,PPP,MIAMITOWN AUTO PARTS AND RECYCLING INC,NaN,NaN,NaN,NaN,02/24/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,269416.44,01/25/2021
8,9725917702,05/01/2020,101,PPP,POPPYCOCKS INC,NaN,NaN,NaN,NaN,08/17/2021,...,Subchapter S Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,259982.88,06/24/2021
9,9666867710,05/01/2020,101,PPP,CHURCH SQUARE PHARMACY INC,NaN,NaN,NaN,NaN,04/21/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,252253.42,03/31/2021
10,9662697710,05/01/2020,101,PPP,"MILFAST INDUSTRIAL SUPPLY, INC",NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Female Owned,Non-Veteran,NaN,175643.41,04/06/2021
11,9724667708,05/01/2020,101,PPP,FERNANDINA BEACH HOTEL GROUP LLC,NaN,NaN,NaN,NaN,08/17/2021,...,Limited Liability Company(LLC),57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,172263.32,07/29/2021
12,9672967701,05/01/2020,101,PPP,OTTAWA PRODUCTS CO INC,NaN,NaN,NaN,NaN,11/17/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,156504.89,04/23/2021

<b>Null Address Update: Null Borrower Address

In [13]:
add_null = ppp_df_23.loc[ppp_df_23["BorrowerAddress"].isnull()]
add_null

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021
5,9774337701,05/01/2020,101,PPP,HUDSON EXTRUSIONS INC.,NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,332137.41,05/10/2021
7,9722187702,05/01/2020,101,PPP,MIAMITOWN AUTO PARTS AND RECYCLING INC,NaN,NaN,NaN,NaN,02/24/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,269416.44,01/25/2021
8,9725917702,05/01/2020,101,PPP,POPPYCOCKS INC,NaN,NaN,NaN,NaN,08/17/2021,...,Subchapter S Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,259982.88,06/24/2021
9,9666867710,05/01/2020,101,PPP,CHURCH SQUARE PHARMACY INC,NaN,NaN,NaN,NaN,04/21/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,252253.42,03/31/2021
10,9662697710,05/01/2020,101,PPP,"MILFAST INDUSTRIAL SUPPLY, INC",NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Female Owned,Non-Veteran,NaN,175643.41,04/06/2021
11,9724667708,05/01/2020,101,PPP,FERNANDINA BEACH HOTEL GROUP LLC,NaN,NaN,NaN,NaN,08/17/2021,...,Limited Liability Company(LLC),57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,172263.32,07/29/2021
12,9672967701,05/01/2020,101,PPP,OTTAWA PRODUCTS CO INC,NaN,NaN,NaN,NaN,11/17/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,156504.89,04/23/2021
157207,2030257707,05/01/2020,912,PPP,ROMUALD Z JOVERO DBA R &AMP; B INTERNATIONAL O...,NaN,NaN,CA,NaN,09/30/2021,...,Sole Proprietorship,48270,"JPMorgan Chase Bank, National Association",COLUMBUS,OH,Unanswered,Unanswered,NaN,160691.30,08/20/2021
175156,8181657703,05/01/2020,811,PPP,"SILVERORE ENTERPRISES, LLC",NaN,FRISCO,CO,80443,01/22/2021,...,Limited Liability Company(LLC),53803,"U.S. Bank, National Association",CINCINNATI,OH,Male Owned,Non-Veteran,NaN,250902.63,11/30/2020
663182,1681327703,05/01/2020,248,PPP,PETREY AB CORP.,NaN,NaN,NY,NaN,06/30/2020,...,Subchapter S Corporation,48270,"JPMorgan Chase Bank, National Association",COLUMBUS,OH,Unanswered,Unanswered,NaN,NaN,NaN
789096,9793947702,05/01/2020,464,PPP,DANIEL ISLAND VENTURES LLC,NaN,DANIEL ISLAND,SC,29492-7504,08/04/2021,...,Limited Liability Company(LLC),19248,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,156223.23,06/11/2021
845402,3192617705,05/01/2020,610,PPP,FOUNDATION FOR INSPIRATION AND,NaN,NaN,TX,NaN,12/15/2020,...,Corporation,48270,"JPMorgan Chase Bank, National Association",COLUMBUS,OH,Unanswered,Unanswered,NaN,NaN,NaN
882649,2491137709,05/01/2020,610,PPP,"PATRIOT PLACE &AMP; FINISH, LLC",NaN,NaN,TX,NaN,06/24/2021,...,Limited Liability Company(LLC),48270,"JPMorgan Chase Bank, National Association",COLUMBUS,OH,Unanswered,Unanswered,NaN,153548.86,05/10/2021

In [14]:
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==2030257707, 'BorrowerAddress'] ="1105 East Plaza Blvd. Suite A"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==2030257707, 'BorrowerCity'] ="National City"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==8181657703, 'BorrowerAddress'] ="601 Main St"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==1681327703, 'BorrowerAddress'] ="2041 Park St"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==1681327703, 'BorrowerCity'] ="ATLANTIC BEACH"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==9793947702, 'BorrowerAddress'] ="17 Lockwood Drive, Suite 400"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==3192617705, 'BorrowerAddress'] ="2541 SOUTH IH-35 SUITE 200-263"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==3192617705, 'BorrowerCity'] ="Round Rock"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==2491137709, 'BorrowerAddress'] ="261 FLOWER RIDGE DR"
ppp_df_23.loc[ppp_df_23["LoanNumber"] ==2491137709, 'BorrowerCity'] ="FORT WORTH"

In [15]:
null_add_check = ppp_df_23.loc[ppp_df_23["BorrowerAddress"].isnull()] 
null_add_check

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021
5,9774337701,05/01/2020,101,PPP,HUDSON EXTRUSIONS INC.,NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,332137.41,05/10/2021
7,9722187702,05/01/2020,101,PPP,MIAMITOWN AUTO PARTS AND RECYCLING INC,NaN,NaN,NaN,NaN,02/24/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,269416.44,01/25/2021
8,9725917702,05/01/2020,101,PPP,POPPYCOCKS INC,NaN,NaN,NaN,NaN,08/17/2021,...,Subchapter S Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,259982.88,06/24/2021
9,9666867710,05/01/2020,101,PPP,CHURCH SQUARE PHARMACY INC,NaN,NaN,NaN,NaN,04/21/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,252253.42,03/31/2021
10,9662697710,05/01/2020,101,PPP,"MILFAST INDUSTRIAL SUPPLY, INC",NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328,The Huntington National Bank,COLUMBUS,OH,Female Owned,Non-Veteran,NaN,175643.41,04/06/2021
11,9724667708,05/01/2020,101,PPP,FERNANDINA BEACH HOTEL GROUP LLC,NaN,NaN,NaN,NaN,08/17/2021,...,Limited Liability Company(LLC),57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,172263.32,07/29/2021
12,9672967701,05/01/2020,101,PPP,OTTAWA PRODUCTS CO INC,NaN,NaN,NaN,NaN,11/17/2021,...,Corporation,57328,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,156504.89,04/23/2021

"Not Available" for missing Address+City+State <br>
Manually updated in FIPS processing baesd on Borrower Name

In [16]:
ppp_df_23.loc[ppp_df_23["BorrowerState"].isnull(), 'BorrowerState'] = "Not Available"
ppp_df_23.loc[ppp_df_23["BorrowerAddress"].isnull(), 'BorrowerAddress'] = "Not Available"
ppp_df_23.loc[ppp_df_23["BorrowerCity"].isnull(), 'BorrowerCity'] = "Not Available"

Combining Columns for New Full Address column

In [17]:
ppp_df_23['FullAdd'] = ppp_df_23.BorrowerAddress + ", " + ppp_df_23.BorrowerCity + ", " + ppp_df_23.BorrowerState
ppp_df_23['ServicingLenderFullAddress'] = ppp_df_23.ServicingLenderAddress + ", " + ppp_df_23.ServicingLenderCity + ", " + ppp_df_23.ServicingLenderState
ppp_df_23.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate,FullAdd,ServicingLenderFullAddress
0,9547507704,05/01/2020,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,12/18/2020,...,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA"
1,9777677704,05/01/2020,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,09/28/2021,...,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA"
2,5791407702,05/01/2020,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,03/17/2021,...,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC"
3,6223567700,05/01/2020,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,10/16/2021,...,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC"
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,08/17/2021,...,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH"

<b>File Write for Updated Address

In [18]:
ppp_df_23.to_csv("../data/raw/>150K/public_150k_plus_230630_add.csv")

<h2>II

<b>File Read of Update RAW

In [19]:
csv_path_update = "../data/raw/>150K/public_150k_plus_230630_add.csv"
ppp_df_23 = pd.read_csv(csv_path_update, index_col=0)

Null Updates (cont.)

In [20]:
ppp_df_23['ForgivenessAmount']=ppp_df_23['ForgivenessAmount'].fillna(0.0)
ppp_df_23['UndisbursedAmount']=ppp_df_23['UndisbursedAmount'].fillna(0.0)
null_UndisbursedAmount = ppp_df_23.loc[ppp_df_23["UndisbursedAmount"].isnull()] 
null_UndisbursedAmount.head()

Empty DataFrame
Columns: [LoanNumber, DateApproved, SBAOfficeCode, ProcessingMethod, BorrowerName, BorrowerAddress, BorrowerCity, BorrowerState, BorrowerZip, LoanStatusDate, LoanStatus, Term, SBAGuarantyPercentage, InitialApprovalAmount, CurrentApprovalAmount, UndisbursedAmount, FranchiseName, ServicingLenderLocationID, ServicingLenderName, ServicingLenderAddress, ServicingLenderCity, ServicingLenderState, ServicingLenderZip, RuralUrbanIndicator, HubzoneIndicator, LMIIndicator, BusinessAgeDescription, ProjectCity, ProjectCountyName, ProjectState, ProjectZip, CD, JobsReported, NAICSCode, Race, Ethnicity, UTILITIES_PROCEED, PAYROLL_PROCEED, MORTGAGE_INTEREST_PROCEED, RENT_PROCEED, REFINANCE_EIDL_PROCEED, HEALTH_CARE_PROCEED, DEBT_INTEREST_PROCEED, BusinessType, OriginatingLenderLocationID, OriginatingLender, OriginatingLenderCity, OriginatingLenderState, Gender, Veteran, NonProfit, ForgivenessAmount, ForgivenessDate, FullAdd, ServicingLenderFullAddress]
Index: []

[0 rows x 55 columns]

<h4>Date to Timestamp Conversion<br></h4>
mm/dd/yyyy > yyyymmdd

<b>DateApproved

In [21]:
dates = []
for date in ppp_df_23['DateApproved']:
    dt = pd.to_datetime(date, format='%m/%d/%Y') #year #### format
    dates.append(dt)

ppp_df_23['DateApprovedTS'] = dates
ppp_df_23['DateApprovedTS']= ppp_df_23['DateApprovedTS'].astype(str)
ppp_df_23['DateApprovedTS']= ppp_df_23['DateApprovedTS'].str.replace('-', '', regex=True)
ppp_df_23.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate,FullAdd,ServicingLenderFullAddress,DateApprovedTS
0,9547507704,05/01/2020,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,12/18/2020,...,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501
1,9777677704,05/01/2020,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,09/28/2021,...,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501
2,5791407702,05/01/2020,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,03/17/2021,...,CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501
3,6223567700,05/01/2020,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,10/16/2021,...,CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,08/17/2021,...,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501

<b>ForgivenessDate

In [22]:
fdates = []
for fdate in ppp_df_23['ForgivenessDate']:
    fdt = pd.to_datetime(fdate, format='%m/%d/%Y') #year #### format
    fdates.append(fdt)

ppp_df_23['ForgivenessDateTS'] = fdates
ppp_df_23['ForgivenessDateTS']= ppp_df_23['ForgivenessDateTS'].astype(str)
ppp_df_23['ForgivenessDateTS']= ppp_df_23['ForgivenessDateTS'].str.replace('-', '', regex=True)
ppp_df_23.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS
0,9547507704,05/01/2020,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,12/18/2020,...,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120
1,9777677704,05/01/2020,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,09/28/2021,...,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812
2,5791407702,05/01/2020,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,03/17/2021,...,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210
3,6223567700,05/01/2020,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,10/16/2021,...,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,08/17/2021,...,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408

<b>LoanStatusDate

In [23]:
ldates = []
for ldate in ppp_df_23['LoanStatusDate']:
    ldt = pd.to_datetime(ldate, format='%m/%d/%Y') #year #### format
    ldates.append(ldt)

ppp_df_23['LoanStatusDateTS'] = ldates
ppp_df_23['LoanStatusDateTS']= ppp_df_23['LoanStatusDateTS'].astype(str)
ppp_df_23['LoanStatusDateTS']= ppp_df_23['LoanStatusDateTS'].str.replace('-', '', regex=True)
ppp_df_23.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS
0,9547507704,05/01/2020,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,12/18/2020,...,Unanswered,Unanswered,NaN,773553.37,11/20/2020,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218
1,9777677704,05/01/2020,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,09/28/2021,...,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928
2,5791407702,05/01/2020,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,03/17/2021,...,Unanswered,Unanswered,Y,696677.49,02/10/2021,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317
3,6223567700,05/01/2020,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,10/16/2021,...,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016
4,9662437702,05/01/2020,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,08/17/2021,...,Unanswered,Unanswered,NaN,370819.35,04/08/2021,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408,20210817

Dropping Original Date Columns

In [24]:
ppp_df_23 = ppp_df_23.drop(['DateApproved', 'ForgivenessDate','LoanStatusDate'], axis=1)

NaT > NaN > "Not Available" [LoanStatusDateTS, ForgivenessDateTS]

In [25]:
ppp_df_23 = ppp_df_23.replace('NaT', np.nan)
ppp_df_23['LoanStatusDateTS']=ppp_df_23['LoanStatusDateTS'].fillna("Not Available")
ppp_df_23['ForgivenessDateTS']=ppp_df_23['ForgivenessDateTS'].fillna("Not Available")

<b> Update File due to procesing times of datetime columns

In [26]:
ppp_df_23.to_csv("../data/raw/>150K/public_150k_plus_230630_addts.csv")

<h2>III

<b>File Read of Updated RAW + address + ts

In [2]:
csv_path_update = "../data/raw/>150K/public_150k_plus_230630_addts.csv"
ppp_df_23 = pd.read_csv(csv_path_update, index_col=0)

<h4>NAICS Integration

<b>NAICSCode

In [3]:
naics_ind = pd.read_csv("../data/raw/NAICS/NAICSind.csv") #NAICSCode, Industry
naics_full = pd.read_csv("../data/raw/NAICS/NAICSfull.csv") #NAICSCode, SubIndustry Values

In [4]:
naics_ind["NA"] = naics_ind["NA"].astype(str)
print(naics_ind.shape[0])
naics_ind.head()

25

   NA                                       Industry
0  11     Agriculture, Forestry, Fishing and Hunting
1  21  Mining, Quarrying, and Oil and Gas Extraction
2  22                                      Utilities
3  23                                   Construction
4  31                                  Manufacturing

In [5]:
naics_full["NA"] = naics_full["NAICSCode"].astype(str).str[:2]
print(naics_full.shape[0])
naics_full.head()

1057

,NAICSCode,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA
0,111110,Soybean Farming,999 Other,1111 Oilseed and Grain Farming,1111,11
1,111120,Oilseed (except Soybean) Farming,999 Other,1111 Oilseed and Grain Farming,1111,11
2,111130,Dry Pea and Bean Farming,999 Other,1111 Oilseed and Grain Farming,1111,11
3,111140,Wheat Farming,999 Other,1111 Oilseed and Grain Farming,1111,11
4,111150,Corn Farming,999 Other,1111 Oilseed and Grain Farming,1111,11

Merging NAICS Dataframes on NA

In [6]:
naics_comb = naics_full.merge(naics_ind, on ="NA", how="left")
print(naics_comb.shape[0])
naics_comb.head()

1057

,NAICSCode,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry
0,111110,Soybean Farming,999 Other,1111 Oilseed and Grain Farming,1111,11,"Agriculture, Forestry, Fishing and Hunting"
1,111120,Oilseed (except Soybean) Farming,999 Other,1111 Oilseed and Grain Farming,1111,11,"Agriculture, Forestry, Fishing and Hunting"
2,111130,Dry Pea and Bean Farming,999 Other,1111 Oilseed and Grain Farming,1111,11,"Agriculture, Forestry, Fishing and Hunting"
3,111140,Wheat Farming,999 Other,1111 Oilseed and Grain Farming,1111,11,"Agriculture, Forestry, Fishing and Hunting"
4,111150,Corn Farming,999 Other,1111 Oilseed and Grain Farming,1111,11,"Agriculture, Forestry, Fishing and Hunting"

Parsing for Necessary Columns

In [7]:
cols = ["NAICSCode","Industry","IndustrySubsector","LongName"]
naics_final = naics_comb[cols]
print(naics_final.shape[0])
naics_final.head()

1057

,NAICSCode,Industry,IndustrySubsector,LongName
0,111110,"Agriculture, Forestry, Fishing and Hunting",1111 Oilseed and Grain Farming,Soybean Farming
1,111120,"Agriculture, Forestry, Fishing and Hunting",1111 Oilseed and Grain Farming,Oilseed (except Soybean) Farming
2,111130,"Agriculture, Forestry, Fishing and Hunting",1111 Oilseed and Grain Farming,Dry Pea and Bean Farming
3,111140,"Agriculture, Forestry, Fishing and Hunting",1111 Oilseed and Grain Farming,Wheat Farming
4,111150,"Agriculture, Forestry, Fishing and Hunting",1111 Oilseed and Grain Farming,Corn Farming

NAICS Null Check, Dtypes

In [8]:
print(naics_final.isnull().sum())

NAICSCode            0
Industry             0
IndustrySubsector    0
LongName             0
dtype: int64

In [9]:
naics_final.dtypes

NAICSCode             int64
Industry             object
IndustrySubsector    object
LongName             object
dtype: object

Convert NAICSCode column from float match NAICS Int64

In [10]:
ppp_df_23["NAICSCode"] = ppp_df_23["NAICSCode"].fillna(0) # 6628
ppp_df_23["NAICSCode"] = ppp_df_23["NAICSCode"].astype("Int64")
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,GA,Unanswered,Unanswered,NaN,773553.37,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,GA,Male Owned,Non-Veteran,NaN,746336.24,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,NC,Unanswered,Unanswered,Y,696677.49,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,NC,Male Owned,Non-Veteran,NaN,395264.11,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,OH,Unanswered,Unanswered,NaN,370819.35,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408,20210817

Merge NAICS to Main

In [11]:
ppp_df_23_merge = ppp_df_23.merge(naics_final, on="NAICSCode", how="left")
ppp_df_23_merge.head() #6632

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,NonProfit,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,NaN,773553.37,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,NaN,746336.24,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,Y,696677.49,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,NaN,NaN,NaN
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,NaN,395264.11,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,NaN,370819.35,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving

Review Nulls on Merge

In [12]:
ppp_df_23_merge.loc[ppp_df_23_merge["Industry"].isnull()] #12162

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,NonProfit,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,Y,696677.49,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,NaN,NaN,NaN
36,4820397010,1084,PPP,"COLVILLE, INC.",4300 B Street,ANCHORAGE,AK,99503-5913,Paid in Full,24,...,NaN,3819960.24,"4300 B Street, ANCHORAGE, AK","3111 'C' St, ANCHORAGE, AK",20200404,20210611,20210720,NaN,NaN,NaN
260,6287537004,1084,PPP,SEWARD ASSOCIATION FOR THE ADVANCEMENT OF MARI...,301 Railway Avenue,SEWARD,AK,99664-3801,Paid in Full,24,...,NaN,1051530.90,"301 Railway Avenue, SEWARD, AK","3111 'C' St, ANCHORAGE, AK",20200406,20201103,20201217,NaN,NaN,NaN
305,1892977209,1084,PPP,DENALI VISIONS 3000,2211 Sunrise Dr,ANCHORAGE,AK,99508-3273,Paid in Full,24,...,NaN,974986.64,"2211 Sunrise Dr, ANCHORAGE, AK","101 W 36th Ave, ANCHORAGE, AK",20200415,20211214,20220106,NaN,NaN,NaN
429,5784067001,1084,PPP,TONGASS TRADING COMPANY,201 DOCK ST,KETCHIKAN,AK,99901-6407,Paid in Full,24,...,NaN,742358.88,"201 DOCK ST, KETCHIKAN, AK","2030 Sea level Dr Ste 300, KETCHIKAN, AK",20200406,20201105,20210129,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964869,4935817005,897,PPP,"BEG, LLC",1709 Muirfield Court PO BOX 319,DOUGLAS,WY,82633-8701,Paid in Full,24,...,NaN,215095.51,"1709 Muirfield Court PO BOX 319, DOUGLAS, WY","322 Walnut St, DOUGLAS, WY",20200404,20210125,20210218,NaN,NaN,NaN
964906,3960157702,897,PPP,TAURUS ENGINEERING AND CONTROL INC,190 PENDELL BLVD NO 1074,MILLS,WY,82644,Paid in Full,24,...,NaN,211957.42,"190 PENDELL BLVD NO 1074, MILLS, WY","101 N Philips Ave, SIOUX FALLS, SD",20200501,20210915,20211020,NaN,NaN,NaN
964978,7342767709,897,PPP,CK EMPLOYMENT SERVICES,1 FIR RD,DUBOIS,WY,82513,Paid in Full,24,...,NaN,201786.57,"1 FIR RD, DUBOIS, WY","425 Walnut St, CINCINNATI, OH",20200501,20201209,20210122,NaN,NaN,NaN
965262,3885147709,897,PPP,CONTRACTORS SUPPLY INC - GILLETTE,5005 ROURKE AVE,GILLETTE,WY,82718,Paid in Full,24,...,NaN,174901.89,"5005 ROURKE AVE, GILLETTE, WY","101 N Philips Ave, SIOUX FALLS, SD",20200501,20210608,20210714,NaN,NaN,NaN
965480,5145237302,897,PPP,WYO D CONSTRUCTION LLC,PO Box 118,La Barge,WY,83123,Paid in Full,24,...,NaN,157488.73,"PO Box 118, La Barge, WY","111 W Monroe St, CHICAGO, IL",20200430,20210715,20210812,NaN,NaN,NaN

<b>NAICS Formatting

In [13]:
ppp_df_23 = ppp_df_23_merge

In [14]:
ppp_df_23.loc[ppp_df_23["NAICSCode"] == 999990, 'Industry'] = 'Nonclassifiable Establishments'
ppp_df_23.loc[ppp_df_23["NAICSCode"] == 999990, 'IndustrySubsector'] = 'Nonclassifiable Establishments'
ppp_df_23.loc[ppp_df_23["NAICSCode"] == 999990, 'LongName'] = 'Nonclassifiable Establishments'

In [15]:
ppp_df_23.loc[ppp_df_23["NAICSCode"] == 999990].head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,NonProfit,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName
1503,1126217303,1084,PPP,"NYSTUENS FOLLY, LLC",1811 Abbott Rd,ANCHORAGE,AK,99507,Paid in Full,24,...,NaN,254601.10,"1811 Abbott Rd, ANCHORAGE, AK","101 W 36th Ave, ANCHORAGE, AK",20200428,20210722,20210807,Nonclassifiable Establishments,Nonclassifiable Establishments,Nonclassifiable Establishments
2001,5414867008,1084,PPP,ALASKA SB LLC,317 W 104th Ave.,ANCHORAGE,AK,99515-2611,Paid in Full,24,...,NaN,198845.86,"317 W 104th Ave., ANCHORAGE, AK","3111 'C' St, ANCHORAGE, AK",20200405,20210331,20210420,Nonclassifiable Establishments,Nonclassifiable Establishments,Nonclassifiable Establishments
2218,4678427701,1084,PPP,HALCYON DAYS LLC,41630 GLADYS COURT,HOMER,AK,99603,Paid in Full,24,...,NaN,162872.34,"41630 GLADYS COURT, HOMER, AK","101 N Philips Ave, SIOUX FALLS, SD",20200501,20211006,20211216,Nonclassifiable Establishments,Nonclassifiable Establishments,Nonclassifiable Establishments
3526,7212977105,459,PPP,"NEAL TECHNICAL INNOVATIONS, LLC",9101 Milton Jones Road,DAPHNE,AL,36526-6226,Paid in Full,24,...,NaN,1210597.27,"9101 Milton Jones Road, DAPHNE, AL","2510 14th St One Hancock Plz, GULFPORT, MS",20200414,20210317,20210406,Nonclassifiable Establishments,Nonclassifiable Establishments,Nonclassifiable Establishments
4702,5062267000,459,PPP,PAY SUITE LLC,611 Walnut Street,GADSDEN,AL,35901-4136,Paid in Full,24,...,NaN,663329.00,"611 Walnut Street, GADSDEN, AL","1912 Cherokee Ave SW, CULLMAN, AL",20200404,20201230,20210107,Nonclassifiable Establishments,Nonclassifiable Establishments,Nonclassifiable Establishments

In [16]:
ppp_df_23_merge.loc[ppp_df_23_merge["Industry"].isnull()]

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,NonProfit,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,Y,696677.49,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,NaN,NaN,NaN
36,4820397010,1084,PPP,"COLVILLE, INC.",4300 B Street,ANCHORAGE,AK,99503-5913,Paid in Full,24,...,NaN,3819960.24,"4300 B Street, ANCHORAGE, AK","3111 'C' St, ANCHORAGE, AK",20200404,20210611,20210720,NaN,NaN,NaN
260,6287537004,1084,PPP,SEWARD ASSOCIATION FOR THE ADVANCEMENT OF MARI...,301 Railway Avenue,SEWARD,AK,99664-3801,Paid in Full,24,...,NaN,1051530.90,"301 Railway Avenue, SEWARD, AK","3111 'C' St, ANCHORAGE, AK",20200406,20201103,20201217,NaN,NaN,NaN
305,1892977209,1084,PPP,DENALI VISIONS 3000,2211 Sunrise Dr,ANCHORAGE,AK,99508-3273,Paid in Full,24,...,NaN,974986.64,"2211 Sunrise Dr, ANCHORAGE, AK","101 W 36th Ave, ANCHORAGE, AK",20200415,20211214,20220106,NaN,NaN,NaN
429,5784067001,1084,PPP,TONGASS TRADING COMPANY,201 DOCK ST,KETCHIKAN,AK,99901-6407,Paid in Full,24,...,NaN,742358.88,"201 DOCK ST, KETCHIKAN, AK","2030 Sea level Dr Ste 300, KETCHIKAN, AK",20200406,20201105,20210129,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962807,6656547003,390,PPP,"TERRASIMCO, INC.",1016 Bedington Road,MARTINSBURG,WV,25404-7188,Paid in Full,24,...,NaN,182530.45,"1016 Bedington Road, MARTINSBURG, WV","101 S Washington St, BERKELEY SPRINGS, WV",20200407,20210107,20210219,NaN,NaN,NaN
962820,1885427101,390,PPP,MACATAC V INC,42 Chase Park,HURRICANE,WV,25526-7302,Paid in Full,24,...,NaN,181983.51,"42 Chase Park, HURRICANE, WV","138 Putnam St, MARIETTA, OH",20200410,20210310,20210421,NaN,NaN,NaN
963043,9665527700,390,PPP,CIG HIBACHI LLC,1 LIBERTY SQ,Hurricane,WV,25526,Paid in Full,24,...,NaN,168926.99,"1 LIBERTY SQ, Hurricane, WV","17 S High St., COLUMBUS, OH",20200501,20210125,20210224,NaN,NaN,NaN
964906,3960157702,897,PPP,TAURUS ENGINEERING AND CONTROL INC,190 PENDELL BLVD NO 1074,MILLS,WY,82644,Paid in Full,24,...,NaN,211957.42,"190 PENDELL BLVD NO 1074, MILLS, WY","101 N Philips Ave, SIOUX FALLS, SD",20200501,20210915,20211020,NaN,NaN,NaN
965262,3885147709,897,PPP,CONTRACTORS SUPPLY INC - GILLETTE,5005 ROURKE AVE,GILLETTE,WY,82718,Paid in Full,24,...,NaN,174901.89,"5005 ROURKE AVE, GILLETTE, WY","101 N Philips Ave, SIOUX FALLS, SD",20200501,20210608,20210714,NaN,NaN,NaN

In [17]:
ppp_df_23["Industry"] = ppp_df_23["Industry"].fillna("Not Available")
ppp_df_23["IndustrySubsector"] = ppp_df_23["IndustrySubsector"].fillna("Not Available")
ppp_df_23["LongName"] = ppp_df_23["LongName"].fillna("Not Available")
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,NonProfit,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,NaN,773553.37,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,NaN,746336.24,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,Y,696677.49,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,Not Available,Not Available,Not Available
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,NaN,395264.11,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,NaN,370819.35,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving

Null Check, Not Available after NAICS Null Formatting

In [18]:
print(ppp_df_23[ppp_df_23["Industry"] == 'Not Available'].shape[0])#12162 - 4078
print(ppp_df_23[ppp_df_23["Industry"] == 'Nonclassifiable Establishments'].shape[0])

8084
4078

<h4>SBA District Office Labeling

In [19]:
sba_xslx = pd.read_excel("../data/raw/SBA/SBAOfficeCodeLabels.xlsx", dtype=str, index_col=None)
sba_xslx.to_csv('../data/raw/SBA/SBAOfficeCodeLabels.csv', encoding='utf-8', index=False)
sba_df = pd.read_csv("../data/raw/SBA/SBAOfficeCodeLabels.csv")
sba_df.index = sba_df.index.astype('int64')
sba_df

    SBAOfficeCode                    SBAOfficeLabel
0             100         BOSTON REGIONAL OFFICE
1             101  MASSACHUSETTS DISTRICT OFFICE
2             130      SPRINGFIELD BRANCH OFFICE
3             150        VERMONT DISTRICT OFFICE
4             156    CONNECTICUT DISTRICT OFFICE
..            ...                               ...
89           1013        SEATTLE DISTRICT OFFICE
90           1084         ALASKA DISTRICT OFFICE
91           1086       PORTLAND DISTRICT OFFICE
92           1087          BOISE DISTRICT OFFICE
93           1094          SPOKANE BRANCH OFFICE

[94 rows x 2 columns]

In [20]:
ppp_df_23= ppp_df_23.merge(sba_df, on="SBAOfficeCode", how="left")
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ForgivenessAmount,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,773553.37,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,SOUTH CAROLINA DISTRICT OFFICE
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,746336.24,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,SOUTH CAROLINA DISTRICT OFFICE
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,696677.49,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,Not Available,Not Available,Not Available,SEATTLE DISTRICT OFFICE
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,395264.11,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,SANTA ANA DISTRICT OFFICE
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,370819.35,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,MASSACHUSETTS DISTRICT OFFICE

SBA District Office Labeling: Verification

In [21]:
ppp_df_23.loc[ppp_df_23["SBAOfficeLabel"].isnull()]

Empty DataFrame
Columns: [LoanNumber, SBAOfficeCode, ProcessingMethod, BorrowerName, BorrowerAddress, BorrowerCity, BorrowerState, BorrowerZip, LoanStatus, Term, SBAGuarantyPercentage, InitialApprovalAmount, CurrentApprovalAmount, UndisbursedAmount, FranchiseName, ServicingLenderLocationID, ServicingLenderName, ServicingLenderAddress, ServicingLenderCity, ServicingLenderState, ServicingLenderZip, RuralUrbanIndicator, HubzoneIndicator, LMIIndicator, BusinessAgeDescription, ProjectCity, ProjectCountyName, ProjectState, ProjectZip, CD, JobsReported, NAICSCode, Race, Ethnicity, UTILITIES_PROCEED, PAYROLL_PROCEED, MORTGAGE_INTEREST_PROCEED, RENT_PROCEED, REFINANCE_EIDL_PROCEED, HEALTH_CARE_PROCEED, DEBT_INTEREST_PROCEED, BusinessType, OriginatingLenderLocationID, OriginatingLender, OriginatingLenderCity, OriginatingLenderState, Gender, Veteran, NonProfit, ForgivenessAmount, FullAdd, ServicingLenderFullAddress, DateApprovedTS, ForgivenessDateTS, LoanStatusDateTS, Industry, IndustrySubsector, LongName, SBAOfficeLabel]
Index: []

[0 rows x 59 columns]

In [22]:
print(ppp_df_23['SBAOfficeLabel'].nunique())
print(ppp_df_23['SBAOfficeCode'].nunique())

74
75

<h4>Conditions

<b>Loan Approval Amount Ranges to Determine Lender Percent/Profit </b><br>
https://home.treasury.gov/system/files/136/PPP%20Lender%20Information%20Fact%20Sheet.pdf

In [23]:
loan_conditions = [
(ppp_df_23.CurrentApprovalAmount <= 350000) & (ppp_df_23.CurrentApprovalAmount >= 150000),
(ppp_df_23.CurrentApprovalAmount <= 2000000) & (ppp_df_23.CurrentApprovalAmount > 350000),
(ppp_df_23.CurrentApprovalAmount > 2000000)
]
loan_values = [.05,.03,.01]
ppp_df_23['LenderPercent'] = np.select(loan_conditions, loan_values)
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,FullAdd,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,"2410 Highway 15 South, Sumter, SC","1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,0.03
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,"7684 Southrail Road, North Charleston, SC","1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,SOUTH CAROLINA DISTRICT OFFICE,0.03
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,"1850 BOYER AVE E, SEATTLE, WA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,Not Available,Not Available,Not Available,SEATTLE DISTRICT OFFICE,0.03
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA","100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,SANTA ANA DISTRICT OFFICE,0.03
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,"Not Available, Not Available, Not Available","17 S High St., COLUMBUS, OH",20200501,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,MASSACHUSETTS DISTRICT OFFICE,0.03

<b>Determining Lender Profit based on Percent of Current Approval

In [24]:
ppp_df_23["EstimatedLenderProfit"] = ppp_df_23['CurrentApprovalAmount'] * ppp_df_23['LenderPercent']
ppp_df_23["EstimatedLenderProfit"] = ppp_df_23["EstimatedLenderProfit"].apply(lambda x: '{:.2f}'.format(x) if type(x) is int or type(x) is float else x)
ppp_df_23['LenderPercent'] = pd.Series(["{0:.0f}%".format(val * 100) for val in ppp_df_23['LenderPercent']], index = ppp_df_23.index)
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ServicingLenderFullAddress,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,"1148 Broadway, COLUMBUS, GA",20200501,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,3%,23080.76
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,"1148 Broadway, COLUMBUS, GA",20200501,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,SOUTH CAROLINA DISTRICT OFFICE,3%,22107.83
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,"100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210210,20210317,Not Available,Not Available,Not Available,SEATTLE DISTRICT OFFICE,3%,20740.65
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,"100 N Tryon St, Ste 170, CHARLOTTE, NC",20200501,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,SANTA ANA DISTRICT OFFICE,3%,14996.13
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,"17 S High St., COLUMBUS, OH",20200501,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,MASSACHUSETTS DISTRICT OFFICE,3%,11023.11

<b>Determining Approval Ranges for Each Loan

In [25]:
loan_conditions = [
(ppp_df_23.CurrentApprovalAmount <= 350000) & (ppp_df_23.CurrentApprovalAmount >= 150000),
(ppp_df_23.CurrentApprovalAmount <= 1000000) & (ppp_df_23.CurrentApprovalAmount > 350000),
(ppp_df_23.CurrentApprovalAmount <= 2000000) & (ppp_df_23.CurrentApprovalAmount > 1000000),
(ppp_df_23.CurrentApprovalAmount <= 5000000) & (ppp_df_23.CurrentApprovalAmount > 2000000),
(ppp_df_23.CurrentApprovalAmount <= 10000000) & (ppp_df_23.CurrentApprovalAmount > 5000000),  
]
loan_values = ["a $150,000-350,000","b $350,000-1 million", "c $1-2 million","d $2-5 million", "e $5-10 million"]
ppp_df_23['LoanRange'] = np.select(loan_conditions, loan_values)
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,DateApprovedTS,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit,LoanRange
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,20200501,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,3%,23080.76,"b $350,000-1 million"
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,20200501,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,SOUTH CAROLINA DISTRICT OFFICE,3%,22107.83,"b $350,000-1 million"
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,20200501,20210210,20210317,Not Available,Not Available,Not Available,SEATTLE DISTRICT OFFICE,3%,20740.65,"b $350,000-1 million"
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,20200501,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,SANTA ANA DISTRICT OFFICE,3%,14996.13,"b $350,000-1 million"
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,20200501,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,MASSACHUSETTS DISTRICT OFFICE,3%,11023.11,"b $350,000-1 million"

<b>Determining Job Report Ranges for Each Loan

JobsReported Formatting

In [26]:
ppp_df_23.loc[ppp_df_23["JobsReported"] == "0", 'JobsReported'] = 0
ppp_df_23.loc[ppp_df_23["JobsReported"].isnull(), 'JobsReported'] = 0
ppp_df_23['JobsReported']=ppp_df_23['JobsReported'].astype(int)

https://data.bls.gov/cew/apps/data_views/data_views.htm#tab=Tables

In [27]:
job_conditions = [
(ppp_df_23.JobsReported <= 5),
(ppp_df_23.JobsReported <= 9) & (ppp_df_23.JobsReported > 5),
(ppp_df_23.JobsReported <= 19) & (ppp_df_23.JobsReported > 9),
(ppp_df_23.JobsReported <= 49) & (ppp_df_23.JobsReported > 19),
(ppp_df_23.JobsReported <= 99) & (ppp_df_23.JobsReported > 49), 
(ppp_df_23.JobsReported <= 249) & (ppp_df_23.JobsReported > 99),
(ppp_df_23.JobsReported <= 499) & (ppp_df_23.JobsReported > 249),
(ppp_df_23.JobsReported > 499)
]
job_values = ["Fewer than 5","5 to 9", "10 to 19","20 to 49", "50 to 99", "100 to 249", "250 to 499", "500 or more"]
ppp_df_23['JobRange'] = np.select(job_conditions, job_values)
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit,LoanRange,JobRange
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,3%,23080.76,"b $350,000-1 million",50 to 99
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,SOUTH CAROLINA DISTRICT OFFICE,3%,22107.83,"b $350,000-1 million",50 to 99
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,20210210,20210317,Not Available,Not Available,Not Available,SEATTLE DISTRICT OFFICE,3%,20740.65,"b $350,000-1 million",50 to 99
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,SANTA ANA DISTRICT OFFICE,3%,14996.13,"b $350,000-1 million",20 to 49
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,MASSACHUSETTS DISTRICT OFFICE,3%,11023.11,"b $350,000-1 million",20 to 49

In [28]:
ppp_df_23['JobRange'].value_counts()

JobRange
20 to 49        416149
10 to 19        241148
50 to 99        161163
100 to 249       84575
5 to 9           31080
250 to 499       21987
Fewer than 5      5093
500 or more       4357
Name: count, dtype: int64

In [29]:
ppp_df_23.loc[ppp_df_23["JobRange"] == "0", 'JobRange'] = "Fewer than 5"
ppp_df_23['JobRange'].value_counts()

JobRange
20 to 49        416149
10 to 19        241148
50 to 99        161163
100 to 249       84575
5 to 9           31080
250 to 499       21987
Fewer than 5      5093
500 or more       4357
Name: count, dtype: int64

In [30]:
ppp_df_23['JobRange'].isnull().sum() #check

0

<h4>Naming Consistency

<b>Naming Consistency: Business Age, Type

Counts

In [31]:
listbusiness =ppp_df_23["BusinessType"].value_counts()
listbusiness

BusinessType
Corporation                            415684
Limited  Liability Company(LLC)        261058
Subchapter S Corporation               174799
Non-Profit Organization                 55904
Partnership                             18158
Limited Liability Partnership           12724
Sole Proprietorship                     12255
Professional Association                 6270
Cooperative                              2435
501(c)3 – Non Profit                     1772
Non-Profit Childcare Center               900
501(c)6 – Non Profit Membership           762
Employee Stock Ownership Plan(ESOP)       641
Self-Employed Individuals                 494
Trust                                     397
Housing Co-op                             152
Joint Venture                             125
Independent Contractors                   112
Single Member LLC                          78
Tribal Concerns                            64
Tenant in Common                           30
501(c) – Non Profit except 3,4,6,          10
Rollover as Business Start-Ups (ROB         4
501(c)19 – Non Profit Veterans              2
Qualified Joint-Venture (spouses)           2
Name: count, dtype: int64

In [32]:
listbusinessage =ppp_df_23['BusinessAgeDescription'].value_counts()
listbusinessage

BusinessAgeDescription
Existing or more than 2 years old         859324
New Business or 2 years or less            54479
Unanswered                                 51051
Change of Ownership                          422
Startup, Loan Funds will Open Business       275
Name: count, dtype: int64

Updates

In [33]:
ppp_df_23["BusinessType"] = ppp_df_23["BusinessType"].replace({'Limited  Liability Company(LLC)': 'Limited Liability Company(LLC)'}) #extra space in text

ppp_df_23.loc[ppp_df_23['BusinessAgeDescription'] == 'Unanswered', 'BusinessAgeDescription'] = 'Not Available'

ppp_df_23['BusinessAgeDescription'] = ppp_df_23['BusinessAgeDescription'].fillna('Not Available')
ppp_df_23["BusinessType"] = ppp_df_23["BusinessType"].fillna('Not Available')
ppp_df_23["FranchiseName"] = ppp_df_23["FranchiseName"].fillna('Not Available')
ppp_df_23.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit,LoanRange,JobRange
0,9547507704,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,29150-9662,Paid in Full,24,...,20201120,20201218,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,3%,23080.76,"b $350,000-1 million",50 to 99
1,9777677704,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,29420-9000,Paid in Full,24,...,20210812,20210928,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,SOUTH CAROLINA DISTRICT OFFICE,3%,22107.83,"b $350,000-1 million",50 to 99
2,5791407702,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,98112-2922,Paid in Full,24,...,20210210,20210317,Not Available,Not Available,Not Available,SEATTLE DISTRICT OFFICE,3%,20740.65,"b $350,000-1 million",50 to 99
3,6223567700,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,92407-1740,Paid in Full,24,...,20210910,20211016,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,SANTA ANA DISTRICT OFFICE,3%,14996.13,"b $350,000-1 million",20 to 49
4,9662437702,101,PPP,AERO BOX LLC,Not Available,Not Available,Not Available,NaN,Paid in Full,24,...,20210408,20210817,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,MASSACHUSETTS DISTRICT OFFICE,3%,11023.11,"b $350,000-1 million",20 to 49

Verification

In [34]:
listbusiness =ppp_df_23["BusinessType"].value_counts()
listbusiness

BusinessType
Corporation                            415684
Limited Liability Company(LLC)         261058
Subchapter S Corporation               174799
Non-Profit Organization                 55904
Partnership                             18158
Limited Liability Partnership           12724
Sole Proprietorship                     12255
Professional Association                 6270
Cooperative                              2435
501(c)3 – Non Profit                     1772
Non-Profit Childcare Center               900
501(c)6 – Non Profit Membership           762
Not Available                             720
Employee Stock Ownership Plan(ESOP)       641
Self-Employed Individuals                 494
Trust                                     397
Housing Co-op                             152
Joint Venture                             125
Independent Contractors                   112
Single Member LLC                          78
Tribal Concerns                            64
Tenant in Common                           30
501(c) – Non Profit except 3,4,6,          10
Rollover as Business Start-Ups (ROB         4
501(c)19 – Non Profit Veterans              2
Qualified Joint-Venture (spouses)           2
Name: count, dtype: int64

In [35]:
listbusinessage =ppp_df_23['BusinessAgeDescription'].value_counts()
listbusinessage

BusinessAgeDescription
Existing or more than 2 years old         859324
New Business or 2 years or less            54479
Not Available                              51052
Change of Ownership                          422
Startup, Loan Funds will Open Business       275
Name: count, dtype: int64

<b>Naming Consistency: NonProfit

In [36]:
listnonprofit = ppp_df_23["NonProfit"].value_counts()
listnonprofit

NonProfit
Y    59350
Name: count, dtype: int64

Updates

In [37]:
ppp_df_23["NonProfit"] = ppp_df_23["NonProfit"].fillna('N')

Verification

Verify that all NonProfits = Y have listed NonProfit as BusinessType<br>

In [38]:
nonprofit_yes = ppp_df_23.loc[ppp_df_23["NonProfit"] == "Y"]
nonprofit_yes["BusinessType"].value_counts()

BusinessType
Non-Profit Organization              55904
501(c)3 – Non Profit                  1772
Non-Profit Childcare Center            900
501(c)6 – Non Profit Membership        762
501(c) – Non Profit except 3,4,6,       10
501(c)19 – Non Profit Veterans           2
Name: count, dtype: int64

Verify that all NonProfits = N do not have NonProfit as BusinessType<br>

In [39]:
nonprofit_no= ppp_df_23.loc[ppp_df_23["NonProfit"] == "N"]
nonprofit_no["BusinessType"].value_counts()

BusinessType
Corporation                            415684
Limited Liability Company(LLC)         261058
Subchapter S Corporation               174799
Partnership                             18158
Limited Liability Partnership           12724
Sole Proprietorship                     12255
Professional Association                 6270
Cooperative                              2435
Not Available                             720
Employee Stock Ownership Plan(ESOP)       641
Self-Employed Individuals                 494
Trust                                     397
Housing Co-op                             152
Joint Venture                             125
Independent Contractors                   112
Single Member LLC                          78
Tribal Concerns                            64
Tenant in Common                           30
Rollover as Business Start-Ups (ROB         4
Qualified Joint-Venture (spouses)           2
Name: count, dtype: int64

<b>Naming Consistency: Borrower Name

Check: &AMP;

In [40]:
cleanamp_check = ppp_df_23[ppp_df_23['BorrowerName'].astype(str).str.contains("&AMP;")]
cleanamp_check.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit,LoanRange,JobRange
56,6570687706,1084,PPP,AHTNA CONSTRUCTION &AMP; PRIMARY PRODUCTS COMP...,110 W 38th Ave Ste 100,Anchorage,AK,99503,Paid in Full,24,...,20211119,20211216,Construction,"2373 Highway, Street, and Bridge Construction","Highway, Street, and Bridge Construction",ALASKA DISTRICT OFFICE,1%,27555.87,d $2-5 million,100 to 249
1876,6707308401,1084,PPS,ALLURE DAY SPA &AMP; HAIR DESIGN LLC.,142 W 5th Ave,Anchorage,AK,99501-2522,Paid in Full,60,...,20211025,20211103,Other Services (except Public Administration),8121 Personal Care Services,Other Personal Care Services,ALASKA DISTRICT OFFICE,5%,10357.50,"a $150,000-350,000",20 to 49
2361,2556438507,1084,PPS,360 CONSTRUCTION &AMP; DESIGN LLC FKA TRAILBO...,3330 C St Ste 100,Anchorage,AK,99503-3957,Paid in Full,60,...,20220113,20220131,Construction,2361 Residential Building Construction,Residential Remodelers,ALASKA DISTRICT OFFICE,5%,8405.95,"a $150,000-350,000",10 to 19
2425,3840357709,1084,PPP,FRAMPTON &AMP; OPINSKY LLC,2525 BLUEBERRY ROAD SUITE 204,ANCHORAGE,AK,99503,Paid in Full,24,...,20210525,20210610,Real Estate and Rental and Leasing,5312 Offices of Real Estate Agents and Brokers,Offices of Real Estate Agents and Brokers,ALASKA DISTRICT OFFICE,5%,8218.60,"a $150,000-350,000",10 to 19
4861,9610747710,459,PPP,R &AMP; D ELECTRONICS INC,5501 Hwy 431 S,Brownsboro,AL,35741-9772,Paid in Full,24,...,20201125,20201218,Manufacturing,3312 Steel Product Manufacturing from Purchase...,Steel Wire Drawing,ALABAMA DISTRICT OFFICE,3%,18650.50,"b $350,000-1 million",50 to 99

Update & Verify I: &

In [41]:
ppp_df_23['BorrowerName']=ppp_df_23['BorrowerName'].astype(str).str.replace('&AMP;', '&', regex=True)
cleanamp_verify = ppp_df_23[ppp_df_23['BorrowerName'].astype(str).str.contains("&AMP;")]
cleanamp_verify

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit,LoanRange,JobRange
806347,9712177706,474,PPP,COMPLETE WELDING &AMP; FABRICATION INC,112 E INDUSTRIAL PARK DR,JACKSBORO,TN,37757,Paid in Full,24,...,20201103,20201216,Other Services (except Public Administration),8113 Commercial and Industrial Machinery and E...,Commercial and Industrial Machinery and Equipm...,TENNESSEE DISTRICT OFFICE,5%,8375.00,"a $150,000-350,000",20 to 49

Update & Verify II: &

In [42]:
ppp_df_23.loc[ppp_df_23["LoanNumber"] == 9712177706, 'BorrowerName'] = "COMPLETE WELDING & FABRICATION INC"
cleanamp_verify = ppp_df_23[ppp_df_23['BorrowerName'].astype(str).str.contains("&AMP;")]
cleanamp_verify

Empty DataFrame
Columns: [LoanNumber, SBAOfficeCode, ProcessingMethod, BorrowerName, BorrowerAddress, BorrowerCity, BorrowerState, BorrowerZip, LoanStatus, Term, SBAGuarantyPercentage, InitialApprovalAmount, CurrentApprovalAmount, UndisbursedAmount, FranchiseName, ServicingLenderLocationID, ServicingLenderName, ServicingLenderAddress, ServicingLenderCity, ServicingLenderState, ServicingLenderZip, RuralUrbanIndicator, HubzoneIndicator, LMIIndicator, BusinessAgeDescription, ProjectCity, ProjectCountyName, ProjectState, ProjectZip, CD, JobsReported, NAICSCode, Race, Ethnicity, UTILITIES_PROCEED, PAYROLL_PROCEED, MORTGAGE_INTEREST_PROCEED, RENT_PROCEED, REFINANCE_EIDL_PROCEED, HEALTH_CARE_PROCEED, DEBT_INTEREST_PROCEED, BusinessType, OriginatingLenderLocationID, OriginatingLender, OriginatingLenderCity, OriginatingLenderState, Gender, Veteran, NonProfit, ForgivenessAmount, FullAdd, ServicingLenderFullAddress, DateApprovedTS, ForgivenessDateTS, LoanStatusDateTS, Industry, IndustrySubsector, LongName, SBAOfficeLabel, LenderPercent, EstimatedLenderProfit, LoanRange, JobRange]
Index: []

[0 rows x 63 columns]

Check: SBA SMALL 7A TERM

In [43]:
cleansba_check = ppp_df_23[ppp_df_23['BorrowerName'].astype(str).str.contains("SBA SMALL 7A TERM")]
cleansba_check.head()

,LoanNumber,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatus,Term,...,ForgivenessDateTS,LoanStatusDateTS,Industry,IndustrySubsector,LongName,SBAOfficeLabel,LenderPercent,EstimatedLenderProfit,LoanRange,JobRange
30443,3513127702,988,PPP,SOUTHWEST PRIVATE INVESTMENTS LLC-SBA SMALL 7A...,2728 N 24TH STREET,PHOENIX,AZ,85008,Charged Off,0,...,Not Available,20211120,Not Available,Not Available,Not Available,ARIZONA DISTRICT OFFICE,5%,10625.00,"a $150,000-350,000",10 to 19
186221,3321607710,156,PPP,BRISTOL HOTEL LLC-SBA SMALL 7A TERM,42 Century Drive,Bristol,CT,06010,Paid in Full,24,...,20210802,20211221,Not Available,Not Available,Not Available,CONNECTICUT DISTRICT OFFICE,3%,21124.38,"b $350,000-1 million",10 to 19
186938,4202817705,156,PPP,ATLANTIC MASONRY PRODUCTS CORP-SBA SMALL 7A TERM,67 Quinnipiac Ave.,"North Haven ,",CT,06473,Paid in Full,24,...,20210615,20210723,Not Available,Not Available,Not Available,CONNECTICUT DISTRICT OFFICE,3%,17173.38,"b $350,000-1 million",10 to 19
186985,4249147702,156,PPP,MACKENZIE RESTORATION COMPANY LLC-SBA SMALL 7A...,4 Carlton Street,Fairfield,CT,06824,Paid in Full,24,...,20210628,20210722,Not Available,Not Available,Not Available,CONNECTICUT DISTRICT OFFICE,3%,16963.71,"b $350,000-1 million",10 to 19
187477,4190277700,156,PPP,CENTRAL CONNECTICUT ACOUSTICS INC-SBA SMALL 7A...,105 north cherry street,wallingford,CT,06492,Paid in Full,24,...,20210331,20210630,Construction,2383 Building Finishing Contractors,Drywall and Insulation Contractors,CONNECTICUT DISTRICT OFFICE,3%,15000.00,"b $350,000-1 million",20 to 49

Update & Verify: SBA SMALL 7A TERM

In [44]:
ppp_df_23['BorrowerName']=ppp_df_23['BorrowerName'].astype(str).str.replace('SBA SMALL 7A TERM', '', regex=True)
cleansba_verify = ppp_df_23[ppp_df_23['BorrowerName'].astype(str).str.contains("SBA SMALL 7A TERM")]
cleansba_verify

Empty DataFrame
Columns: [LoanNumber, SBAOfficeCode, ProcessingMethod, BorrowerName, BorrowerAddress, BorrowerCity, BorrowerState, BorrowerZip, LoanStatus, Term, SBAGuarantyPercentage, InitialApprovalAmount, CurrentApprovalAmount, UndisbursedAmount, FranchiseName, ServicingLenderLocationID, ServicingLenderName, ServicingLenderAddress, ServicingLenderCity, ServicingLenderState, ServicingLenderZip, RuralUrbanIndicator, HubzoneIndicator, LMIIndicator, BusinessAgeDescription, ProjectCity, ProjectCountyName, ProjectState, ProjectZip, CD, JobsReported, NAICSCode, Race, Ethnicity, UTILITIES_PROCEED, PAYROLL_PROCEED, MORTGAGE_INTEREST_PROCEED, RENT_PROCEED, REFINANCE_EIDL_PROCEED, HEALTH_CARE_PROCEED, DEBT_INTEREST_PROCEED, BusinessType, OriginatingLenderLocationID, OriginatingLender, OriginatingLenderCity, OriginatingLenderState, Gender, Veteran, NonProfit, ForgivenessAmount, FullAdd, ServicingLenderFullAddress, DateApprovedTS, ForgivenessDateTS, LoanStatusDateTS, Industry, IndustrySubsector, LongName, SBAOfficeLabel, LenderPercent, EstimatedLenderProfit, LoanRange, JobRange]
Index: []

[0 rows x 63 columns]

<b>Remove Leading / Trailing Whitespaces from string columns

In [45]:
beforetrails = ppp_df_23.loc[ppp_df_23["Industry"] == "Utilities"]
beforetrails["IndustrySubsector"].sort_values().unique().tolist()

['2211 Electric Power Generation, Transmission and Distribution',
 '2212 Natural Gas Distribution ',
 '2213 Water, Sewage and Other Systems ']

In [46]:
ppp_df_23 = ppp_df_23.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [47]:
aftertrails = ppp_df_23.loc[ppp_df_23["Industry"] == "Utilities"]
aftertrails["IndustrySubsector"].sort_values().unique().tolist()

['2211 Electric Power Generation, Transmission and Distribution',
 '2212 Natural Gas Distribution',
 '2213 Water, Sewage and Other Systems']

<h4>DataFrame Finalization

Final Null, Dtype Check

In [48]:
pd.set_option('display.max_rows', 70)
print(ppp_df_23.isnull().sum())

LoanNumber                          0
SBAOfficeCode                       0
ProcessingMethod                    0
BorrowerName                        0
BorrowerAddress                     0
BorrowerCity                        0
BorrowerState                       0
BorrowerZip                        13
LoanStatus                          0
Term                                0
SBAGuarantyPercentage               0
InitialApprovalAmount               0
CurrentApprovalAmount               0
UndisbursedAmount                   0
FranchiseName                       0
ServicingLenderLocationID           0
ServicingLenderName                 0
ServicingLenderAddress              0
ServicingLenderCity                 0
ServicingLenderState                0
ServicingLenderZip                  0
RuralUrbanIndicator                 0
HubzoneIndicator                    0
LMIIndicator                        0
BusinessAgeDescription              0
ProjectCity                        13
ProjectCountyName                  57
ProjectState                        9
ProjectZip                         14
CD                                 46
JobsReported                        0
NAICSCode                           0
Race                                0
Ethnicity                           0
UTILITIES_PROCEED              627203
PAYROLL_PROCEED                  1827
MORTGAGE_INTEREST_PROCEED      920028
RENT_PROCEED                   866328
REFINANCE_EIDL_PROCEED         942704
HEALTH_CARE_PROCEED            908126
DEBT_INTEREST_PROCEED          933856
BusinessType                        0
OriginatingLenderLocationID         0
OriginatingLender                   0
OriginatingLenderCity               0
OriginatingLenderState              0
Gender                              0
Veteran                             0
NonProfit                           0
ForgivenessAmount                   0
FullAdd                             0
ServicingLenderFullAddress          0
DateApprovedTS                      0
ForgivenessDateTS                   0
LoanStatusDateTS                    0
Industry                            0
IndustrySubsector                   0
LongName                            0
SBAOfficeLabel                      0
LenderPercent                       0
EstimatedLenderProfit               0
LoanRange                           0
JobRange                            0
dtype: int64

In [49]:
ppp_df_23.dtypes

LoanNumber                       int64
SBAOfficeCode                    int64
ProcessingMethod                object
BorrowerName                    object
BorrowerAddress                 object
BorrowerCity                    object
BorrowerState                   object
BorrowerZip                     object
LoanStatus                      object
Term                             int64
SBAGuarantyPercentage            int64
InitialApprovalAmount          float64
CurrentApprovalAmount          float64
UndisbursedAmount              float64
FranchiseName                   object
ServicingLenderLocationID        int64
ServicingLenderName             object
ServicingLenderAddress          object
ServicingLenderCity             object
ServicingLenderState            object
ServicingLenderZip              object
RuralUrbanIndicator             object
HubzoneIndicator                object
LMIIndicator                    object
BusinessAgeDescription          object
ProjectCity                     object
ProjectCountyName               object
ProjectState                    object
ProjectZip                      object
CD                              object
JobsReported                     int64
NAICSCode                        int64
Race                            object
Ethnicity                       object
UTILITIES_PROCEED              float64
PAYROLL_PROCEED                float64
MORTGAGE_INTEREST_PROCEED      float64
RENT_PROCEED                   float64
REFINANCE_EIDL_PROCEED         float64
HEALTH_CARE_PROCEED            float64
DEBT_INTEREST_PROCEED          float64
BusinessType                    object
OriginatingLenderLocationID      int64
OriginatingLender               object
OriginatingLenderCity           object
OriginatingLenderState          object
Gender                          object
Veteran                         object
NonProfit                       object
ForgivenessAmount              float64
FullAdd                         object
ServicingLenderFullAddress      object
DateApprovedTS                   int64
ForgivenessDateTS               object
LoanStatusDateTS                object
Industry                        object
IndustrySubsector               object
LongName                        object
SBAOfficeLabel                  object
LenderPercent                   object
EstimatedLenderProfit           object
LoanRange                       object
JobRange                        object
dtype: object

In [50]:
pd.reset_option('display.max_rows', silent=True)

<b>Determining Necessary Columns<br></b>
<h6>Drop Columns that would provide inconclusive analysis results based on significant Null Count<br>
*potential for filter to be added based on these attributes at later time

In [51]:
#keep track of columns removed
removed = ['BorrowerAddress', 'BorrowerCity', 'BorrowerZip', 'SBAGuarantyPercentage', 'InitialApprovalAmount', 'FranchiseName',
 'BusinessAgeDescription', 'ProjectCity','ProjectCountyName', 'ProjectState', 'ProjectZip','Race', 'Ethnicity', 'ServicingLenderAddress', 'ServicingLenderCity', 'ServicingLenderState', 'ServicingLenderZip', 
 'UTILITIES_PROCEED', 'PAYROLL_PROCEED', 'MORTGAGE_INTEREST_PROCEED', 'RENT_PROCEED', 'REFINANCE_EIDL_PROCEED', 'DateApproved_ts', 'ForgivenessDate_ts',
 'HEALTH_CARE_PROCEED','DEBT_INTEREST_PROCEED', 'Gender', 'Veteran', 'NA', '4DigitNAICS','TRIIndustrySector']

cols =['LoanNumber','DateApprovedTS','SBAOfficeCode','ProcessingMethod','BorrowerName','BorrowerState',
       'LoanStatusDateTS','LoanStatus','Term','CurrentApprovalAmount','UndisbursedAmount', 
       'ServicingLenderLocationID','ServicingLenderName','ServicingLenderState',
       'RuralUrbanIndicator','HubzoneIndicator','LMIIndicator','BusinessAgeDescription','CD','JobsReported', 
       'NAICSCode','BusinessType','OriginatingLenderLocationID','OriginatingLender', 'OriginatingLenderCity', 'OriginatingLenderState',
       'NonProfit', 'ForgivenessAmount', 'ForgivenessDateTS',
       'SBAOfficeLabel', 'ServicingLenderFullAddress','LenderPercent', 'EstimatedLenderProfit', 
       'LoanRange', 'JobRange','Industry', 'IndustrySubsector','LongName', 'FullAdd'] #39

ppp_df_23 = ppp_df_23[cols]
ppp_df_23.head()

,LoanNumber,DateApprovedTS,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerState,LoanStatusDateTS,LoanStatus,Term,CurrentApprovalAmount,...,SBAOfficeLabel,ServicingLenderFullAddress,LenderPercent,EstimatedLenderProfit,LoanRange,JobRange,Industry,IndustrySubsector,LongName,FullAdd
0,9547507704,20200501,464,PPP,"SUMTER COATINGS, INC.",SC,20201218,Paid in Full,24,769358.78,...,SOUTH CAROLINA DISTRICT OFFICE,"1148 Broadway, COLUMBUS, GA",3%,23080.76,"b $350,000-1 million",50 to 99,Manufacturing,"3255 Paint, Coating, and Adhesive Manufacturing",Paint and Coating Manufacturing,"2410 Highway 15 South, Sumter, SC"
1,9777677704,20200501,464,PPP,"PLEASANT PLACES, INC.",SC,20210928,Paid in Full,24,736927.79,...,SOUTH CAROLINA DISTRICT OFFICE,"1148 Broadway, COLUMBUS, GA",3%,22107.83,"b $350,000-1 million",50 to 99,Administrative and Support and Waste Managemen...,5617 Services to Buildings and Dwellings,Landscaping Services,"7684 Southrail Road, North Charleston, SC"
2,5791407702,20200501,1013,PPP,BOYER CHILDREN'S CLINIC,WA,20210317,Paid in Full,24,691355.00,...,SEATTLE DISTRICT OFFICE,"100 N Tryon St, Ste 170, CHARLOTTE, NC",3%,20740.65,"b $350,000-1 million",50 to 99,Not Available,Not Available,Not Available,"1850 BOYER AVE E, SEATTLE, WA"
3,6223567700,20200501,920,PPP,KIRTLEY CONSTRUCTION INC,CA,20211016,Paid in Full,24,499871.00,...,SANTA ANA DISTRICT OFFICE,"100 N Tryon St, Ste 170, CHARLOTTE, NC",3%,14996.13,"b $350,000-1 million",20 to 49,Construction,2361 Residential Building Construction,New Single-Family Housing Construction (except...,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,9662437702,20200501,101,PPP,AERO BOX LLC,Not Available,20210817,Paid in Full,24,367437.00,...,MASSACHUSETTS DISTRICT OFFICE,"17 S High St., COLUMBUS, OH",3%,11023.11,"b $350,000-1 million",20 to 49,Transportation and Warehousing,4842 Specialized Freight Trucking,Used Household and Office Goods Moving,"Not Available, Not Available, Not Available"

In [52]:
ppp_df_23.to_csv("../data/ppp_pipe23.csv")

<b>Pipeline IN/OUT comp

In [53]:
csv_path = "../data/raw/>150K/public_150k_plus_230630.csv"
ppp_df_23raw = pd.read_csv(csv_path)
print(set(ppp_df_23raw.columns).symmetric_difference(ppp_df_23.columns))

{'LoanStatusDateTS', 'BorrowerAddress', 'Veteran', 'ServicingLenderCity', 'Industry', 'UTILITIES_PROCEED', 'HEALTH_CARE_PROCEED', 'LenderPercent', 'EstimatedLenderProfit', 'RENT_PROCEED', 'ProjectCountyName', 'Ethnicity', 'Gender', 'ForgivenessDateTS', 'DEBT_INTEREST_PROCEED', 'LoanRange', 'ForgivenessDate', 'IndustrySubsector', 'MORTGAGE_INTEREST_PROCEED', 'JobRange', 'FranchiseName', 'Race', 'ProjectCity', 'SBAOfficeLabel', 'ProjectState', 'BorrowerZip', 'ServicingLenderFullAddress', 'ServicingLenderZip', 'PAYROLL_PROCEED', 'ServicingLenderAddress', 'DateApproved', 'DateApprovedTS', 'REFINANCE_EIDL_PROCEED', 'LoanStatusDate', 'LongName', 'ProjectZip', 'SBAGuarantyPercentage', 'FullAdd', 'BorrowerCity', 'InitialApprovalAmount'}

In [54]:
nullraw = ppp_df_23raw.isnull().sum()
nullraw_df = pd.DataFrame({"column": nullraw.index, "nulls_r": nullraw.values})

typesraw = ppp_df_23raw.dtypes
typesraw_df = pd.DataFrame({"column": typesraw.index, "dtype_r": typesraw.values})

rawnulltypes = nullraw_df.merge(typesraw_df, on="column", how="left")
rawnulltypes

                         column  nulls_r  dtype_r
0                    LoanNumber        0    int64
1                  DateApproved        0   object
2                 SBAOfficeCode        0    int64
3              ProcessingMethod        0   object
4                  BorrowerName        4   object
5               BorrowerAddress       14   object
6                  BorrowerCity       12   object
7                 BorrowerState       13   object
8                   BorrowerZip       13   object
9                LoanStatusDate    16825   object
10                   LoanStatus        0   object
11                         Term        0    int64
12        SBAGuarantyPercentage        0    int64
13        InitialApprovalAmount        0  float64
14        CurrentApprovalAmount        0  float64
15            UndisbursedAmount       46  float64
16                FranchiseName   930147   object
17    ServicingLenderLocationID        0    int64
18          ServicingLenderName        0   object
19       ServicingLenderAddress        0   object
20          ServicingLenderCity        0   object
21         ServicingLenderState        0   object
22           ServicingLenderZip        0   object
23          RuralUrbanIndicator        0   object
24             HubzoneIndicator        0   object
25                 LMIIndicator        0   object
26       BusinessAgeDescription        1   object
27                  ProjectCity       13   object
28            ProjectCountyName       57   object
29                 ProjectState        9   object
30                   ProjectZip       14   object
31                           CD       46   object
32                 JobsReported        1  float64
33                    NAICSCode     6628  float64
34                         Race        0   object
35                    Ethnicity        0   object
36            UTILITIES_PROCEED   627203  float64
37              PAYROLL_PROCEED     1827  float64
38    MORTGAGE_INTEREST_PROCEED   920028  float64
39                 RENT_PROCEED   866328  float64
40       REFINANCE_EIDL_PROCEED   942704  float64
41          HEALTH_CARE_PROCEED   908126  float64
42        DEBT_INTEREST_PROCEED   933856  float64
43                 BusinessType      720   object
44  OriginatingLenderLocationID        0    int64
45            OriginatingLender        0   object
46        OriginatingLenderCity        0   object
47       OriginatingLenderState        0   object
48                       Gender        0   object
49                      Veteran        0   object
50                    NonProfit   906202   object
51            ForgivenessAmount    26515  float64
52              ForgivenessDate    26515   object

In [55]:
nullpipe = ppp_df_23.isnull().sum()
nullpipe_df = pd.DataFrame({"column": nullpipe.index, "nulls_r": nullpipe.values})

typespipe = ppp_df_23.dtypes
typespipe_df = pd.DataFrame({"column": typespipe.index, "dtype_r": typespipe.values})

piped_nulltypes = nullpipe_df.merge(typespipe_df, on="column", how="left")
piped_nulltypes

                         column  nulls_r  dtype_r
0                    LoanNumber        0    int64
1                DateApprovedTS        0    int64
2                 SBAOfficeCode        0    int64
3              ProcessingMethod        0   object
4                  BorrowerName        0   object
5                 BorrowerState        0   object
6              LoanStatusDateTS        0   object
7                    LoanStatus        0   object
8                          Term        0    int64
9         CurrentApprovalAmount        0  float64
10            UndisbursedAmount        0  float64
11    ServicingLenderLocationID        0    int64
12          ServicingLenderName        0   object
13         ServicingLenderState        0   object
14          RuralUrbanIndicator        0   object
15             HubzoneIndicator        0   object
16                 LMIIndicator        0   object
17       BusinessAgeDescription        0   object
18                           CD       46   object
19                 JobsReported        0    int64
20                    NAICSCode        0    int64
21                 BusinessType        0   object
22  OriginatingLenderLocationID        0    int64
23            OriginatingLender        0   object
24        OriginatingLenderCity        0   object
25       OriginatingLenderState        0   object
26                    NonProfit        0   object
27            ForgivenessAmount        0  float64
28            ForgivenessDateTS        0   object
29               SBAOfficeLabel        0   object
30   ServicingLenderFullAddress        0   object
31                LenderPercent        0   object
32        EstimatedLenderProfit        0   object
33                    LoanRange        0   object
34                     JobRange        0   object
35                     Industry        0   object
36            IndustrySubsector        0   object
37                     LongName        0   object
38                      FullAdd        0   object