In [1]:
import requests
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

<b>Merge Pipe to Current Geo

In [2]:
geo_path = "../../data/state_data/geo/ppp_geo.csv" #data as of 11/21/21
ppp_geo= pd.read_csv(geo_path)
ppp_geo.head()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (72) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
0,0,0,0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",...,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255.0,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",33.853682,-80.369867,NaN
1,1,1,1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",...,999 Other,5617 Services to Buildings and Dwellings,5617.0,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",32.942332,-80.066165,NaN
2,2,2,2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,...,NaN,NaN,NaN,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",47.636067,-122.302559,NaN
3,3,3,3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,...,999 Other,2361 Residential Building Construction,2361.0,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",34.224719,-117.372550,NaN
4,4,4,4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,...,999 Other,4842 Specialized Freight Trucking,4842.0,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",42.521828,-82.913680,NaN

In [3]:
ppp_geonull=ppp_geo.loc[ppp_geo["Lat"].isnull()] #479586
ppp_geonull.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
369,369,369,369,369,369,5048318601,3/20/21,1084,PPS,DELTA INDUSTRIAL SERVICES INC.,...,999 Other,5511 Management of Companies and Enterprises,5511.0,ALASKA DISTRICT OFFICE,"b $350,000-1 million",10 to 19,"1229 RICHARDSON HWY, DELTA JUNCTION, AK",NaN,NaN,NaN
428,428,428,428,428,428,5085327008,4/5/20,1084,PPP,"DELTA INDUSTRIAL SERVICES, INC.",...,999 Other,5511 Management of Companies and Enterprises,5511.0,ALASKA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1229 Richardson Hwy, DELTA JUNCTION, AK",NaN,NaN,NaN
1865,1865,1865,1865,1865,1865,4637628408,2/6/21,1084,PPS,MCKINLEY FIRE PROTECTION LLC,...,999 Other,2382 Building Equipment Contractors,2382.0,ALASKA DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"1706 Ship Ave, Anchorage, AK",NaN,NaN,NaN
2274,2274,2274,2274,2274,2274,5337318401,2/8/21,1084,PPS,THE ALASKA CENTRE FOR CREATIVE RENEWAL LLC,...,999 Other,7211 Traveler Accommodation,7211.0,ALASKA DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"46877 STILLPOINT TRL, HALIBUT COVE, AK",NaN,NaN,NaN
2379,2379,2379,2379,2379,2379,9891427104,4/15/20,1084,PPP,MCKINLEY FIRE PROTECTION,...,999 Other,2382 Building Equipment Contractors,2382.0,ALASKA DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"1706 SHIP AVENUE, ANCHORAGE, AK",NaN,NaN,NaN

In [4]:
ppp_geonull["full_add"].nunique() #64407

64407

In [5]:
ppp_geonull["BorrowerState"].value_counts()

TX    33381
OR    13456
UT     9295
ID     4416
PR     2952
SD     2695
VI      218
WY       90
MP       82
IN       28
MI       14
NC       11
PA        8
GU        8
AL        8
AK        5
NM        4
WA        4
AZ        4
TN        3
MA        3
NJ        3
FL        3
ME        2
IL        2
WI        2
AR        2
CO        2
WV        1
GA        1
CT        1
MN        1
HI        1
OH        1
NY        1
NE        1
IA        1
MS        1
Name: BorrowerState, dtype: int64

<h4> Process by State

In [6]:
ppp_togeo_comb= ppp_geonull[ppp_geonull["BorrowerState"] == "TX"]
ppp_togeo_comb

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
840482,840482,840482,840482,840482,840482,6582497008,4/7/20,681,PPP,JACOBY & JACOBY INC,...,999 Other,4931 Warehousing and Storage,4931.0,SAN ANTONIO DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"806 PO Box, MELVIN, TX",NaN,NaN,NaN
850869,850869,850869,850869,850869,850869,4283458309,1/23/21,610,PPS,TMBP-CLICK INC,...,999 Other,"5413 Architectural, Engineering, and Related S...",5413.0,DALLAS / FT WORTH DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"325, DALLAS, TX",NaN,NaN,NaN
851843,851843,851843,851843,851843,851843,5479017208,4/27/20,681,PPP,"CINEMA SOLUTIONS, INC",...,999 Other,5112 Software Publishers,5112.0,SAN ANTONIO DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"19026 RIDGEWOOD PKWY STE 107, SAN ANTONIO, TX",NaN,NaN,NaN
851844,851844,851844,851844,851844,851844,1784327107,4/10/20,639,PPP,"MIRA'S SPORTS & MORE, INC.",...,999 Other,"4511 Sporting Goods, Hobby, and Musical Instru...",4511.0,LOWER RIO GRANDE VALLEY DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"6006 AYERS ST, CORPUS CHRISTI, TX",NaN,NaN,NaN
851845,851845,851845,851845,851845,851845,5881287402,5/13/20,671,PPP,"PINNACLE DISASTER & RECOVERY SERVICES, LP",...,999 Other,2389 Other Specialty Trade Contractors,2389.0,HOUSTON DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"12507 Woodworth Drive, Suite 400, CYPRESS, TX",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886818,886818,886818,886818,886818,886818,9936567203,4/28/20,671,PPP,ST. ANTHONY CATHOLIC CHURCH,...,999 Other,8131 Religious Organizations,8131.0,HOUSTON DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"401 South Parker, Bryan, TX",NaN,NaN,NaN
886819,886819,886819,886819,886819,886819,9960748303,1/31/21,681,PPS,URCORE COMPANIES LLC,...,999 Other,5614 Business Support Services,5614.0,SAN ANTONIO DISTRICT OFFICE,"a $150,000-350,000",50 to 99,"1386 Industrial Dr Ste 125, New Braunfels, TX",NaN,NaN,NaN
886820,886820,886820,886820,886820,886820,9966447007,4/9/20,678,PPP,STEADFAST ENERGY INVESTMENTS LP,...,999 Other,2111 Oil and Gas Extraction,2111.0,LUBBOCK DISTRICT OFFICE,"a $150,000-350,000",Fewer than 5,"4305 N. Garfield, Midland, TX",NaN,NaN,NaN
886821,886821,886821,886821,886821,886821,9967088603,3/26/21,677,PPP,RUDDOCK MANUFACTURING COMPANY INC.,...,315 Apparel,3152 Cut and Sew Apparel Manufacturing,3152.0,EL PASO DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"1801 Magoffin Ave, El Paso, TX",NaN,NaN,NaN
886822,886822,886822,886822,886822,886822,9986128510,3/12/21,671,PPS,METALLOY INC,...,331 Primary Metals,3314 Nonferrous Metal (except Aluminum) Produc...,3314.0,HOUSTON DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"5800 Heiser St, Houston, TX",NaN,NaN,NaN

In [7]:
#process to identify and code for unique addresses 
ppp_togeo = ppp_togeo_comb["full_add"]
ppp_togeo_unique = ppp_togeo.drop_duplicates()
ppp_togeo_unique

840482                           806 PO Box, MELVIN, TX
850869                                  325, DALLAS, TX
851843    19026 RIDGEWOOD PKWY STE 107, SAN ANTONIO, TX
851844                6006 AYERS ST, CORPUS CHRISTI, TX
851845    12507 Woodworth Drive, Suite 400, CYPRESS, TX
                              ...
886818                      401 South Parker, Bryan, TX
886819    1386 Industrial Dr Ste 125, New Braunfels, TX
886820                    4305 N. Garfield, Midland, TX
886821                   1801 Magoffin Ave, El Paso, TX
886822                      5800 Heiser St, Houston, TX
Name: full_add, Length: 32607, dtype: object

Google Geocoding API

In [8]:
API_KEY = "AIzaSyB1VgzISCRoQ1hh-ARhR0rzXtQmSKA4TkI" # c.s = 40017
# "AIzaSyC7hhwM4qlfkU8zfiq1_MR-n4BWktUxxMo" #c.d.s = 40017

In [9]:
params = {
    "key":API_KEY
}
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'
addresses = ppp_togeo_unique #STATE
lat = []
lng = []
notfound = []
for address in tqdm(addresses):
    params['address'] = f"{address}"
    response = requests.get(base_url, params=params).json()
    results = response['results']
    try:
        #print(f"{address} is {results[0]['geometry']['location']}")
        #geometry = results[0]['geometry']
        lat.append(results[0]['geometry']['location']['lat'])
        lng.append(results[0]['geometry']['location']['lng'])
        
    except (KeyError, IndexError):
        print(f"{address} Not Found")
        notfound.append(address)
        lat.append(None)
        lng.append(None)

  0%|          | 0/32607 [00:00<?, ?it/s]

806 PO Box, MELVIN, TX Not Found
325, DALLAS, TX Not Found
20311 Kuykendahl Rd, SPRING, TX Not Found

KeyboardInterrupt:

In [10]:
print(notfound)
notfound_df = pd.DataFrame({"Not_Found":notfound})
notfound_df.count()

['806 PO Box, MELVIN, TX', '325, DALLAS, TX', '20311 Kuykendahl Rd, SPRING, TX']

Not_Found    3
dtype: int64

In [11]:
addresses = ppp_togeo_unique

In [12]:
addresses

840482                           806 PO Box, MELVIN, TX
850869                                  325, DALLAS, TX
851843    19026 RIDGEWOOD PKWY STE 107, SAN ANTONIO, TX
851844                6006 AYERS ST, CORPUS CHRISTI, TX
851845    12507 Woodworth Drive, Suite 400, CYPRESS, TX
                              ...
886818                      401 South Parker, Bryan, TX
886819    1386 Industrial Dr Ste 125, New Braunfels, TX
886820                    4305 N. Garfield, Midland, TX
886821                   1801 Magoffin Ave, El Paso, TX
886822                      5800 Heiser St, Houston, TX
Name: full_add, Length: 32607, dtype: object

In [13]:
addresses.head()

840482                           806 PO Box, MELVIN, TX
850869                                  325, DALLAS, TX
851843    19026 RIDGEWOOD PKWY STE 107, SAN ANTONIO, TX
851844                6006 AYERS ST, CORPUS CHRISTI, TX
851845    12507 Woodworth Drive, Suite 400, CYPRESS, TX
Name: full_add, dtype: object

In [14]:
lat_df= pd.DataFrame(lat)
lat_df

              0
0           NaN
1           NaN
2     29.617826
3     27.720440
4     29.957840
...         ...
5207  35.912820
5208  26.173759
5209  32.337686
5210  29.585524
5211  32.957490

[5212 rows x 1 columns]

In [15]:
tx_add = addresses.iloc[:5212]

In [16]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)
location_df = pd.DataFrame({"full_add": tx_add, "Lat": lat, "Long":lng})
location_df.head()

                                             full_add        Lat       Long
840482                         806 PO Box, MELVIN, TX        NaN        NaN
850869                                325, DALLAS, TX        NaN        NaN
851843  19026 RIDGEWOOD PKWY STE 107, SAN ANTONIO, TX  29.617826 -98.457756
851844              6006 AYERS ST, CORPUS CHRISTI, TX  27.720440 -97.436078
851845  12507 Woodworth Drive, Suite 400, CYPRESS, TX  29.957840 -95.667952

In [17]:
location_null = location_df.loc[location_df["Lat"].isnull()]
location_null.count()

full_add    3
Lat         0
Long        0
dtype: int64

In [18]:
location_df.to_csv("../../data/state_data/geo/verify/location_verify_tx.csv")

#ref point 1/7

In [19]:
location_df= pd.read_csv("../../data/state_data/geo/verify/location_verify_tx.csv")
location_df

      Unnamed: 0                                       full_add        Lat        Long
0         840482                         806 PO Box, MELVIN, TX        NaN         NaN
1         850869                                325, DALLAS, TX        NaN         NaN
2         851843  19026 RIDGEWOOD PKWY STE 107, SAN ANTONIO, TX  29.617826  -98.457756
3         851844              6006 AYERS ST, CORPUS CHRISTI, TX  27.720440  -97.436078
4         851845  12507 Woodworth Drive, Suite 400, CYPRESS, TX  29.957840  -95.667952
...          ...                                            ...        ...         ...
5207      857423                      122 Main St, Canadian, TX  35.912820 -100.382077
5208      857424               300 W Expressway 83, Weslaco, TX  26.173759  -97.992710
5209      857425                 3537 S Hwy 287, WAXAHACHIE, TX  32.337686  -96.769169
5210      857426                 16332 INTERSTATE 35, SELMA, TX  29.585524  -98.298558
5211      857427               3902 Lindberg Drive, ADDISON, TX  32.957490  -96.846540

[5212 rows x 4 columns]

In [19]:
#ppp_geo["BorrowerState"].value_counts()

In [21]:
#mapping coordinates to NaN values in main ppp_geo
m = dict(zip(location_df.full_add,location_df.Lat))
ppp_geo.Lat = ppp_geo.Lat.fillna(ppp_geo.full_add.map(m))
n = dict(zip(location_df.full_add,location_df.Long))
ppp_geo.Long = ppp_geo.Long.fillna(ppp_geo.full_add.map(n))

In [21]:
#ppp_geoVT[ppp_geoVT.duplicated(keep=False)]

In [22]:
null_check =ppp_geo.loc[ppp_geo["Lat"].isnull()] #93877 > 66711 > 61268
null_check

        Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  Unnamed: 0.1.1.1.1  LoanNumber DateApproved  SBAOfficeCode ProcessingMethod                                        BorrowerName                BorrowerAddress    BorrowerCity BorrowerState  BorrowerZip LoanStatusDate    LoanStatus  Term  SBAGuarantyPercentage  InitialApprovalAmount  CurrentApprovalAmount  UndisbursedAmount FranchiseName  ServicingLenderLocationID    ServicingLenderName ServicingLenderAddress ServicingLenderCity ServicingLenderState ServicingLenderZip RuralUrbanIndicator HubzoneIndicator LMIIndicator             BusinessAgeDescription     ProjectCity    ProjectCountyName ProjectState  ProjectZip   CD  JobsReported  NAICSCode        Race               Ethnicity  UTILITIES_PROCEED  PAYROLL_PROCEED  MORTGAGE_INTEREST_PROCEED  RENT_PROCEED  REFINANCE_EIDL_PROCEED  HEALTH_CARE_PROCEED  DEBT_INTEREST_PROCEED                    BusinessType  OriginatingLenderLocationID      OriginatingLender OriginatingLenderCity OriginatingLenderState        Gender      Veteran NonProfit  ForgivenessAmount ForgivenessDate    NA Estimated_LenderPercent  Estimated_LenderProfit  DateApproved_ts  ForgivenessDate_ts                                 Industry                                               LongName TRIIndustrySector                             IndustrySubsector  4DigitNAICS           SBAOfficeLabel            Loan_Range job_Range                                     full_add  Lat  Long  FIPS_z
369            369           369             369               369                 369  5048318601      3/20/21           1084              PPS                      DELTA INDUSTRIAL SERVICES INC.            1229 RICHARDSON HWY  DELTA JUNCTION            AK      99737.0            NaN   Exemption 4    60                    100              824834.30              824834.30                0.0           NaN                     116975          Northrim Bank            3111 'C' St           ANCHORAGE                   AK              99503                   R                N            N  Existing or more than 2 years old  DELTA JUNCTION  SOUTHEAST FAIRBANKS           AK       99737  AK-          11.0   551114.0  Unanswered       Unknown/NotStated                1.0        824830.30                        NaN           NaN                     NaN                  NaN                    NaN        Subchapter S Corporation                       116975          Northrim Bank             ANCHORAGE                     AK  Female Owned   Unanswered         N                NaN             NaN  55.0                      3%              24745.0290       1616198400         -9223372037  Management of Companies and Enterprises  Corporate, Subsidiary, and Regional Managing Offices          999 Other  5511 Management of Companies and Enterprises       5511.0   ALASKA DISTRICT OFFICE  b $350,000-1 million  10 to 19      1229 RICHARDSON HWY, DELTA JUNCTION, AK  NaN   NaN     NaN
428            428           428             428               428                 428  5085327008       4/5/20           1084              PPP                     DELTA INDUSTRIAL SERVICES, INC.            1229 Richardson Hwy  DELTA JUNCTION            AK      99737.0        3/19/21  Paid in Full    24                    100              738690.00              738690.00                0.0           NaN                     116975          Northrim Bank            3111 'C' St           ANCHORAGE                   AK              99503                   R                N            N  Existing or more than 2 years old  DELTA JUNCTION  SOUTHEAST FAIRBANKS           AK  99737-9800  AK-          60.0   551114.0  Unanswered       Unknown/NotStated                NaN        738690.00                        NaN           NaN                     NaN                  NaN                    NaN        Subchapter S Corporation                       116975          Northrim Bank             ANCHORAGE                     AK  Female Owned   Unanswered         N          744923.33         2/22/21  55.0                      3%              22160.7000       1586044800          1613952000  Management of Companies and Enterprises  Corporate, Subsidiary, and Regional Managing Offices          999 Other  5511 Management of Companies and Enterprises       5511.0   ALASKA DISTRICT OFFICE  b $350,000-1 million  50 to 99      1229 Richardson Hwy, DELTA JUNCTION, AK  NaN   NaN     NaN
1865          1865          1865            1865              1865                1865  4637628408       2/6/21           1084              PPS                        MCKINLEY FIRE PROTECTION LLC                  1706 Ship Ave       Anchorage            AK      99501.0            NaN   Exemption 4    60                    100              208121.85              208121.85                0.0           NaN                     116975          Northrim Bank            3111 'C' St           ANCHORAGE                   AK              99503                   U                Y            Y  Existing or more than 2 years old       Anchorage            ANCHORAGE           AK  99501-1807  AK-          13.0   238220.0  Unanswered  Not Hispanic or Latino                1.0        208119.85                        NaN           NaN                     NaN                  NaN                    NaN  Limited Liability Company(LLC)                       116975          Northrim Bank             ANCHORAGE                     AK    Male Owned  Non-Veteran         N                NaN             NaN  23.0                      5%              10406.0925       1612569600         -9223372037                             Construction   Plumbing, Heating, and Air-Conditioning Contractors          999 Other           2382 Building Equipment Contractors       2382.0   ALASKA DISTRICT OFFICE    a $150,000-350,000  10 to 19                 1706 Ship Ave, Anchorage, AK  NaN   NaN     NaN
2274          2274          2274            2274              2274                2274  5337318401       2/8/21           1084              PPS          THE ALASKA CENTRE FOR CREATIVE RENEWAL LLC           46877 STILLPOINT TRL    HALIBUT COVE            AK      99603.0            NaN   Exemption 4    60                    100              174292.00              174292.00                0.0           NaN                     116975          Northrim Bank            3111 'C' St           ANCHORAGE                   AK              99503                   R                N            N  Existing or more than 2 years old    HALIBUT COVE      KENAI PENINSULA           AK       99603  AK-          18.0   721199.0       White  Not Hispanic or Latino                1.0        174287.00                        NaN           NaN                     NaN                  NaN                    NaN  Limited Liability Company(LLC)                       116975          Northrim Bank             ANCHORAGE                     AK    Male Owned  Non-Veteran         N                NaN             NaN  72.0                      5%               8714.6000       1612742400         -9223372037          Accommodation and Food Services                      All Other Traveler Accommodation          999 Other                   7211 Traveler Accommodation       7211.0   ALASKA DISTRICT OFFICE    a $150,000-350,000  10 to 19       46877 STILLPOINT TRL, HALIBUT COVE, AK  NaN   NaN     NaN
2379          2379          2379            2379              2379                2379  9891427104      4/15/20           1084              PPP                            MCKINLEY FIRE PROTECTION               1706 SHIP AVENUE       ANCHORAGE            AK      99501.0        3/19/21  Paid in Full    24                    100              166972.37              166972.37                0.0           NaN                     116975          Northrim Bank            3111 'C' St           ANCHORAGE                   AK              99503                   U                Y            Y  Existing or more than 2 years old       ANCHORAGE            ANCHORAGE           AK  99501-1807  AK-          14.0   238220.0  Unanswered  Not Hispanic or Latino                NaN        166972.37                        NaN           NaN                     NaN                  NaN                    NaN  Limited Liability Company(LLC)                       116975          Northrim Bank             ANCHORAGE                     AK    Male Owned  Non-Veteran         N          168353.89         2/19/21  23.0                      5%               8348.6185       1586908800          1613692800                             Construction   Plumbing, Heating, and Air-Conditioning Contractors          999 Other           2382 Building Equipment Contractors       2382.0   ALASKA DISTRICT OFFICE    a $150,000-350,000  10 to 19              1706 SHIP AVENUE, ANCHORAGE, AK  NaN   NaN     NaN
...            ...           ...             ...               ...                 ...         ...          ...            ...              ...                                                 ...                            ...             ...           ...          ...            ...           ...   ...                    ...                    ...                    ...                ...           ...                        ...                    ...                    ...                 ...                  ...                ...                 ...              ...          ...                                ...             ...                  ...          ...         ...  ...           ...        ...         ...                     ...                ...              ...                        ...           ...                     ...                  ...                    ...                             ...                          ...                    ...                   ...                    ...           ...          ...       ...                ...             ...   ...                     ...                     ...              ...                 ...                                      ...                                                    ...               ...                                           ...          ...                      ...                   ...       ...                                          ...  ...   ...     ...
968551      968551        968551          968551            968551              968551  2665238309      1/21/21            897              PPS                                 RHOADES DENTAL P.C.                17 S Seneca Ave       Newcastle            WY      82701.0         8/6/21  Paid in Full    60                    100              150000.00              150000.00                0.0           NaN                      77248  Pinnacle Bank-Wyoming      1702 Sheridan Ave                CODY                   WY         82414-3848                   R                N            N  Existing or more than 2 years old       Newcastle               WESTON           WY  82701-2816  WY-          11.0   621210.0  Unanswered  Not Hispanic or Latino                NaN        150000.00                        NaN           NaN                     NaN                  NaN                    NaN                     Corporation                        77248  Pinnacle Bank-Wyoming                  CODY                     WY  Female Owned      Veteran         N          150661.64         7/12/21  62.0                      5%               7500.0000       1611187200          1626048000        Health Care and Social Assistance                                   Offices of Dentists          999 Other                      6212 Offices of Dentists       6212.0  WYOMING DISTRICT OFFICE    a $150,000-350,000  10 to 19               17 S Seneca Ave, Newcastle, WY  NaN   NaN     NaN
968552      968552        968552          968552            968552              968552  4395967002       4/3/20            897              PPP                            ROY E PAULSON, JR., P.C.                 102 N. Kenwood          CASPER            WY      82601.0        1/13/21  Paid in Full    24                    100              150000.00              150000.00                0.0           NaN                      42366     Platte Valley Bank           2201 Main St          TORRINGTON                   WY         82240-2317                   U                N            N  Existing or more than 2 years old          CASPER              NATRONA           WY  82601-2724  WY-          15.0   621210.0  Unanswered  Not Hispanic or Latino                NaN        150000.00                        NaN           NaN                     NaN                  NaN                    NaN                     Corporation                        42366     Platte Valley Bank            TORRINGTON                     WY    Male Owned  Non-Veteran         N          151037.50         12/9/20  62.0                      5%               7500.0000       1585872000          1607472000        Health Care and Social Assistance                                   Offices of Dentists          999 Other                      6212 Offices of Dentists       6212.0  WYOMING DISTRICT OFFICE    a $150,000-350,000  10 to 19                   102 N. Kenwood, CASPER, WY  NaN   NaN     NaN
968553      968553        968553          968553            968553              968553  6985647108      4/14/20            897              PPP  SWEETWATER COUNTY CHILD DEVELOPMENTAL CENTER, INC.          1715 HITCHING POST DR     GREEN RIVER            WY      82935.0        12/8/20  Paid in Full    24                    100              150000.00              150000.00                0.0           NaN                     122813      NebraskaLand Bank        1400 S Dewey St        NORTH PLATTE                   NE         69101-7605                   U                N            N  Existing or more than 2 years old     GREEN RIVER           SWEETWATER           WY  82935-5783  WY-          42.0   624410.0  Unanswered       Unknown/NotStated             5000.0        145000.00                        NaN           NaN                     NaN                  NaN                    NaN     Non-Profit Childcare Center                       122813      NebraskaLand Bank          NORTH PLATTE                     NE    Unanswered   Unanswered         Y          150789.04         11/3/20  62.0                      5%               7500.0000       1586822400          1604361600        Health Care and Social Assistance                               Child Day Care Services          999 Other                  6244 Child Day Care Services       6244.0  WYOMING DISTRICT OFFICE    a $150,000-350,000  20 to 49       1715 HITCHING POST DR, GREEN RIVER, WY  NaN   NaN     NaN
968555      968555        968555          968555            968555              968555  9054647103      4/15/20            897              PPP                                      EDEN LIFE CARE  30 N. Gould Street Suite 4000        SHERIDAN            WY      82801.0            NaN   Exemption 4    60                    100              150000.00              150000.00                0.0           NaN                      25901    Small Business Bank        13423 W 92nd St              LENEXA                   KS         66215-3636                   R                N            N    New Business or 2 years or less        SHERIDAN             SHERIDAN           WY  82801-0001  WY-           7.0   621610.0  Unanswered       Unknown/NotStated                NaN        150000.00                        NaN           NaN                     NaN                  NaN                    NaN                     Corporation                        25901    Small Business Bank                LENEXA                     KS    Unanswered   Unanswered         N                NaN             NaN  62.0                      5%               7500.0000       1586908800         -9223372037        Health Care and Social Assistance                              Home Health Care Services         999 Other                6216 Home Health Care Services       6216.0  WYOMING DISTRICT OFFICE    a $150,000-350,000    5 to 9  30 N. Gould Street Suite 4000, SHERIDAN, WY  NaN   NaN     NaN
968556      968556        968556          968556            968556              968556  9184687004       4/9/20            897              PPP                       S & S JOHNSON ENTERPRISES INC           7342 Granite Loop Rd   TETON VILLAGE            WY      83025.0       10/22/21  Paid in Full    24                    100              150000.00              150000.00                0.0           NaN                      77193   Bank of Jackson Hole         990 W Broadway             JACKSON                   WY              83001                   R                N            N  Existing or more than 2 years old   TETON VILLAGE                TETON           WY  83025-0550  WY-          11.0   722511.0  Unanswered       Unknown/NotStated                NaN        150000.00                        NaN           NaN                     NaN                  NaN                    NaN        Subchapter S Corporation                        77193   Bank of Jackson Hole               JACKSON                     WY    Unanswered   Unanswered         N          152162.50         9/22/21  72.0                      5%               7500.0000       1586390400          1632268800          Accommodation and Food Services                              Full-Service Restaurants          999 Other      7225 Restaurants and Other Eating Places       7225.0  WYOMING DISTRICT OFFICE    a $150,000-350,000  10 to 19      7342 Granite Loop Rd, TETON VILLAGE, WY  NaN   NaN     NaN

[61268 rows x 75 columns]

Writing to main Geo File

In [23]:
ppp_geo.to_csv("../../data/state_data/geo/ppp_geo.csv")

In [24]:
ppp_df = ppp_geo

Parsing Geo DataFrame for State Geo Files

In [25]:
ak_df = ppp_df.loc[ppp_df["BorrowerState"] == "AK", :]
al_df = ppp_df.loc[ppp_df["BorrowerState"] == "AL", :]
ar_df = ppp_df.loc[ppp_df["BorrowerState"] == "AR", :]
as_df = ppp_df.loc[ppp_df["BorrowerState"] == "AS", :] #American Samoa
az_df = ppp_df.loc[ppp_df["BorrowerState"] == "AZ", :]
ca_df = ppp_df.loc[ppp_df["BorrowerState"] == "CA", :]
co_df = ppp_df.loc[ppp_df["BorrowerState"] == "CO", :]
ct_df = ppp_df.loc[ppp_df["BorrowerState"] == "CT", :]
dc_df = ppp_df.loc[ppp_df["BorrowerState"] == "DC", :] #D.C.
de_df = ppp_df.loc[ppp_df["BorrowerState"] == "DE", :]
fl_df = ppp_df.loc[ppp_df["BorrowerState"] == "FL", :]
ga_df = ppp_df.loc[ppp_df["BorrowerState"] == "GA", :]
gu_df = ppp_df.loc[ppp_df["BorrowerState"] == "GU", :] #Guam
hi_df = ppp_df.loc[ppp_df["BorrowerState"] == "HI", :]
ia_df = ppp_df.loc[ppp_df["BorrowerState"] == "IA", :]
id_df = ppp_df.loc[ppp_df["BorrowerState"] == "ID", :]
il_df = ppp_df.loc[ppp_df["BorrowerState"] == "IL", :]
in_df = ppp_df.loc[ppp_df["BorrowerState"] == "IN", :]
ks_df = ppp_df.loc[ppp_df["BorrowerState"] == "KS", :]
ky_df = ppp_df.loc[ppp_df["BorrowerState"] == "KY", :]
la_df = ppp_df.loc[ppp_df["BorrowerState"] == "LA", :]
ma_df = ppp_df.loc[ppp_df["BorrowerState"] == "MA", :]
md_df = ppp_df.loc[ppp_df["BorrowerState"] == "MD", :]
me_df = ppp_df.loc[ppp_df["BorrowerState"] == "ME", :]
mi_df = ppp_df.loc[ppp_df["BorrowerState"] == "MI", :]
mn_df = ppp_df.loc[ppp_df["BorrowerState"] == "MN", :]
mo_df = ppp_df.loc[ppp_df["BorrowerState"] == "MO", :]
mp_df = ppp_df.loc[ppp_df["BorrowerState"] == "MP", :] #Saipan Member of Parliament
ms_df = ppp_df.loc[ppp_df["BorrowerState"] == "MS", :]
mt_df = ppp_df.loc[ppp_df["BorrowerState"] == "MT", :]
nc_df = ppp_df.loc[ppp_df["BorrowerState"] == "NC", :]
nd_df = ppp_df.loc[ppp_df["BorrowerState"] == "ND", :]
ne_df = ppp_df.loc[ppp_df["BorrowerState"] == "NE", :]
nh_df = ppp_df.loc[ppp_df["BorrowerState"] == "NH", :]
nj_df = ppp_df.loc[ppp_df["BorrowerState"] == "NJ", :]
nm_df = ppp_df.loc[ppp_df["BorrowerState"] == "NM", :]
nv_df = ppp_df.loc[ppp_df["BorrowerState"] == "NV", :]
ny_df = ppp_df.loc[ppp_df["BorrowerState"] == "NY", :]
oh_df = ppp_df.loc[ppp_df["BorrowerState"] == "OH", :]
ok_df = ppp_df.loc[ppp_df["BorrowerState"] == "OK", :]
or_df = ppp_df.loc[ppp_df["BorrowerState"] == "OR", :]
pa_df = ppp_df.loc[ppp_df["BorrowerState"] == "PA", :]
pr_df = ppp_df.loc[ppp_df["BorrowerState"] == "PR", :] #Puerto Rico
ri_df = ppp_df.loc[ppp_df["BorrowerState"] == "RI", :]
sc_df = ppp_df.loc[ppp_df["BorrowerState"] == "SC", :]
sd_df = ppp_df.loc[ppp_df["BorrowerState"] == "SD", :]
tn_df = ppp_df.loc[ppp_df["BorrowerState"] == "TN", :]
tx_df = ppp_df.loc[ppp_df["BorrowerState"] == "TX", :]
ut_df = ppp_df.loc[ppp_df["BorrowerState"] == "UT", :]
va_df = ppp_df.loc[ppp_df["BorrowerState"] == "VA", :]
vi_df = ppp_df.loc[ppp_df["BorrowerState"] == "VI", :] #Virgin Islands
vt_df = ppp_df.loc[ppp_df["BorrowerState"] == "VT", :]
wa_df = ppp_df.loc[ppp_df["BorrowerState"] == "WA", :]
wi_df = ppp_df.loc[ppp_df["BorrowerState"] == "WI", :]
wv_df = ppp_df.loc[ppp_df["BorrowerState"] == "WV", :]
wy_df = ppp_df.loc[ppp_df["BorrowerState"] == "WY", :]

Geocoded States

In [26]:
ak_df.to_csv("../../data/state_data/geo/geocoded/geo_ak.csv") 
al_df.to_csv("../../data/state_data/geo/geocoded/geo_al.csv")
ar_df.to_csv("../../data/state_data/geo/geocoded/geo_ar.csv") 
as_df.to_csv("../../data/state_data/geo/geocoded/geo_as.csv")
az_df.to_csv("../../data/state_data/geo/geocoded/geo_az.csv")  
ca_df.to_csv("../../data/state_data/geo/geocoded/geo_ca.csv")
co_df.to_csv("../../data/state_data/geo/geocoded/geo_co.csv") 
ct_df.to_csv("../../data/state_data/geo/geocoded/geo_ct.csv")  


dc_df.to_csv("../../data/state_data/geo/geocoded/geo_dc.csv")
de_df.to_csv("../../data/state_data/geo/geocoded/geo_de.csv") 
ga_df.to_csv("../../data/state_data/geo/geocoded/geo_ga.csv")
gu_df.to_csv("../../data/state_data/geo/geocoded/geo_gu.csv")
hi_df.to_csv("../../data/state_data/geo/geocoded/geo_hi.csv") 
fl_df.to_csv("../../data/state_data/geo/geocoded/geo_fl.csv") 
ia_df.to_csv("../../data/state_data/geo/geocoded/geo_ia.csv")  
il_df.to_csv("../../data/state_data/geo/geocoded/geo_il.csv")
in_df.to_csv("../../data/state_data/geo/geocoded/geo_in.csv") 
ks_df.to_csv("../../data/state_data/geo/geocoded/geo_ks.csv")
ky_df.to_csv("../../data/state_data/geo/geocoded/geo_ky.csv")
la_df.to_csv("../../data/state_data/geo/geocoded/geo_la.csv")
nc_df.to_csv("../../data/state_data/geo/geocoded/geo_nc.csv") 
nd_df.to_csv("../../data/state_data/geo/geocoded/geo_nd.csv")
ne_df.to_csv("../../data/state_data/geo/geocoded/geo_ne.csv")
ma_df.to_csv("../../data/state_data/geo/geocoded/geo_ma.csv") 
md_df.to_csv("../../data/state_data/geo/geocoded/geo_md.csv")
me_df.to_csv("../../data/state_data/geo/geocoded/geo_me.csv")
mi_df.to_csv("../../data/state_data/geo/geocoded/geo_mi.csv") 
mn_df.to_csv("../../data/state_data/geo/geocoded/geo_mn.csv") 
mo_df.to_csv("../../data/state_data/geo/geocoded/geo_mo.csv")
ms_df.to_csv("../../data/state_data/geo/geocoded/geo_ms.csv")
mt_df.to_csv("../../data/state_data/geo/geocoded/geo_mt.csv")
nc_df.to_csv("../../data/state_data/geo/geocoded/geo_nc.csv")
nh_df.to_csv("../../data/state_data/geo/geocoded/geo_nh.csv")  
nj_df.to_csv("../../data/state_data/geo/geocoded/geo_nj.csv")
nm_df.to_csv("../../data/state_data/geo/geocoded/geo_nm.csv") 
nv_df.to_csv("../../data/state_data/geo/geocoded/geo_nv.csv")  
ny_df.to_csv("../../data/state_data/geo/geocoded/geo_ny.csv")  
oh_df.to_csv("../../data/state_data/geo/geocoded/geo_oh.csv")
ok_df.to_csv("../../data/state_data/geo/geocoded/geo_ok.csv")
pa_df.to_csv("../../data/state_data/geo/geocoded/geo_pa.csv")
ri_df.to_csv("../../data/state_data/geo/geocoded/geo_ri.csv")
sc_df.to_csv("../../data/state_data/geo/geocoded/geo_sc.csv")
tn_df.to_csv("../../data/state_data/geo/geocoded/geo_tn.csv")  
tx_df.to_csv("../../data/state_data/geo/geocoded/geo_tx.csv")  
va_df.to_csv("../../data/state_data/geo/geocoded/geo_va.csv") 
vi_df.to_csv("../../data/state_data/geo/geocoded/geo_vi.csv")  
vt_df.to_csv("../../data/state_data/geo/geocoded/geo_vt.csv")
wa_df.to_csv("../../data/state_data/geo/geocoded/geo_wa.csv")
wi_df.to_csv("../../data/state_data/geo/geocoded/geo_wi.csv")  
wv_df.to_csv("../../data/state_data/geo/geocoded/geo_wv.csv")

All States

In [ ]:
ak_df.to_csv("../../data/state_data/geo_ak.csv") 
al_df.to_csv("../../data/state_data/geo_al.csv")
ar_df.to_csv("../../data/state_data/geo_ar.csv") 
as_df.to_csv("../../data/state_data/geo_as.csv")
az_df.to_csv("../../data/state_data/geo_az.csv")  
ca_df.to_csv("../../data/state_data/geo_ca.csv")  
co_df.to_csv("../../data/state_data/geo_co.csv") 
ct_df.to_csv("../../data/state_data/geo_ct.csv")  
dc_df.to_csv("../../data/state_data/geo_dc.csv")
de_df.to_csv("../../data/state_data/geo_de.csv") 
fl_df.to_csv("../../data/state_data/geo_fl.csv") 
ga_df.to_csv("../../data/state_data/geo_ga.csv") 
gu_df.to_csv("../../data/state_data/geo_gu.csv")
hi_df.to_csv("../../data/state_data/geo_hi.csv") 
ia_df.to_csv("../../data/state_data/geo_ia.csv")  
id_df.to_csv("../../data/state_data/geo_id.csv")  
il_df.to_csv("../../data/state_data/geo_il.csv")  
in_df.to_csv("../../data/state_data/geo_in.csv") 
ks_df.to_csv("../../data/state_data/geo_ks.csv")  
ky_df.to_csv("../../data/state_data/geo_ky.csv")  
la_df.to_csv("../../data/state_data/geo_la.csv")
ma_df.to_csv("../../data/state_data/geo_ma.csv") 
md_df.to_csv("../../data/state_data/geo_md.csv")
me_df.to_csv("../../data/state_data/geo_me.csv")  
mi_df.to_csv("../../data/state_data/geo_mi.csv") 
mn_df.to_csv("../../data/state_data/geo_mn.csv") 
mo_df.to_csv("../../data/state_data/geo_mo.csv")  
mp_df.to_csv("../../data/state_data/geo_mp.csv") 
ms_df.to_csv("../../data/state_data/geo_ms.csv")
mt_df.to_csv("../../data/state_data/geo_mt.csv")
nc_df.to_csv("../../data/state_data/geo_nc.csv") 
nd_df.to_csv("../../data/state_data/geo_nd.csv")  
ne_df.to_csv("../../data/state_data/geo_ne.csv")
nh_df.to_csv("../../data/state_data/geo_nh.csv")  
nj_df.to_csv("../../data/state_data/geo_nj.csv")
nm_df.to_csv("../../data/state_data/geo_nm.csv") 
nv_df.to_csv("../../data/state_data/geo_nv.csv")  
ny_df.to_csv("../../data/state_data/geo_ny.csv")  
oh_df.to_csv("../../data/state_data/geo_oh.csv")
ok_df.to_csv("../../data/state_data/geo_ok.csv") 
or_df.to_csv("../../data/state_data/geo_or.csv")  
pa_df.to_csv("../../data/state_data/geo_pa.csv")
pr_df.to_csv("../../data/state_data/geo_pr.csv")  
ri_df.to_csv("../../data/state_data/geo_ri.csv") 
sc_df.to_csv("../../data/state_data/geo_sc.csv") 
sd_df.to_csv("../../data/state_data/geo_sd.csv") 
tn_df.to_csv("../../data/state_data/geo_tn.csv")  
tx_df.to_csv("../../data/state_data/geo_tx.csv")  
ut_df.to_csv("../../data/state_data/geo_ut.csv")  
va_df.to_csv("../../data/state_data/geo_va.csv")  
vi_df.to_csv("../../data/state_data/geo_vi.csv")  
vt_df.to_csv("../../data/state_data/geo_vt.csv")
wa_df.to_csv("../../data/state_data/geo_wa.csv")  
wi_df.to_csv("../../data/state_data/geo_wi.csv")  
wv_df.to_csv("../../data/state_data/geo_wv.csv") 
wy_df.to_csv("../../data/state_data/geo_wy.csv")