In [2]:
import pandas as pd
import numpy as np

In [6]:
ppp_df = pd.read_csv("data/ppp_pipe.csv")
ppp_df

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255.0,32.0,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC"
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617.0,56.0,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC"
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,NaN,NaN,NaN,NaN,NaN,NaN,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA"
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361.0,23.0,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842.0,48.0,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968552,968552,968552,4395967002,4/3/20,897,PPP,"ROY E PAULSON, JR., P.C.",102 N. Kenwood,CASPER,WY,...,Offices of Dentists,999 Other,6212 Offices of Dentists,6212.0,62.0,Health Care and Social Assistance,WYOMING DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"102 N. Kenwood, CASPER, WY"
968553,968553,968553,6985647108,4/14/20,897,PPP,"SWEETWATER COUNTY CHILD DEVELOPMENTAL CENTER, ...",1715 HITCHING POST DR,GREEN RIVER,WY,...,Child Day Care Services,999 Other,6244 Child Day Care Services,6244.0,62.0,Health Care and Social Assistance,WYOMING DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"1715 HITCHING POST DR, GREEN RIVER, WY"
968554,968554,968554,7996438405,2/12/21,897,PPS,ELECTRICAL SYSTEMS OF WYOMING INC,1105 Adon Rd,Rozet,WY,...,Electrical Contractors and Other Wiring Instal...,999 Other,2382 Building Equipment Contractors,2382.0,23.0,Construction,WYOMING DISTRICT OFFICE,"a $150,000-350,000",Fewer than 5,"1105 Adon Rd, Rozet, WY"
968555,968555,968555,9054647103,4/15/20,897,PPP,EDEN LIFE CARE,30 N. Gould Street Suite 4000,SHERIDAN,WY,...,Home Health Care Services,999 Other,6216 Home Health Care Services,6216.0,62.0,Health Care and Social Assistance,WYOMING DISTRICT OFFICE,"a $150,000-350,000",5 to 9,"30 N. Gould Street Suite 4000, SHERIDAN, WY"
968556,968556,968556,9184687004,4/9/20,897,PPP,S & S JOHNSON ENTERPRISES INC,7342 Granite Loop Rd,TETON VILLAGE,WY,...,Full-Service Restaurants,999 Other,7225 Restaurants and Other Eating Places,7225.0,72.0,Accommodation and Food Services,WYOMING DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"7342 Granite Loop Rd, TETON VILLAGE, WY"

In [7]:
#pd.set_option('display.max_rows', None)
ppp_df_industry = ppp_df.groupby(["Industry", "IndustrySubsector"]).agg({ "LoanNumber": 'count'})
ppp_df_industry #312

                                                                                    LoanNumber
Industry                        IndustrySubsector
Accommodation and Food Services 7211 Traveler Accommodation                              20906
                                7212 RV (Recreational Vehicle) Parks and Recrea...        1158
                                7213 Rooming and Boarding Houses, Dormitories, ...         120
                                7223 Special Food Services                                4393
                                7224 Drinking Places (Alcoholic Beverages)                4002
...                                                                                        ...
Wholesale Trade                 4246 Chemical and Allied Products Merchant Whol...         955
                                4247 Petroleum and Petroleum Products Merchant ...        1490
                                4248 Beer, Wine, and Distilled Alcoholic Bevera...        1114
                                4249 Miscellaneous Nondurable Goods Merchant Wh...        3587
                                4251 Wholesale Electronic Markets and Agents an...        1281

[312 rows x 1 columns]

In [8]:
ppp_df_industry = ppp_df.groupby(["Industry", "IndustrySubsector", "Loan_Range", "BusinessType"]).agg({ "LoanNumber": 'count'})
ppp_df_industry  #9801

                                                                                                                                           LoanNumber
Industry                        IndustrySubsector                                  Loan_Range         BusinessType
Accommodation and Food Services 7211 Traveler Accommodation                        a $150,000-350,000 501(c)6 – Non Profit Membership               1
                                                                                                      Cooperative                                   4
                                                                                                      Corporation                                2601
                                                                                                      Employee Stock Ownership Plan(ESOP)           1
                                                                                                      Independent Contractors                       1
...                                                                                                                                               ...
Wholesale Trade                 4251 Wholesale Electronic Markets and Agents an... d $2-5 million     Corporation                                   5
                                                                                                      Limited Liability Company(LLC)                1
                                                                                                      Subchapter S Corporation                      5
                                                                                   e $5-10 million    Employee Stock Ownership Plan(ESOP)           1
                                                                                                      Limited Liability Company(LLC)                2

[9801 rows x 1 columns]

In [9]:
#pd.set_option('display.max_rows', None)
ppp_df["IndustrySubsector"].nunique()

312

In [10]:
ppp_df.loc[ppp_df["NAICSCode"] == 999990, 'Industry'] = 'Nonclassifiable Establishments'
ppp_df.loc[ppp_df["NAICSCode"] == 999990, 'IndustrySubsector'] = 'Nonclassifiable Establishments'
ppp_df.loc[ppp_df["NAICSCode"] == 999990, 'NA'] = 99
ppp_df.loc[ppp_df["NAICSCode"] == 999990, '4DigitNAICS'] = 9900

In [11]:
ppp_df["NAICSCode"] = ppp_df["NAICSCode"].fillna(0).astype(int).astype(str)
ppp_df["NA"] = ppp_df["NA"].fillna(0).astype(int).astype(str)
ppp_df["4DigitNAICS"] = ppp_df["4DigitNAICS"].fillna(0)
ppp_df["4DigitNAICS"] = ppp_df["4DigitNAICS"].astype(int).astype(str).str[:4]
ppp_df["Industry"] = ppp_df["Industry"].fillna("Not Available")
ppp_df["IndustrySubsector"] = ppp_df["IndustrySubsector"].fillna("Not Available")

In [12]:
ppp_df["4DigitNAICS"] = ppp_df.apply(lambda x: x["NA"] + '000' if x["4DigitNAICS"]=='0' else x["4DigitNAICS"], axis=1)
ppp_df["NA"] = ppp_df.apply(lambda x: x["NA"] + '0' if x["NA"]=='0' else x["NA"], axis=1)
ppp_df.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC"
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC"
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,NaN,NaN,Not Available,0000,00,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA"
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI"

In [13]:
ppp_df["4DigitNAICS"].nunique()

313

In [14]:
ppp_df.loc[ppp_df["4DigitNAICS"] == "6115", "IndustrySubsector"] = "6115 Technical and Trade Schools"
edu_ppp = ppp_df.loc[ppp_df["Industry"] == "Educational Services"]
edu_ppp.groupby(["Industry", "IndustrySubsector"]).agg({"LoanNumber": "count"})

                                                                         LoanNumber
Industry             IndustrySubsector
Educational Services 6111 Elementary and Secondary Schools                    10032
                     6112 Junior Colleges                                       101
                     6113 Colleges, Universities, and Professional S...        1370
                     6114 Business Schools and Computer and Manageme...         873
                     6115 Technical and Trade Schools                          1126
                     6116 Other Schools and Instruction                        3742
                     6117 Educational Support Services                         2781

In [15]:
#ppp_df.loc[ppp_df["4DigitNAICS"] == "6115", "IndustrySubsector"] = "6115 Technical and Trade Schools"
manppp = ppp_df.loc[ppp_df["Industry"] == "Utilities"]
manppp["IndustrySubsector"].sort_values().unique().tolist()

['2211 Electric Power Generation, Transmission and Distribution',
 '2212 Natural Gas Distribution ',
 '2213 Water, Sewage and Other Systems ']

<b>Industries - 26

In [16]:
indss_df_na =  ppp_df.groupby(["IndustrySubsector",  "4DigitNAICS"], as_index=False).agg({ "LoanNumber": 'count'}) #327
indss_df_na.head()

                                   IndustrySubsector 4DigitNAICS  LoanNumber
0                     1111 Oilseed and Grain Farming        1111         783
1                   1112 Vegetable and Melon Farming        1112         900
2                    1113 Fruit and Tree Nut Farming        1113        1630
3  1114 Greenhouse, Nursery, and Floriculture Pro...        1114        1230
4                            1119 Other Crop Farming        1119        1329

<b>Industry, Subsector - 328, accounts for Subsector = 0

In [17]:
pd.set_option('display.max_rows', None)
indss_df = ppp_df.groupby(["Industry", "NA", "4DigitNAICS"]).agg({ "LoanNumber": 'count'}) #327
indss_df

                                                                   LoanNumber
Industry                                           NA 4DigitNAICS
Accommodation and Food Services                    72 7211              20906
                                                      7212               1158
                                                      7213                120
                                                      7223               4393
                                                      7224               4002
                                                      7225              93936
Administrative and Support and Waste Management... 56 5611               2806
                                                      5612                647
                                                      5613               8926
                                                      5614               4940
                                                      5615               1698
                                                      5616               3957
                                                      5617              14195
                                                      5619               3334
                                                      5621               1258
                                                      5622                465
                                                      5629               2418
Agriculture, Forestry, Fishing and Hunting         11 1111                783
                                                      1112                900
                                                      1113               1630
                                                      1114               1230
                                                      1119               1329
                                                      1121               2315
                                                      1122                303
                                                      1123                218
                                                      1124                 17
                                                      1125                161
                                                      1129                397
                                                      1131                236
                                                      1132                 74
                                                      1133                892
                                                      1141                338
                                                      1142                 41
                                                      1151               1933
                                                      1152                261
                                                      1153                318
Arts, Entertainment, and Recreation                71 7111               2018
                                                      7112                859
                                                      7113               1360
                                                      7114                496
                                                      7115                648
                                                      7121               2008
                                                      7131                729
                                                      7132                461
                                                      7139               8340
Construction                                       23 2361              14039
                                                      2362              20282
                                                      2371               5198
                                                      2372                610
                                                      2373               4655
                                                      2379               3231
                                                      2381              16001
                                                      2382              35289
                                                      2383              11705
                                                      2389              17549
Educational Services                               61 6111              10032
                                                      6112                101
                                                      6113               1370
                                                      6114                873
                                                      6115               1126
                                                      6116               3742
                                                      6117               2781
Finance and Insurance                              52 5211                  4
                                                      5221                 58
                                                      5222               1384
                                                      5223               1275
                                                      5231                915
                                                      5232                 32
                                                      5239               3499
                                                      5241               1021
                                                      5242               6460
                                                      5251                181
                                                      5259                444
Health Care and Social Assistance                  62 6211              30142
                                                      6212              17619
                                                      6213              11474
                                                      6214               5394
                                                      6215               1846
                                                      6216              10076
                                                      6219               3512
                                                      6221               2320
                                                      6222                274
                                                      6223                354
                                                      6231               7712
                                                      6232               2279
                                                      6233               4611
                                                      6239                966
                                                      6241               8876
                                                      6242               1859
                                                      6243               1015
                                                      6244               7208
Information                                        51 5111               2369
                                                      5112               3793
                                                      5121               2206
                                                      5122                310
                                                      5151               1105
                                                      5152                135
                                                      5173                826
                                                      5174                 82
                                                      5179               1726
                                                      5182               1943
                                                      5191               1630
Management of Companies and Enterprises            55 5511               2169
Manufacturing                                      31 3111                406
                                                      3112                204
                                                      3113                339
                                                      3114                575
                                                      3115                426
                                                      3116                603
                                                      3117                239
                                                      3118               1720
                                                      3119               1896
                                                      3121               2363
                                                      3122                 86
                                                      3131                104
                                                      3132                292
                                                      3133                341
                                                      3141                275
                                                      3149                685
                                                      3151                110
                                                      3152               1059
                                                      3159                735
                                                      3161                 73
                                                      3162                116
                                                      3169                157
                                                   32 3211                691
                                                      3212                513
                                                      3219               2709
                                                      3221                168
                                                      3222               1192
                                                      3231               5551
                                                      3241                843
                                                      3251                676
                                                      3252                672
                                                      3253                276
                                                      3254               1058
                                                      3255                637
                                                      3256                654
                                                      3259                853
                                                      3261               3457
                                                      3262                688
                                                      3271                285
                                                      3272                558
                                                      3273               1641
                                                      3274                 20
                                                      3279                999
                                                   33 3311                370
                                                      3312                864
                                                      3313                283
                                                      3314                318
                                                      3315                814
                                                      3321               1066
                                                      3322                290
                                                      3323               5995
                                                      3324                696
                                                      3325                357
                                                      3326                476
                                                      3327               6271
                                                      3328               1809
                                                      3329               4291
                                                      3331               1860
                                                      3332               2117
                                                      3333               1121
                                                      3334               1010
                                                      3335               3160
                                                      3336                393
                                                      3339               3301
                                                      3341                613
                                                      3342                846
                                                      3343                350
                                                      3344               2039
                                                      3345               2327
                                                      3346                249
                                                      3351                761
                                                      3352                125
                                                      3353                797
                                                      3359               1341
                                                      3361                317
                                                      3362                738
                                                      3363               1323
                                                      3364               1323
                                                      3365                 95
                                                      3366                725
                                                      3369                377
                                                      3371               2329
                                                      3372               1587
                                                      3379                268
                                                      3391               2600
                                                      3399               5987
Mining, Quarrying, and Oil and Gas Extraction      21 2111                972
                                                      2121                193
                                                      2122                 72
                                                      2123               1279
                                                      2131               5842
Nonclassifiable Establishments                     99 9900               4092
Not Available                                      00 0000               8090
Other Services (except Public Administration)      81 8111              10470
                                                      8112               1211
                                                      8113               3228
                                                      8114               1294
                                                      8121               6950
                                                      8122                911
                                                      8123               1715
                                                      8129               5346
                                                      8131              13392
                                                      8132               3033
                                                      8133               3008
                                                      8134               3144
                                                      8139               4071
                                                      8141                110
Professional, Scientific, and Technical Services   54 5411              21585
                                                      5412               8356
                                                      5413              21682
                                                      5414               2877
                                                      5415              19206
                                                      5416              19657
                                                      5417               2515
                                                      5418               6187
                                                      5419              13609
Public Administration                              92 9211                328
                                                      9221               1195
                                                      9231                682
                                                      9241                118
                                                      9251                236
                                                      9261                329
                                                      9271                 27
                                                      9281                 53
Real Estate and Rental and Leasing                 53 5311               5677
                                                      5312               3177
                                                      5313               9668
                                                      5321                654
                                                      5322                931
                                                      5323                335
                                                      5324               2778
                                                      5331                152
Retail Trade                                       44 4411              17558
                                                      4412               3129
                                                      4413               2458
                                                      4421               2048
                                                      4422               1757
                                                      4431               1517
                                                      4441               4095
                                                      4442               1266
                                                      4451               4133
                                                      4452               1961
                                                      4453                452
                                                      4461               3988
                                                      4471               2050
                                                      4481               2209
                                                      4482                375
                                                      4483               1060
                                                   45 4511               1417
                                                      4512                264
                                                      4522                 83

In [18]:
indss_df =  ppp_df.groupby(["Industry", "NA", "IndustrySubsector", "4DigitNAICS"]).agg({ "LoanNumber": 'count'}) #327
print(indss_df.shape[0])
indss_df

313

                                                                                                                      LoanNumber
Industry                                           NA IndustrySubsector                                  4DigitNAICS
Accommodation and Food Services                    72 7211 Traveler Accommodation                        7211              20906
                                                      7212 RV (Recreational Vehicle) Parks and Recrea... 7212               1158
                                                      7213 Rooming and Boarding Houses, Dormitories, ... 7213                120
                                                      7223 Special Food Services                         7223               4393
                                                      7224 Drinking Places (Alcoholic Beverages)         7224               4002
                                                      7225 Restaurants and Other Eating Places           7225              93936
Administrative and Support and Waste Management... 56 5611 Office Administrative Services                5611               2806
                                                      5612 Facilities Support Services                   5612                647
                                                      5613 Employment Services                           5613               8926
                                                      5614 Business Support Services                     5614               4940
                                                      5615 Travel Arrangement and Reservation Services   5615               1698
                                                      5616 Investigation and Security Services           5616               3957
                                                      5617 Services to Buildings and Dwellings           5617              14195
                                                      5619 Other Support Services                        5619               3334
                                                      5621 Waste Collection                              5621               1258
                                                      5622 Waste Treatment and Disposal                  5622                465
                                                      5629 Remediation and Other Waste Management Ser... 5629               2418
Agriculture, Forestry, Fishing and Hunting         11 1111 Oilseed and Grain Farming                     1111                783
                                                      1112 Vegetable and Melon Farming                   1112                900
                                                      1113 Fruit and Tree Nut Farming                    1113               1630
                                                      1114 Greenhouse, Nursery, and Floriculture Prod... 1114               1230
                                                      1119 Other Crop Farming                            1119               1329
                                                      1121 Cattle Ranching and Farming                   1121               2315
                                                      1122 Hog and Pig Farming                           1122                303
                                                      1123 Poultry and Egg Production                    1123                218
                                                      1124 Sheep and Goat Farming                        1124                 17
                                                      1125 Aquaculture                                   1125                161
                                                      1129 Other Animal Production                       1129                397
                                                      1131 Timber Tract Operations                       1131                236
                                                      1132 Forest Nurseries and Gathering of Forest P... 1132                 74
                                                      1133 Logging                                       1133                892
                                                      1141 Fishing                                       1141                338
                                                      1142 Hunting and Trapping                          1142                 41
                                                      1151 Support Activities for Crop Production        1151               1933
                                                      1152 Support Activities for Animal Production      1152                261
                                                      1153 Support Activities for Forestry               1153                318
Arts, Entertainment, and Recreation                71 7111 Performing Arts Companies                     7111               2018
                                                      7112 Spectator Sports                              7112                859
                                                      7113 Promoters of Performing Arts, Sports, and ... 7113               1360
                                                      7114 Agents and Managers for Artists, Athletes,... 7114                496
                                                      7115 Independent Artists, Writers, and Performers  7115                648
                                                      7121 Museums, Historical Sites, and Similar Ins... 7121               2008
                                                      7131 Amusement Parks and Arcades                   7131                729
                                                      7132 Gambling Industries                           7132                461
                                                      7139 Other Amusement and Recreation Industries     7139               8340
Construction                                       23 2361 Residential Building Construction             2361              14039
                                                      2362 Nonresidential Building Construction          2362              20282
                                                      2371 Utility System Construction                   2371               5198
                                                      2372 Land Subdivision                              2372                610
                                                      2373 Highway, Street, and Bridge Construction      2373               4655
                                                      2379 Other Heavy and Civil Engineering Construc... 2379               3231
                                                      2381 Foundation, Structure, and Building Exteri... 2381              16001
                                                      2382 Building Equipment Contractors                2382              35289
                                                      2383 Building Finishing Contractors                2383              11705
                                                      2389 Other Specialty Trade Contractors             2389              17549
Educational Services                               61 6111 Elementary and Secondary Schools              6111              10032
                                                      6112 Junior Colleges                               6112                101
                                                      6113 Colleges, Universities, and Professional S... 6113               1370
                                                      6114 Business Schools and Computer and Manageme... 6114                873
                                                      6115 Technical and Trade Schools                   6115               1126
                                                      6116 Other Schools and Instruction                 6116               3742
                                                      6117 Educational Support Services                  6117               2781
Finance and Insurance                              52 5211 Monetary Authorities-Central Bank             5211                  4
                                                      5221 Depository Credit Intermediation              5221                 58
                                                      5222 Nondepository Credit Intermediation           5222               1384
                                                      5223 Activities Related to Credit Intermediation   5223               1275
                                                      5231 Securities and Commodity Contracts Interme... 5231                915
                                                      5232 Securities and Commodity Exchanges            5232                 32
                                                      5239 Other Financial Investment Activities         5239               3499
                                                      5241 Insurance Carriers                            5241               1021
                                                      5242 Agencies, Brokerages, and Other Insurance ... 5242               6460
                                                      5251 Insurance and Employee Benefit Funds          5251                181
                                                      5259 Other Investment Pools and Funds              5259                444
Health Care and Social Assistance                  62 6211 Offices of Physicians                         6211              30142
                                                      6212 Offices of Dentists                           6212              17619
                                                      6213 Offices of Other Health Practitioners         6213              11474
                                                      6214 Outpatient Care Centers                       6214               5394
                                                      6215 Medical and Diagnostic Laboratories           6215               1846
                                                      6216 Home Health Care Services                     6216              10076
                                                      6219 Other Ambulatory Health Care Services         6219               3512
                                                      6221 General Medical and Surgical Hospitals        6221               2320
                                                      6222 Psychiatric and Substance Abuse Hospitals     6222                274
                                                      6223 Specialty (except Psychiatric and Substanc... 6223                354
                                                      6231 Nursing Care Facilities (Skilled Nursing F... 6231               7712
                                                      6232 Residential Intellectual and Developmental... 6232               2279
                                                      6233 Continuing Care Retirement Communities and... 6233               4611
                                                      6239 Other Residential Care Facilities             6239                966
                                                      6241 Individual and Family Services                6241               8876
                                                      6242 Community Food and Housing, and Emergency ... 6242               1859
                                                      6243 Vocational Rehabilitation Services            6243               1015
                                                      6244 Child Day Care Services                       6244               7208
Information                                        51 5111 Newspaper, Periodical, Book, and Directory... 5111               2369
                                                      5112 Software Publishers                           5112               3793
                                                      5121 Motion Picture and Video Industries           5121               2206
                                                      5122 Sound Recording Industries                    5122                310
                                                      5151 Radio and Television Broadcasting             5151               1105
                                                      5152 Cable and Other Subscription Programming      5152                135
                                                      5173 Wired and Wireless Telecommunications Carr... 5173                826
                                                      5174 Satellite Telecommunications                  5174                 82
                                                      5179 Other Telecommunications                      5179               1726
                                                      5182 Data Processing, Hosting, and Related Serv... 5182               1943
                                                      5191 Other Information Services                    5191               1630
Management of Companies and Enterprises            55 5511 Management of Companies and Enterprises       5511               2169
Manufacturing                                      31 3111 Animal Food Manufacturing                     3111                406
                                                      3112 Grain and Oilseed Milling                     3112                204
                                                      3113 Sugar and Confectionery Product Manufacturing 3113                339
                                                      3114 Fruit and Vegetable Preserving and Special... 3114                575
                                                      3115 Dairy Product Manufacturing                   3115                426
                                                      3116 Animal Slaughtering and Processing            3116                603
                                                      3117 Seafood Product Preparation and Packaging     3117                239
                                                      3118 Bakeries and Tortilla Manufacturing           3118               1720
                                                      3119 Other Food Manufacturing                      3119               1896
                                                      3121 Beverage Manufacturing                        3121               2363
                                                      3122 Tobacco Manufacturing                         3122                 86
                                                      3131 Fiber, Yarn, and Thread Mills                 3131                104
                                                      3132 Fabric Mills                                  3132                292
                                                      3133 Textile and Fabric Finishing and Fabric Co... 3133                341
                                                      3141 Textile Furnishings Mills                     3141                275
                                                      3149 Other Textile Product Mills                   3149                685
                                                      3151 Apparel Knitting Mills                        3151                110
                                                      3152 Cut and Sew Apparel Manufacturing             3152               1059
                                                      3159 Apparel Accessories and Other Apparel Manu... 3159                735
                                                      3161 Leather and Hide Tanning and Finishing        3161                 73
                                                      3162 Footwear Manufacturing                        3162                116
                                                      3169 Other Leather and Allied Product Manufactu... 3169                157
                                                   32 3211 Sawmills and Wood Preservation                3211                691
                                                      3212 Veneer, Plywood, and Engineered Wood Produ... 3212                513
                                                      3219 Other Wood Product Manufacturing              3219               2709
                                                      3221 Pulp, Paper, and Paperboard Mills             3221                168
                                                      3222 Converted Paper Product Manufacturing         3222               1192
                                                      3231 Printing and Related Support Activities       3231               5551
                                                      3241 Petroleum and Coal Products Manufacturing     3241                843
                                                      3251 Basic Chemical Manufacturing                  3251                676
                                                      3252 Resin, Synthetic Rubber, and Artificial Sy... 3252                672
                                                      3253 Pesticide, Fertilizer, and Other Agricultu... 3253                276
                                                      3254 Pharmaceutical and Medicine Manufacturing     3254               1058
                                                      3255 Paint, Coating, and Adhesive Manufacturing    3255                637
                                                      3256 Soap, Cleaning Compound, and Toilet Prepar... 3256                654
                                                      3259 Other Chemical Product and Preparation Man... 3259                853
                                                      3261 Plastics Product Manufacturing                3261               3457
                                                      3262 Rubber Product Manufacturing                  3262                688
                                                      3271 Clay Product and Refractory Manufacturing     3271                285
                                                      3272 Glass and Glass Product Manufacturing         3272                558
                                                      3273 Cement and Concrete Product Manufacturing     3273               1641
                                                      3274 Lime and Gypsum Product Manufacturing         3274                 20
                                                      3279 Other Nonmetallic Mineral Product Manufact... 3279                999
                                                   33 3311 Iron and Steel Mills and Ferroalloy Manufa... 3311                370
                                                      3312 Steel Product Manufacturing from Purchased... 3312                864
                                                      3313 Alumina and Aluminum Production and Proces... 3313                283
                                                      3314 Nonferrous Metal (except Aluminum) Product... 3314                318
                                                      3315 Foundries                                     3315                814
                                                      3321 Forging and Stamping                          3321               1066
                                                      3322 Cutlery and Handtool Manufacturing            3322                290

In [19]:
ppp_df['BusinessType'].value_counts()

Corporation                            415963
Limited Liability Company(LLC)         261542
Subchapter S Corporation               177322
Non-Profit Organization                 54932
Partnership                             18086
Limited Liability Partnership           12737
Sole Proprietorship                     12429
Professional Association                 6780
Cooperative                              2449
501(c)3 – Non Profit                     1790
Non-Profit Childcare Center               909
501(c)6 – Non Profit Membership           765
Not Available                             728
Employee Stock Ownership Plan(ESOP)       636
Self-Employed Individuals                 497
Trust                                     408
Housing Co-op                             152
Joint Venture                             129
Independent Contractors                   116
Single Member LLC                          76
Tribal Concerns                            63
Tenant in Common                           31
501(c) – Non Profit except 3,4,6,          10
Rollover as Business Start-Ups (ROB         3
Qualified Joint-Venture (spouses)           2
501(c)19 – Non Profit Veterans              2
Name: BusinessType, dtype: int64

<b>Hashing Code Values

In [16]:
ppp_df_hash = ppp_df
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,Paint and Coating Manufacturing,325 Chemicals,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC"
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,Landscaping Services,999 Other,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC"
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,NaN,NaN,Not Available,0000,00,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA"
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,New Single-Family Housing Construction (except...,999 Other,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA"
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,Used Household and Office Goods Moving,999 Other,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI"

Industry Conditions

In [17]:
ppp_df_hash["INDcode"] = 'IND' + ppp_df_hash["NA"]
ppp_df_hash["SScode"] = 'SS' + ppp_df_hash["4DigitNAICS"].str[-2:]
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,IndustrySubsector,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,"3255 Paint, Coating, and Adhesive Manufacturing",3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,5617 Services to Buildings and Dwellings,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,Not Available,0000,00,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND00,SS00
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,2361 Residential Building Construction,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,4842 Specialized Freight Trucking,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42

Loan Conditions

In [18]:
loan_conditions = [
(ppp_df_hash.Loan_Range == "a $150,000-350,000" ),
(ppp_df_hash.Loan_Range == "b $350,000-1 million" ),
(ppp_df_hash.Loan_Range == "c $1-2 million" ),
(ppp_df_hash.Loan_Range == "d $2-5 million" ),
(ppp_df_hash.Loan_Range == "e $5-10 million" ),
]
loan_values = ["LR1","LR2","LR3","LR4","LR5"]
ppp_df_hash['LRcode'] = np.select(loan_conditions, loan_values)
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,4DigitNAICS,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,3255,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,5617,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,0000,00,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND00,SS00,LR2
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,2361,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,4842,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2

Job Range Conditions

In [19]:
jobrange_conditions = [
    (ppp_df_hash.job_Range == 'Fewer than 5'),
    (ppp_df_hash.job_Range == '5 to 9'),
    (ppp_df_hash.job_Range == '10 to 19'),
    (ppp_df_hash.job_Range == '20 to 49'),
    (ppp_df_hash.job_Range == '50 to 99'),
    (ppp_df_hash.job_Range == '100 to 249'),
    (ppp_df_hash.job_Range == '250 to 499'),
    (ppp_df_hash.job_Range == '500 or more'),
]

jobrange_values = ['JR1', 'JR2', 'JR3', 'JR4', 'JR5',
       'JR6', 'JR7', 'JR8']

ppp_df_hash['JRcode'] = np.select(jobrange_conditions , jobrange_values)
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,NA,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,32,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,56,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,00,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND00,SS00,LR2,JR5
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,23,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,48,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4

In [20]:
ppp_df_hash['JRcode'].value_counts()

JR4    417145
JR3    242131
JR5    161529
JR6     84789
JR2     31387
JR7     22073
JR1      5145
JR8      4358
Name: JRcode, dtype: int64

Business Type Conditions

In [21]:
businesstype_conditions = [
    (ppp_df_hash.BusinessType == "Corporation"),
    (ppp_df_hash.BusinessType == "Limited Liability Company(LLC)"),
    (ppp_df_hash.BusinessType == "Subchapter S Corporation"),
    (ppp_df_hash.BusinessType == "Non-Profit Organization"),
    (ppp_df_hash.BusinessType == "Partnership"),
    (ppp_df_hash.BusinessType == "Limited Liability Partnership"),
    (ppp_df_hash.BusinessType == "Sole Proprietorship"),
    (ppp_df_hash.BusinessType == "Professional Association"),
    (ppp_df_hash.BusinessType == "Cooperative"),
    (ppp_df_hash.BusinessType == "501(c)3 – Non Profit"),
    (ppp_df_hash.BusinessType == "Non-Profit Childcare Center"),
    (ppp_df_hash.BusinessType == "501(c)6 – Non Profit Membership"),
    (ppp_df_hash.BusinessType == "Not Available"),
    (ppp_df_hash.BusinessType == "Employee Stock Ownership Plan(ESOP)"),
    (ppp_df_hash.BusinessType == "Self-Employed Individuals"),
    (ppp_df_hash.BusinessType == "Trust"),
    (ppp_df_hash.BusinessType == "Housing Co-op"),
    (ppp_df_hash.BusinessType == "Joint Venture"),
    (ppp_df_hash.BusinessType == "Independent Contractors"),
    (ppp_df_hash.BusinessType == "Single Member LLC"),
    (ppp_df_hash.BusinessType == "Tribal Concerns"),
    (ppp_df_hash.BusinessType == "Tenant in Common"),
    (ppp_df_hash.BusinessType == "501(c) – Non Profit except 3,4,6,"),
    (ppp_df_hash.BusinessType == "Rollover as Business Start-Ups (ROB"),
    (ppp_df_hash.BusinessType == "501(c)19 – Non Profit Veterans"),
    (ppp_df_hash.BusinessType == "Qualified Joint-Venture (spouses)"),
    
    
]

businesstype_values = ["BT01", "BT02", "BT03", "BT04", "BT05", 
                       "BT06", "BT07", "BT08", "BT09", "BT10", 
                       "BT11", "BT12", "BT13", "BT14", "BT15", 
                       "BT16", "BT17", "BT18", "BT19", "BT20", 
                       "BT21", "BT22", "BT23", "BT24", "BT25",
                       "BT26"]
ppp_df_hash['BTcode'] = np.select(businesstype_conditions, businesstype_values)
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,Industry,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,Manufacturing,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,Administrative and Support and Waste Managemen...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,Not Available,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND00,SS00,LR2,JR5,BT04
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,Construction,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,Transportation and Warehousing,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13

In [22]:
ppp_df_hash['BTcode'].value_counts()

BT01    415963
BT02    261542
BT03    177322
BT04     54932
BT05     18086
BT06     12737
BT07     12429
BT08      6780
BT09      2449
BT10      1790
BT11       909
BT12       765
BT13       728
BT14       636
BT15       497
BT16       408
BT17       152
BT18       129
BT19       116
BT20        76
BT21        63
BT22        31
BT23        10
BT24         3
BT25         2
BT26         2
Name: BTcode, dtype: int64

Business Age Conditions

In [23]:
businessage_conditions = [
    (ppp_df_hash.BusinessAgeDescription == 'Existing or more than 2 years old'),
    (ppp_df_hash.BusinessAgeDescription == 'New Business or 2 years or less'),
    (ppp_df_hash.BusinessAgeDescription == 'Unanswered'),
    (ppp_df_hash.BusinessAgeDescription == 'Change of Ownership'),
    (ppp_df_hash.BusinessAgeDescription == 'Startup, Loan Funds will Open Business'),
]
businessage_values = ["BA1", "BA2", "BA3", "BA4", "BA5"]
ppp_df_hash['BAcode'] = np.select(businessage_conditions, businessage_values)
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,SBAOfficeLabel,Loan_Range,job_Range,full_add,INDcode,SScode,LRcode,JRcode,BTcode,BAcode
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"2410 Highway 15 South, Sumter, SC",IND32,SS55,LR2,JR5,BT01,BA1
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,SOUTH CAROLINA DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"7684 Southrail Road, North Charleston, SC",IND56,SS17,LR2,JR5,BT07,BA1
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,SEATTLE DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"1850 BOYER AVE E, SEATTLE, WA",IND00,SS00,LR2,JR5,BT04,BA2
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,SANTA ANA DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"1661 MARTIN RANCH RD, SAN BERNARDINO, CA",IND23,SS61,LR2,JR4,BT01,BA2
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,MASSACHUSETTS DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"20101 Cornillie Dr, Roseville, MI",IND48,SS42,LR2,JR4,BT13,BA3

In [24]:
ppp_df_hash['BAcode'].value_counts()

BA1    861935
BA2     54854
BA3     51056
BA4       422
BA5       290
Name: BAcode, dtype: int64

<b>Alt Process Codes

In [25]:
ppp_df_hash["PMcode"] = ppp_df_hash["ProcessingMethod"] # PPP/PPS
ppp_df_hash["NPcode"] = 'NP' + ppp_df_hash["NonProfit"] # Y/N
ppp_df_hash["LMIcode"] = 'LMI' +ppp_df_hash["LMIIndicator"] #Y/N
ppp_df_hash["HZcode"] = 'HZ' + ppp_df_hash["HubzoneIndicator"] #Y/N
ppp_df_hash["RUcode"] = ppp_df_hash["RuralUrbanIndicator"] #U/R
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,SS55,LR2,JR5,BT01,BA1,PPP,NPN,LMIN,HZN,U
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,SS17,LR2,JR5,BT07,BA1,PPP,NPN,LMIY,HZY,U
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,SS00,LR2,JR5,BT04,BA2,PPP,NPY,LMIN,HZN,U
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,SS61,LR2,JR4,BT01,BA2,PPP,NPN,LMIN,HZN,U
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,SS42,LR2,JR4,BT13,BA3,PPP,NPN,LMIN,HZN,U

In [26]:
md_groups = ppp_df_hash.loc[ppp_df_hash["BorrowerState"] == "MD"]
md_groups.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode
425853,425853,425853,4142717108,4/12/20,373,PPP,"PT NETWORK, LLC",501 Fairmount Ave,Towson,MD,...,SS13,LR5,JR8,BT02,BA1,PPP,NPN,LMIY,HZN,U
425854,425854,425854,4682157009,4/4/20,373,PPP,"GMS MINE REPAIR AND MAINTENANCE, INC.",PO Box 2446 32 Enterprise Drive,OAKLAND,MD,...,SS21,LR5,JR8,BT01,BA1,PPP,NPN,LMIN,HZN,R
425855,425855,425855,8298497108,4/15/20,373,PPP,"GSE SYSTEMS, INC.",1332 Londontown Blvd 200,Sykesville,MD,...,SS33,LR5,JR7,BT01,BA1,PPP,NPN,LMIN,HZN,R
425856,425856,425856,8415647105,4/15/20,373,PPP,"MISSION BBQ MANAGEMENT, LLC",7750 Governor Ritchie Highway,Glen Burnie,MD,...,SS25,LR5,JR8,BT02,BA1,PPP,NPN,LMIN,HZN,U
425857,425857,425857,9405257009,4/9/20,373,PPP,LEMEK LLC,8184 Lark Brown Road Suite 201,ELKRIDGE,MD,...,SS25,LR5,JR8,BT03,BA1,PPP,NPN,LMIN,HZN,U

Creating HASHcodes

In [27]:
### Industry, Subsector
ppp_df_hash["INDSScode"] = ppp_df_hash["INDcode"]  + ppp_df_hash["SScode"]


# Loan Range, Business Type, Industry, Subsector
#ppp_df_hash["HASHcodebase1"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode']
#ppp_df_hash["HASHcodebase2"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['JRcode']
#ppp_df_hash["HASHcodebase3"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['BTcode']
#ppp_df_hash["HASHcodebase4"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['BAcode']
#ppp_df_hash["HASHcodebase5"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['PMcode']
# Loan Range, Business Type, Industry, Subsector
#ppp_df_hash["HASHcodebaseJR"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] 
# Loan Range, Business Type, Industry, Subsector
ppp_df_hash["HASHcodebaseJRBT"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] 
# Loan Range, Business Type, JobRange, Industry, Subsector
#ppp_df_hash["HASHcodebaseJRBTBA"] =  ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] +ppp_df_hash['LRcode'] + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash['BAcode']


# Loan Range, Business Type, JobRange, Industry, Subsector, ProcessingMethod
ppp_df_hash["HASHcodePM"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] + ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash['BAcode'] + ppp_df_hash["PMcode"]
# Loan Range, Business Type, JobRange, Industry, Subsector, ProcessingMethod, Nonprofit, LMI, Hubzone, RuralUrban
#ppp_df_hash["HASHcodefull"] = ppp_df_hash["INDcode"] + ppp_df_hash["SScode"] + ppp_df_hash['LRcode']  + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash["PMcode"] + ppp_df_hash["NPcode"] + ppp_df_hash["LMIcode"] + ppp_df_hash["HZcode"]  + ppp_df_hash["RUcode"]
#ppp_df_hash["HASHcodePMr"] = ppp_df_hash["PMcode"] + ppp_df_hash['LRcode'] + ppp_df_hash['BAcode'] + ppp_df_hash['JRcode'] + ppp_df_hash['BTcode'] + ppp_df_hash["INDcode"] + ppp_df_hash["SScode"]  
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodebaseJRBT,HASHcodePM
0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,SC,...,BT01,BA1,PPP,NPN,LMIN,HZN,U,IND32SS55,IND32SS55LR2JR5BT01,IND32SS55LR2JR5BT01BA1PPP
1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,SC,...,BT07,BA1,PPP,NPN,LMIY,HZY,U,IND56SS17,IND56SS17LR2JR5BT07,IND56SS17LR2JR5BT07BA1PPP
2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,WA,...,BT04,BA2,PPP,NPY,LMIN,HZN,U,IND00SS00,IND00SS00LR2JR5BT04,IND00SS00LR2JR5BT04BA2PPP
3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,CA,...,BT01,BA2,PPP,NPN,LMIN,HZN,U,IND23SS61,IND23SS61LR2JR4BT01,IND23SS61LR2JR4BT01BA2PPP
4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,MI,...,BT13,BA3,PPP,NPN,LMIN,HZN,U,IND48SS42,IND48SS42LR2JR4BT13,IND48SS42LR2JR4BT13BA3PPP

In [28]:
#md_groups = md_groups.groupby(["INDcode", "Industry", "INDSScode", "IndustrySubsector"]).agg({"LoanNumber":"count"})
#md_groups.shape[0] #290


#groups = ppp_df_hash.groupby(["INDcode", "Industry", "INDSScode", "IndustrySubsector"]).agg({"LoanNumber":"count"})
#groups.shape[0] #

In [29]:
print(ppp_df_hash["INDSScode"].nunique()) #328

'''
print(ppp_df_hash["HASHcodebase1"].nunique()) #1580 LR
print(ppp_df_hash["HASHcodebase2"].nunique()) #2431  JR
print(ppp_df_hash["HASHcodebase3"].nunique()) #3499 BT
print(ppp_df_hash["HASHcodebase4"].nunique()) #1227 BA
print(ppp_df_hash["HASHcodebase5"].nunique()) #639 PM

print(ppp_df_hash["HASHcodebaseJR"].nunique()) #6924
print(ppp_df_hash["HASHcodebaseJRBT"].nunique()) #26945
print(ppp_df_hash["HASHcodebaseJRBTBA"].nunique()) #43458
'''
print(ppp_df_hash["HASHcodePM"].nunique()) #55127


#print(ppp_df_hash["HASHcode"].nunique()) # 26945
#print(ppp_df_hash["HASHcodePM"].nunique()) # 55127
#print(ppp_df_hash["HASHcodefull"].nunique()) #108534 combinations

313
54996

In [30]:
ppp_df["ServicingLenderLocationID"].nunique() #4810
ppp_df["ServicingLenderName"].nunique() #4295

4295

Writing HASHcode File

In [ ]:
ppp_df_hash.to_csv("data/ppp_hash.csv")

:

In [32]:
ppp_df_hash["BTcode"].value_counts()

BT01    415963
BT02    261542
BT03    177322
BT04     54932
BT05     18086
BT06     12737
BT07     12429
BT08      6780
BT09      2449
BT10      1790
BT11       909
BT12       765
BT13       728
BT14       636
BT15       497
BT16       408
BT17       152
BT18       129
BT19       116
BT20        76
BT21        63
BT22        31
BT23        10
BT24         3
BT25         2
BT26         2
Name: BTcode, dtype: int64

In [33]:
print(ppp_df_hash.isnull().sum())

Unnamed: 0                          0
Unnamed: 0.1                        0
LoanNumber                          0
DateApproved                        0
SBAOfficeCode                       0
ProcessingMethod                    0
BorrowerName                        4
BorrowerAddress                     6
BorrowerCity                        4
BorrowerState                       0
BorrowerZip                        12
LoanStatusDate                 281932
LoanStatus                          0
Term                                0
SBAGuarantyPercentage               0
InitialApprovalAmount               0
CurrentApprovalAmount               0
UndisbursedAmount                 219
FranchiseName                  933151
ServicingLenderLocationID           0
ServicingLenderName                 0
ServicingLenderAddress              0
ServicingLenderCity                 0
ServicingLenderState                0
ServicingLenderZip                  0
RuralUrbanIndicator                 0
HubzoneIndicator                    0
LMIIndicator                        0
BusinessAgeDescription              0
ProjectCity                        13
ProjectCountyName                  57
ProjectState                        9
ProjectZip                         14
CD                                 46
JobsReported                        1
NAICSCode                           0
Race                                0
Ethnicity                           0
UTILITIES_PROCEED              629071
PAYROLL_PROCEED                  1824
MORTGAGE_INTEREST_PROCEED      922101
RENT_PROCEED                   868916
REFINANCE_EIDL_PROCEED         945363
HEALTH_CARE_PROCEED            910989
DEBT_INTEREST_PROCEED          936594
BusinessType                        0
OriginatingLenderLocationID         0
OriginatingLender                   0
OriginatingLenderCity               0
OriginatingLenderState              0
Gender                              0
Veteran                             0
NonProfit                           0
ForgivenessAmount              207884
ForgivenessDate                207884
Estimated_LenderPercent             0
Estimated_LenderProfit              0
DateApproved_ts                     0
ForgivenessDate_ts                  0
LongName                        12182
TRIIndustrySector               12182
IndustrySubsector                   0
4DigitNAICS                         0
NA                                  0
Industry                            0
SBAOfficeLabel                      0
Loan_Range                          0
job_Range                           0
full_add                            6
INDcode                             0
SScode                              0
LRcode                              0
JRcode                              0
BTcode                              0
BAcode                              0
PMcode                              0
NPcode                              0
LMIcode                             0
HZcode                              0
RUcode                              0
INDSScode                           0
HASHcodebaseJRBT                    0
HASHcodePM                          0
dtype: int64

In [34]:
## option FIPS hashing, State, County, BlockGroup additions - separate

<b>Sorting Hash Arrays (used to combine feature groups)

In [3]:
ppp_df_hash = pd.read_csv("../../data/ppp_hash.csv")
ppp_df_hash.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,...,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodebaseJRBT,HASHcodePM
0,0,0,0,9547507704,5/1/20,464,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,...,BT01,BA1,PPP,NPN,LMIN,HZN,U,IND32SS55,IND32SS55LR2JR5BT01,IND32SS55LR2JR5BT01BA1PPP
1,1,1,1,9777677704,5/1/20,464,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,...,BT07,BA1,PPP,NPN,LMIY,HZY,U,IND56SS17,IND56SS17LR2JR5BT07,IND56SS17LR2JR5BT07BA1PPP
2,2,2,2,5791407702,5/1/20,1013,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,...,BT04,BA2,PPP,NPY,LMIN,HZN,U,IND00SS00,IND00SS00LR2JR5BT04,IND00SS00LR2JR5BT04BA2PPP
3,3,3,3,6223567700,5/1/20,920,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,...,BT01,BA2,PPP,NPN,LMIN,HZN,U,IND23SS61,IND23SS61LR2JR4BT01,IND23SS61LR2JR4BT01BA2PPP
4,4,4,4,9662437702,5/1/20,101,PPP,AERO BOX LLC,20101 Cornillie Dr,Roseville,...,BT13,BA3,PPP,NPN,LMIN,HZN,U,IND48SS42,IND48SS42LR2JR4BT13,IND48SS42LR2JR4BT13BA3PPP

In [4]:
ppp_df_hash.loc[ppp_df_hash["LoanNumber"] == 3894287707]

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,...,BTcode,BAcode,PMcode,NPcode,LMIcode,HZcode,RUcode,INDSScode,HASHcodebaseJRBT,HASHcodePM
116929,116929,116929,116929,3894287707,5/1/20,912,PPP,PHD UROLOGY,1240 S. ELISEO DRIVE SUITE 200,GREENBRAE,...,BT01,BA1,PPP,NPN,LMIY,HZN,U,IND00SS00,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP

cols= ["LoanNumber", "INDSScode", "INDcode", "SScode", "LRcode","JRcode", "BTcode", "BAcode", "PMcode", "HASHcodebaseJRBT", "HASHcodePM"]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["PMcode", "LRcode", "BAcode", "JRcode",  "BTcode", "INDcode", "SScode"], ascending=[True, True, True, True, True, True, True], ignore_index=True)
ppp_df_hashSort.head(40)

In [5]:
cols= ["LoanNumber", "INDSScode", "INDcode", "SScode", "LRcode","JRcode", "BTcode", "BAcode", "PMcode", "HASHcodebaseJRBT", "HASHcodePM", "Industry", "IndustrySubsector" ]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["INDcode", "SScode", "LRcode", "JRcode", "BAcode", "BTcode","PMcode"], ascending=[True, True, True, True, True, True, True], ignore_index=True)
ppp_df_hashSort.head(40)

,LoanNumber,INDSScode,INDcode,SScode,LRcode,JRcode,BTcode,BAcode,PMcode,HASHcodebaseJRBT,HASHcodePM,Industry,IndustrySubsector
0,3894287707,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
1,3910757707,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
2,4559867701,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
3,4533907702,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
4,9925367708,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
5,4158237710,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
6,3321447710,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
7,2366557707,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
8,3191927702,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
9,3461597700,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
10,7521657706,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
11,4203327702,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
12,4133777701,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
13,4119857705,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
14,4320877702,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
15,4272147700,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
16,1526937709,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
17,3497247702,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
18,4328877707,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
19,4124397703,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
20,1861887704,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
21,3514637704,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
22,3248217703,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
23,3336527702,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
24,4321407703,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
25,3535997706,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
26,3723007710,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
27,1100577700,IND00SS00,IND00,SS00,LR1,JR1,BT01,BA1,PPP,IND00SS00LR1JR1BT01,IND00SS00LR1JR1BT01BA1PPP,Not Available,Not Available
28,4893777704,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
29,1496967705,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
30,4381387701,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
31,4194237707,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
32,1600597702,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
33,1719447700,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
34,9823957707,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
35,7348777702,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
36,9500297705,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
37,3185537108,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
38,4189217707,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available
39,3013257710,IND00SS00,IND00,SS00,LR1,JR1,BT02,BA1,PPP,IND00SS00LR1JR1BT02,IND00SS00LR1JR1BT02BA1PPP,Not Available,Not Available

In [6]:
ppp_df_hashSort["INDSScode"].nunique()

313

In [6]:
ppp_df_hashSort["HASHcodePM"].nunique()

54996

In [16]:
print(ppp_df_hashSort["INDSScode"].nunique()) #313 
ppp_df_hashSort["INDSScode"].unique().tolist() 
print(ppp_df_hashSort.loc[ppp_df_hashSort["INDSScode"] =="IND11SS22"].count())

313
LoanNumber           303
INDSScode            303
INDcode              303
SScode               303
LRcode               303
JRcode               303
BTcode               303
BAcode               303
PMcode               303
HASHcodebaseJRBT     303
HASHcodePM           303
Industry             303
IndustrySubsector    303
dtype: int64

In [11]:
print(ppp_df_hashSort.loc[ppp_df_hashSort["JRcode"] =="JR1"].count())

LoanNumber           5145
INDSScode            5145
INDcode              5145
SScode               5145
LRcode               5145
JRcode               5145
BTcode               5145
BAcode               5145
PMcode               5145
HASHcodebaseJRBT     5145
HASHcodePM           5145
Industry             5145
IndustrySubsector    5145
dtype: int64

Output for Sorted HASHcodes

cols= ["HASHcodebase", "LoanNumber"]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["HASHcodebase"], ascending=[True])
print(ppp_df_hashSort["HASHcodebase"].nunique())
ppp_df_hashSort.head(20)

In [ ]:
#ppp_df_hashSort.to_csv("data/ppp_hashSort.csv")
read_hsh = pd.read_csv('data/ppp_hashSort.csv')
read_hsh.head()

In [3]:
read_hsh.dtypes

Unnamed: 0            int64
LoanNumber            int64
INDSScode            object
INDcode              object
SScode               object
LRcode               object
JRcode               object
BTcode               object
BAcode               object
PMcode               object
HASHcodebaseJRBT     object
HASHcodePM           object
Industry             object
IndustrySubsector    object
dtype: object

cols= ["HASHcodePM", "LoanNumber"]
ppp_df_hashSort = ppp_df_hash[cols]
ppp_df_hashSort = ppp_df_hashSort.sort_values(["HASHcodePM"], ascending=[True])
print(ppp_df_hashSort["HASHcodePM"].nunique())
ppp_df_hashSort.head(20)

In [43]:
#would need to combine loan factors and sort array
#. using haashcode sequence create layergroup for each unique combination
# if layer contains feature = INDcode add to industry group[1-21]
# if layer contains feature = SScode add to subsector group
# if layer contains feature = LRcode [1-5] add to LoanRange group[1-5]
# if layer contains feature = JRcode [1-9] add to JobsRange group[1-9]
# if layer contains feature = BTcode [1-26] add to BusinessType group[1-26]
# if layer contains feature = PMcode [1-2] add to ProcessingMethod group[1-2]